function playEnchantmentSound(type: text, sound: text, volume: number, pitch: number, at: location, players: players, origin player: player = {_}):
    if {_type} is "mining":
        for {_player} in {_players::*}:
            set {_setting} to setting "mining enchantment sounds" for {_player}

            if {_setting} is "None":
                continue

            if {_setting} is "Yours Only":
                if {_origin player} isn't set:
                    continue
                if {_player} isn't {_origin player}:
                    continue

            play sound {_sound} with volume {_volume} and pitch {_pitch} at {_at} for {_player}

    else if {_type} is "combat":
        for {_player} in {_players::*}:
            if setting "combat enchantment sounds" for {_player} is "disabled":
                continue

            play sound {_sound} with volume {_volume} and pitch {_pitch} at {_at} for {_player}

function playersWithSetting(setting: text, values: texts) :: players:
    for {_player} in all players:
        if {_values::*} contains setting {_setting} for {_player}:
            add {_player} to {_players::*}
    return {_players::*}

function saveNumberSliderSettings(player: player, category: string, nbt: nbt compound):
    loop {-setting category::%{_category}%::settings::*}:
        {-setting::%loop-value%::type} is "number slider"
        set {_key} to loop-value
        replace all " " with "_" in {_key}
        set {setting::%{_player}%::%loop-value%} to float tag "%{_key}%" of {_nbt}
        # let's just hardcode this since it's the only setting that requires an immediate inventory update
        if {_key} is "enchantment_lore_length":
            updateInventory({_player}'s inventory)
