function playEnchantmentSound(type: text, sound: text, volume: number, pitch: number, at: location, players: players, origin player: player = {_}):
    if {_type} is "mining":
        for {_player} in {_players::*}:
            set {_setting} to setting "mining enchantment sounds" for {_player}

            if {_setting} is "None":
                continue

            if {_setting} is "Yours Only":
                if {_origin player} isn't set:
                    continue
                if {_player} isn't {_origin player}:
                    continue

            play sound {_sound} with volume {_volume} and pitch {_pitch} at {_at} for {_player}

    else if {_type} is "combat":
        for {_player} in {_players::*}:
            if setting "combat enchantment sounds" for {_player} is "disabled":
                continue

            play sound {_sound} with volume {_volume} and pitch {_pitch} at {_at} for {_player}
