sword enchantment:
    id: "bats"
    display: "&f<sprite:items:item/bat_spawn_egg> &5Bats"
    max level: 5
    priority: 0
    item: bat spawn egg
    cost: "normal"

    ability:
        id: "bats"
        bind: "right click"

        > "cooldown":
            lvl. 1: 20 seconds
            lvl. 2: 18 seconds
            lvl. 3: 15 seconds
            lvl. 4: 12 seconds
            lvl. 5: 10 seconds

        > "amount":
            lvl. 1: 8
            lvl. 2: 10
            lvl. 3: 12
            lvl. 4: 14
            lvl. 5: 18

        > "distance":
            lvl. 1: 12
            lvl. 2: 14
            lvl. 3: 16
            lvl. 4: 18
            lvl. 5: 22

        > "damage":
            lvl. 1: 1
            lvl. 2: 1.5
            lvl. 3: 2
            lvl. 4: 2.5
            lvl. 5: 3

        > "healing":
            lvl. 1: 0.5
            lvl. 2: 0.6
            lvl. 3: 0.7
            lvl. 4: 0.8
            lvl. 5: 1

        > "poison":
            lvl. 1: potion effect of poison 1 for 3.5 seconds
            lvl. 2: potion effect of poison 1 for 3.5 seconds
            lvl. 3: potion effect of  poison 1 for 3.5 seconds
            lvl. 4: potion effect of poison 1 for 3.25 seconds
            lvl. 5: potion effect of poison 1 for 5 seconds

        > "aoe":
            lvl. 1: 1
            lvl. 2: 1.2
            lvl. 3: 1.4
            lvl. 4: 1.6
            lvl. 5: 2

local function getDescription(level: integer) :: string:
    set {_distance} to "distance" of "bats" at {_level}
    set {_amount} to "amount" of "bats" at {_level}
    set {_damage} to "damage" of "bats" at {_level}
    set {_healing} to "healing" of "bats" at {_level}
    set {_poison} to "poison" of "bats" at {_level}
    set {_aoe} to "aoe" of "bats" at {_level}

    return "&e[<bats>] &7summon &f%{_amount}% bats &7that travel &f%{_distance}%m &8(&7AOE: &f%{_aoe}%m&8, &7Enemy: &c%{_damage}%&f<sprite:gui:hud/heart/full>&8, &f%effectDisplay({_poison})%&8, &7You: &a%{_healing}%&f<sprite:gui:hud/heart/full>&8)"

local function bats(player: player, level: integer):
    set {_origin} to location of {_player}'s head

    set {_distance} to "distance" of "bats" at {_level}
    set {_amount} to "amount" of "bats" at {_level}
    set {_damage} to "damage" of "bats" at {_level}
    set {_healing} to "healing" of "bats" at {_level}
    set {_poison} to "poison" of "bats" at {_level}

    loop {_amount} times:
        summon bat at {_origin} ~ vector(random number between 1 and -1, random number between 1 and -1, random number between 1 and -1):
            add bat to {_bats::*}
            set {-no bar::%bat%} to true

    while size of {_bats::*} > 1:
        wait 1 tick
        if {_stop} is set:
            for {_bat} in {_bats::*}:
                delete entity within {_bat}
            stop loop

        if mod(loop-iteration, 4) is 0:
            wait 1 tick
        
        for {_bat} in {_bats::*}:
            push {_bat} forward at speed 0.25
            if distance between {_bat} and {_origin} > {_distance}: 
                set {_stop} to true
            
            loop all living entities in radius 2 around {_bat}:
                loop-entity isn't {_player}
                loop-entity isn't a bat
                difference between {_affected::%loop-entity%} and now isn't less than 0.25 seconds
                set {_affected::%loop-entity%} to now
                damage(loop-entity, {_player}, {_damage})
                heal({_player}, {_healing})
                apply {_poison} to loop-entity
