on load:
    setting("bats", "display", value: "&f<sprite:items:item/bat_spawn_egg> &5Bats")
    setting("bats", "max", value: 5)
    setting("bats", "priority", value: 0)
    setting("bats", "type", value: "sword")
    setting("bats", "item", value: bat spawn egg)

    setting("bats", "cooldown", l1: 20 seconds, l2: 18 seconds, l3: 15 seconds, l4: 12 seconds, l5: 10 seconds)
    
    setting("bats", "amount", l1: 8, l2: 10, l3: 12, l4: 14, l5: 18)
    setting("bats", "distance", l1: 12, l2: 14, l3: 16, l4: 18, l5: 22)
    setting("bats", "damage", l1: 1, l2: 1.5, l3: 2, l4: 2.5, l5: 3)
    setting("bats", "healing", l1: 0.5, l2: 0.6, l3: 0.7, l4: 0.8, l5: 1)
    setting("bats", "poison", l1: potion effect of poison 1 for 3.5 seconds, l2: potion effect of poison 1 for 3.5 seconds, l3: potion effect of  poison 1 for 3.5 seconds, l4: potion effect of poison 1 for 3.25 seconds, l5: potion effect of poison 1 for 5 seconds)
    setting("bats", "aoe", l1: 1, l2: 1.2, l3: 1.4, l4: 1.6, l5: 2)

    setting("bats", "xp cost", l2: 60_000, l3: 200_000, l4: 750_000, l5: 1_000_000)
    setting("bats", "money cost", l2: 100_000, l3: 300_000 , l4: 900_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    set {_distance} to get_setting("bats", "distance", {_level})
    set {_amount} to get_setting("bats", "amount", {_level})
    set {_damage} to get_setting("bats", "damage", {_level})
    set {_healing} to get_setting("bats", "healing", {_level})
    set {_poison} to get_setting("bats", "poison", {_level})
    set {_aoe} to get_setting("bats", "aoe", {_level})

    return "&e[RMB] &7summon &f%{_amount}% bats &7that travel &f%{_distance}%m &8(&7AOE: &f%{_aoe}%m&8, &7Enemy: &c%{_damage}%&f<sprite:gui:hud/heart/full>&8, &f%effectDisplay({_poison})%&8, &7You: &a%{_healing}%&f<sprite:gui:hud/heart/full>&8)"

local function onrightclick(player: player, item: item, level: integer):
    set {_origin} to location of {_player}'s head

    set {_distance} to get_setting("bats", "distance", {_level})
    set {_amount} to get_setting("bats", "amount", {_level})
    set {_damage} to get_setting("bats", "damage", {_level})
    set {_healing} to get_setting("bats", "healing", {_level})
    set {_poison} to get_setting("bats", "poison", {_level})

    loop {_amount} times:
        summon bat at {_origin} ~ vector(random number between 1 and -1, random number between 1 and -1, random number between 1 and -1):
            add bat to {_bats::*}
            set {-no bar::%bat%} to true

    while size of {_bats::*} > 1:
        wait 1 tick
        if {_stop} is set:
            for {_bat} in {_bats::*}:
                delete entity within {_bat}
            stop loop

        if mod(loop-iteration, 4) is 0:
            wait 1 tick
        
        for {_bat} in {_bats::*}:
            push {_bat} forward at speed 0.25
            if distance between {_bat} and {_origin} > {_distance}: 
                set {_stop} to true
            
            loop all living entities in radius 2 around {_bat}:
                loop-entity isn't {_player}
                loop-entity isn't a bat
                difference between {_affected::%loop-entity%} and now isn't less than 0.25 seconds
                set {_affected::%loop-entity%} to now
                damage(loop-entity, {_player}, {_damage})
                heal({_player}, {_healing})
                apply {_poison} to loop-entity