on load:
    create sword enchantment named "bats":
        set enchantment display to "&f<sprite:items:item/bat_spawn_egg> &5Bats"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to bat spawn egg

        level values for "cooldown":
            set level 1 to 20 seconds
            set level 2 to 18 seconds
            set level 3 to 15 seconds
            set level 4 to 12 seconds
            set level 5 to 10 seconds

        level values for "amount":
            set level 1 to 8
            set level 2 to 10
            set level 3 to 12
            set level 4 to 14
            set level 5 to 18

        level values for "distance":
            set level 1 to 12
            set level 2 to 14
            set level 3 to 16
            set level 4 to 18
            set level 5 to 22

        level values for "damage":
            set level 1 to 1
            set level 2 to 1.5
            set level 3 to 2
            set level 4 to 2.5
            set level 5 to 3

        level values for "healing":
            set level 1 to 0.5
            set level 2 to 0.6
            set level 3 to 0.7
            set level 4 to 0.8
            set level 5 to 1

        level values for "poison":
            set level 1 to potion effect of poison 1 for 3.5 seconds
            set level 2 to potion effect of poison 1 for 3.5 seconds
            set level 3 to potion effect of  poison 1 for 3.5 seconds
            set level 4 to potion effect of poison 1 for 3.25 seconds
            set level 5 to potion effect of poison 1 for 5 seconds

        level values for "aoe":
            set level 1 to 1
            set level 2 to 1.2
            set level 3 to 1.4
            set level 4 to 1.6
            set level 5 to 2

        level values for "xp cost":
            set level 2 to 60_000
            set level 3 to 200_000
            set level 4 to 750_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 900_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_distance} to "distance" of "bats" at {_level}
    set {_amount} to "amount" of "bats" at {_level}
    set {_damage} to "damage" of "bats" at {_level}
    set {_healing} to "healing" of "bats" at {_level}
    set {_poison} to "poison" of "bats" at {_level}
    set {_aoe} to "aoe" of "bats" at {_level}

    return "&e[RMB] &7summon &f%{_amount}% bats &7that travel &f%{_distance}%m &8(&7AOE: &f%{_aoe}%m&8, &7Enemy: &c%{_damage}%&f<sprite:gui:hud/heart/full>&8, &f%effectDisplay({_poison})%&8, &7You: &a%{_healing}%&f<sprite:gui:hud/heart/full>&8)"

local function onrightclick(player: player, item: item, level: integer):
    set {_origin} to location of {_player}'s head

    set {_distance} to "distance" of "bats" at {_level}
    set {_amount} to "amount" of "bats" at {_level}
    set {_damage} to "damage" of "bats" at {_level}
    set {_healing} to "healing" of "bats" at {_level}
    set {_poison} to "poison" of "bats" at {_level}

    loop {_amount} times:
        summon bat at {_origin} ~ vector(random number between 1 and -1, random number between 1 and -1, random number between 1 and -1):
            add bat to {_bats::*}
            set {-no bar::%bat%} to true

    while size of {_bats::*} > 1:
        wait 1 tick
        if {_stop} is set:
            for {_bat} in {_bats::*}:
                delete entity within {_bat}
            stop loop

        if mod(loop-iteration, 4) is 0:
            wait 1 tick
        
        for {_bat} in {_bats::*}:
            push {_bat} forward at speed 0.25
            if distance between {_bat} and {_origin} > {_distance}: 
                set {_stop} to true
            
            loop all living entities in radius 2 around {_bat}:
                loop-entity isn't {_player}
                loop-entity isn't a bat
                difference between {_affected::%loop-entity%} and now isn't less than 0.25 seconds
                set {_affected::%loop-entity%} to now
                damage(loop-entity, {_player}, {_damage})
                heal({_player}, {_healing})
                apply {_poison} to loop-entity
