on load:
    create sword enchantment named "crit":
        set enchantment display to "&f<sprite:items:item/diamond_sword> &cCrit"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to diamond sword

        level values for "chance":
            set level 1 to 10
            set level 2 to 12
            set level 3 to 14
            set level 4 to 16
            set level 5 to 20

        level values for "multiplier":
            set level 1 to 0.1
            set level 2 to 0.12
            set level 3 to 0.14
            set level 4 to 0.16
            set level 5 to 0.20

        level values for "xp cost":
            set level 2 to 6_000
            set level 3 to 24_000
            set level 4 to 100_000
            set level 5 to 400_000

        level values for "money cost":
            set level 2 to 10_000
            set level 3 to 30_000
            set level 4 to 140_000
            set level 5 to 550_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of {_level} for "crit"
    return "increase final damage by &f%{_multiplier} * 100%%%"

local function onattack(attacker: entity, sword: item, level: integer, victim: entity, damage: number) :: number:
    set {_multiplier} to "multiplier" of {_level} for "crit"
    playEnchantmentSound("combat", "minecraft:entity.bat.hurt", 1, 1, location of {_attacker}, all players)
    return {_damage} * (1 + {_multiplier})
