sword enchantment:
    id: "crit"
    display: "&f<sprite:items:item/diamond_sword> &cCrit"
    max level: 5
    priority: 10
    item: diamond sword
    cost: "cheap"

    > "chance":
        lvl. 1: 10
        lvl. 2: 12
        lvl. 3: 14
        lvl. 4: 16
        lvl. 5: 20

    > "multiplier":
        lvl. 1: 0.1
        lvl. 2: 0.12
        lvl. 3: 0.14
        lvl. 4: 0.16
        lvl. 5: 0.20

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "crit" at {_level}
    return "increase final damage by &f%{_multiplier} * 100%%%"

local function onAttack(attacker: entity, sword: item, level: integer, victim: entity, damage: number) :: number:
    set {_multiplier} to "multiplier" of "crit" at {_level}
    playEnchantmentSound("combat", "minecraft:entity.bat.hurt", 1, 1, location of {_attacker}, all players)
    return {_damage} * (1 + {_multiplier})