on load:
    create sword enchantment named "flamethrower":
        set enchantment display to "&f<sprite:items:item/blaze_powder> &6Flamethrower"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to blaze powder

        level values for "cooldown":
            set level 1 to 20 seconds
            set level 2 to 18 seconds
            set level 3 to 16 seconds
            set level 4 to 14 seconds
            set level 5 to 12 seconds

        level values for "angle":
            set level 1 to 35
            set level 2 to 40
            set level 3 to 45
            set level 4 to 50
            set level 5 to 55

        level values for "damage":
            set level 1 to 0.4
            set level 2 to 0.45
            set level 3 to 0.5
            set level 4 to 0.55
            set level 5 to 0.65

        level values for "base range":
            set level 1 to 2
            set level 2 to 2
            set level 3 to 2
            set level 4 to 2
            set level 5 to 2

        level values for "addrange":
            set level 1 to 2
            set level 2 to 2.25
            set level 3 to 2.35
            set level 4 to 2.5
            set level 5 to 2.75

        level values for "iterations":
            set level 1 to 5
            set level 2 to 5
            set level 3 to 5
            set level 4 to 5
            set level 5 to 5

        level values for "dust cost":
            set level 1 to 65
            set level 2 to 225
            set level 3 to 850
            set level 4 to 1_100
            set level 5 to 1_650

        level values for "money cost":
            set level 1 to 100_000
            set level 2 to 300_000
            set level 3 to 900_000
            set level 4 to 1_250_000
            set level 5 to 1_800_000

local function getDescription(level: integer) :: string:
    set {_damage} to "damage" of "flamethrower" at {_level}
    set {_iterations} to "iterations" of "flamethrower" at {_level}
    set {_angle} to "angle" of "flamethrower" at {_level}
    set {_addrange} to "addrange" of "flamethrower" at {_level}
    set {_range} to ("base range" of "flamethrower" at {_level}) + {_addrange}
    return "&e[LMB] &7shoots a cone of fire &8(&f%{_angle}%°&8, &f%{_range}%m&8) &7dealing &8(&f%{_damage}% &8- &f%{_damage} * {_iterations}%&f<sprite:gui:hud/heart/full>&8, &7and &f%effectDisplay("ignite", customDuration:2 seconds, showAmplifier: false)%&8)"

local function onLeftClick(player: player, item: item, level: integer):
    set {_range} to "base range" of "flamethrower" at {_level}
    set {_addrange} to "addrange" of "flamethrower" at {_level}
    set {_angle} to "angle" of "flamethrower" at {_level}
    set {_damage} to "damage" of "flamethrower" at {_level}
    set {_iterations} to "iterations" of "flamethrower" at {_level}

    loop 6 times:
        set {_markers::%loop-number%} to marker({_player}'s eye, {_player}, "flamethrower")

    loop {_iterations} times:
        wait 1 tick

        for {_marker} in {_markers::*}:
            if {_marker} isn't alive:
                delete entities within {_markers::*}
                set {_stop} to true

        if {_stop} is true:
            stop loop

        set {_starting location} to {_player}'s eye ~ vector(0, -0.35, 0)
        set {_direction} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch

        for {_marker} in {_markers::*}:
            set {_marker direction} to {_direction}
            set {_index} to loop-index parsed as number
            set {_distance} to {_range} * {_index} / size of {_markers::*}
            set vector length of {_marker direction} to {_distance}

            set {_marker location} to {_starting location} ~ {_marker direction}
            teleport {_marker} to {_marker location}

        drawConeFilled({_starting location}, {_range}, {_angle}, 16)

        for {_entity} in all living entities in radius ({_range} * 2) around {_player}:
            {_entity} is not {_player} or an armor stand
            if coneHit({_player}, {_entity}, {_range}, {_angle} * 1.25, 10) is true:
                ignite {_entity} for 2 seconds
                damage({_entity}, {_player}, {_damage})

        add {_addrange} to {_range}

    delete entities within {_markers::*}

local function drawConeFilled(origin: location, range: number, coneAngle: number, spokes: number):
    set {_half} to {_coneAngle} / 2
    set {_yaw} to -1 * yaw of {_origin}
    set {_pitch} to pitch of {_origin}

    set {_ray} to a line in direction vector(0, 0, 1) with length {_range}

    create custom small flame particle:
        count: 1
        velocity: vector(0, 0, 0)
        extra: 0
    set particle of {_ray} to last created particle
    set particle density of {_ray} to 1

    loop numbers from 0 to {_spokes}:
        set {_t} to loop-number / {_spokes}
        set {_ang} to ({_t} * {_coneAngle}) - {_half}

        draw shape {_ray} at {_origin} for 1 tick:
            rotate drawn shape around x axis by {_pitch} degrees
            rotate drawn shape around y axis by ({_yaw} + {_ang}) degrees