sword enchantment:
    id: "flamethrower"
    display: "&f<sprite:items:item/blaze_powder> &6Flamethrower"
    max level: 5
    priority: 0
    item: blaze powder
    cost: "expensive"

    ability:
        id: "flamethrower"
        bind: "left click"

        > "cooldown":
            lvl. 1: 20 seconds
            lvl. 2: 18 seconds
            lvl. 3: 16 seconds
            lvl. 4: 14 seconds
            lvl. 5: 12 seconds

        > "angle":
            lvl. 1: 35
            lvl. 2: 40
            lvl. 3: 45
            lvl. 4: 50
            lvl. 5: 55

        > "damage":
            lvl. 1: 0.4
            lvl. 2: 0.45
            lvl. 3: 0.5
            lvl. 4: 0.55
            lvl. 5: 0.65

        > "base range":
            lvl. 1: 2
            lvl. 2: 2
            lvl. 3: 2
            lvl. 4: 2
            lvl. 5: 2

        > "addrange":
            lvl. 1: 2
            lvl. 2: 2.25
            lvl. 3: 2.35
            lvl. 4: 2.5
            lvl. 5: 2.75

        > "iterations":
            lvl. 1: 5
            lvl. 2: 5
            lvl. 3: 5
            lvl. 4: 5
            lvl. 5: 5

local function getDescription(level: integer) :: string:
    set {_damage} to "damage" of "flamethrower" at {_level}
    set {_iterations} to "iterations" of "flamethrower" at {_level}
    set {_angle} to "angle" of "flamethrower" at {_level}
    set {_addrange} to "addrange" of "flamethrower" at {_level}
    set {_range} to ("base range" of "flamethrower" at {_level}) + {_addrange}
    return "&e[<flamethrower>] &7shoots a cone of fire &8(&f%{_angle}%°&8, &f%{_range}%m&8) &7dealing &8(&f%{_damage}% &8- &f%{_damage} * {_iterations}%&f<sprite:gui:hud/heart/full>&8, &7and &f%effectDisplay("ignite", customDuration:2 seconds, showAmplifier: false)%&8)"

local function flamethrower(player: player, level: integer):
    set {_range} to "base range" of "flamethrower" at {_level}
    set {_addrange} to "addrange" of "flamethrower" at {_level}
    set {_angle} to "angle" of "flamethrower" at {_level}
    set {_damage} to "damage" of "flamethrower" at {_level}
    set {_iterations} to "iterations" of "flamethrower" at {_level}

    loop 6 times:
        set {_markers::%loop-number%} to marker({_player}'s eye, {_player}, "flamethrower")

    loop {_iterations} times:
        wait 1 tick

        for {_marker} in {_markers::*}:
            if {_marker} isn't alive:
                delete entities within {_markers::*}
                set {_stop} to true

        if {_stop} is true:
            stop loop

        set {_starting location} to {_player}'s eye ~ vector(0, -0.35, 0)
        set {_direction} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch

        for {_marker} in {_markers::*}:
            set {_marker direction} to {_direction}
            set {_index} to loop-index parsed as number
            set {_distance} to {_range} * {_index} / size of {_markers::*}
            set vector length of {_marker direction} to {_distance}

            set {_marker location} to {_starting location} ~ {_marker direction}
            teleport {_marker} to {_marker location}

        drawConeFilled({_starting location}, {_range}, {_angle}, 16)

        for {_entity} in all living entities in radius ({_range} * 2) around {_player}:
            {_entity} is not {_player} or an armor stand
            if coneHit({_player}, {_entity}, {_range}, {_angle} * 1.25, 10) is true:
                ignite({_entity}, 2 seconds)
                damage({_entity}, {_player}, {_damage})

        add {_addrange} to {_range}

    delete entities within {_markers::*}

local function drawConeFilled(origin: location, range: number, coneAngle: number, spokes: number):
    set {_half} to {_coneAngle} / 2
    set {_yaw} to -1 * yaw of {_origin}
    set {_pitch} to pitch of {_origin}

    set {_ray} to a line in direction vector(0, 0, 1) with length {_range}

    create custom small flame particle:
        count: 1
        velocity: vector(0, 0, 0)
        extra: 0
    set particle of {_ray} to last created particle
    set particle density of {_ray} to 1

    loop numbers from 0 to {_spokes}:
        set {_t} to loop-number / {_spokes}
        set {_ang} to ({_t} * {_coneAngle}) - {_half}

        draw shape {_ray} at {_origin} for 1 tick:
            rotate drawn shape around x axis by {_pitch} degrees
            rotate drawn shape around y axis by ({_yaw} + {_ang}) degrees
