using reflection

on load:
    create sword enchantment named "quagmire":
        set enchantment display to "&f<sprite:blocks:block/mud> &fQuagmire"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to mud block

        create ability named "quagmire":
            set ability function to function named "quagmire"
            set ability bind to "right click"

            level values for "cooldown":
                set level 1 to 40 seconds
                set level 2 to 40 seconds
                set level 3 to 40 seconds
                set level 4 to 40 seconds
                set level 5 to 40 seconds

            level values for "radius":
                set level 1 to 4
                set level 2 to 4
                set level 3 to 5
                set level 4 to 5
                set level 5 to 6

            level values for "duration":
                set level 1 to 7 seconds
                set level 2 to 8 seconds
                set level 3 to 9 seconds
                set level 4 to 10 seconds
                set level 5 to 12 seconds

            level values for "slowness":
                set level 1 to potion effect of slowness 4 for 2 ticks
                set level 2 to potion effect of slowness 4 for 2 ticks
                set level 3 to potion effect of slowness 4 for 2 ticks
                set level 4 to potion effect of slowness 5 for 2 ticks
                set level 5 to potion effect of slowness 5 for 2 ticks

        level values for "dust cost":
            set level 2 to 65
            set level 3 to 225
            set level 4 to 4_300
            set level 5 to 6_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 1_800_000
            set level 5 to 3_100_000

local function getDescription(level: number) :: string:
    set {_radius} to "radius" of "quagmire" at {_level}
    set {_duration} to "duration" of "quagmire" at {_level}
    set {_slowness} to "slowness" of "quagmire" at {_level}

    return "&e[<quagmire>] &7set disabling mud &8(&f%effectDisplay({_slowness}, showDuration: false)%&8, &f%effectDisplay("jump disable", showAmplifier: false, showDuration: false)%&8) &7within &f%{_radius}%m &7for &f%timeFormat({_duration})%"

function quagmire(user: entity, level: number):
    set {_radius} to "radius" of "quagmire" at {_level}
    set {_duration} to "duration" of "quagmire" at {_level}
    set {_slowness} to "slowness" of "quagmire" at {_level}
    set {_jump boost} to potion effect of jump boost 255 for 2 ticks
    
    playEnchantmentSound("combat", "minecraft:item.trident.return", 1, 1, location of {_user}, all players)
    wait 10 ticks

    set {_target} to location of {_user}'s target block

    for {_block} in blocks in radius {_radius} around {_target}:
        {_block} isn't air or black concrete
        bounds at {_block} doesn't contain bound with id "spawn", bound with id "mine", or bound with id "mine flight"
        add {_block} to {_affected blocks::*}
        set block within {_block} to mud
        playEnchantmentSound("combat", "minecraft:block.mud.place", 0.05, 1, location of {_user}, all players)

    loop (ticks of {_duration}) times:
        wait 1 tick
        for {_entity} in all entities in radius {_radius} + 1 around {_target}:
            if {_entity} is gliding:
                if blocks 2 below {_entity} doesn't contain mud:
                    continue

                set gliding of {_entity} to false
                set velocity of {_entity} to vector(0, 0, 0)
                loop 5 times:
                    playEnchantmentSound("combat", "minecraft:block.mud.hit", 1, random number between 0.5 and 1, location of {_entity}, all players)
            else:
                if block 0.5 under {_entity} isn't mud:
                    continue

            apply {_slowness} to {_entity}
            apply {_jump boost} to {_entity}
        
    wait 1 tick

    for {_block} in {_affected blocks::*}:
        if y coordinate of {_block} is -0.5:
            set block within {_block} to gray concrete
        else:
            set block within {_block} to air
        for {_entity} in all entities in radius 1 around {_block}:
            if block at {_entity} isn't air:
                teleport {_entity} to {_entity} ~ vector(0, 1, 0)