sword enchantment:
    id: "quagmire"
    display: "&f<sprite:blocks:block/mud> &fQuagmire"
    max level: 5
    priority: 0
    item: mud block
    cost: "normal"

    ability:
        id: "quagmire"
        bind: "right click"
        
        > "cooldown":
            lvl. 1: 40 seconds
            lvl. 2: 40 seconds
            lvl. 3: 40 seconds
            lvl. 4: 40 seconds
            lvl. 5: 40 seconds

        > "radius":
            lvl. 1: 4
            lvl. 2: 4
            lvl. 3: 5
            lvl. 4: 5
            lvl. 5: 6

        > "duration":
            lvl. 1: 7 seconds
            lvl. 2: 8 seconds
            lvl. 3: 9 seconds
            lvl. 4: 10 seconds
            lvl. 5: 12 seconds

        > "slowness":
            lvl. 1: potion effect of slowness 4 for 2 ticks
            lvl. 2: potion effect of slowness 4 for 2 ticks
            lvl. 3: potion effect of slowness 4 for 2 ticks
            lvl. 4: potion effect of slowness 5 for 2 ticks
            lvl. 5: potion effect of slowness 5 for 2 ticks

local function getDescription(level: number) :: string:
    set {_radius} to "radius" of "quagmire" at {_level}
    set {_duration} to "duration" of "quagmire" at {_level}
    set {_slowness} to "slowness" of "quagmire" at {_level}

    return "&e[<quagmire>] &7set disabling mud &8(&f%effectDisplay({_slowness}, showDuration: false)%&8, &f%effectDisplay("jump disable", showAmplifier: false, showDuration: false)%&8) &7within &f%{_radius}%m &7for &f%timeFormat({_duration})%"

function quagmire(user: entity, level: number):
    set {_radius} to "radius" of "quagmire" at {_level}
    set {_duration} to "duration" of "quagmire" at {_level}
    set {_slowness} to "slowness" of "quagmire" at {_level}
    set {_jump boost} to potion effect of jump boost 255 for 2 ticks
    
    playEnchantmentSound("combat", "minecraft:item.trident.return", 1, 1, location of {_user}, all players)
    wait 10 ticks

    set {_target} to location of {_user}'s target block

    for {_block} in blocks in radius {_radius} around {_target}:
        {_block} isn't air, black concrete, bedrock, or barrier
        bounds at {_block} doesn't contain (bound with id "spawn"), (bound with id "mine"), or (bound with id "mine flight")
        add {_block} to {_affected blocks::*}
        set block within {_block} to mud
        playEnchantmentSound("combat", "minecraft:block.mud.place", 0.05, 1, location of {_user}, all players)

    loop (ticks of {_duration}) times:
        wait 1 tick
        for {_entity} in all entities in radius ({_radius} + 1) around {_target}:
            if {_entity} is gliding:
                if blocks 2 below {_entity} doesn't contain mud:
                    continue

                set gliding of {_entity} to false
                set velocity of {_entity} to vector(0, 0, 0)
                loop 5 times:
                    playEnchantmentSound("combat", "minecraft:block.mud.hit", 1, random number between 0.5 and 1, location of {_entity}, all players)
            else:
                if block 0.5 under {_entity} isn't mud:
                    continue

            apply {_slowness} to {_entity}
            apply {_jump boost} to {_entity}
        
    wait 1 tick

    for {_block} in {_affected blocks::*}:
        if y coordinate of {_block} is -0.5:
            set block within {_block} to gray concrete
        else:
            set block within {_block} to air
        for {_entity} in all entities in radius 1 around {_block}:
            if block at {_entity} isn't air:
                teleport {_entity} to {_entity} ~ vector(0, 1, 0)