using reflection

on load:
    create sword enchantment named "quagmire":
        set enchantment display to "&f<sprite:blocks:block/mud> &fQuagmire"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to mud block

        create ability named "quagmire":
            set ability function to function named "quagmire"
            set ability bind to "right click"

        level values for "dust cost":
            set level 2 to 65
            set level 3 to 225
            set level 4 to 4_300
            set level 5 to 6_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 1_800_000
            set level 5 to 3_100_000

local function getDescription(level: number) :: string:
    return "&e[<quagmire>] &7Do Something"

function quagmire(user: entity, level: number):
    broadcast "%{_user}% %{_level}%"