on load:
    create sword enchantment named "snatch":
        set enchantment display to "&f<sprite:items:item/ominous_bottle> &5Snatch"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to ominous bottle

        level values for "cooldown":
            set level 1 to 20 seconds
            set level 2 to 18 seconds
            set level 3 to 15 seconds
            set level 4 to 12 seconds
            set level 5 to 10 seconds

        level values for "distance":
            set level 1 to 20
            set level 2 to 22
            set level 3 to 25
            set level 4 to 27
            set level 5 to 30

        level values for "disable duration":
            set level 1 to 2 seconds
            set level 2 to 3 seconds
            set level 3 to 4 seconds
            set level 4 to 5 seconds
            set level 5 to 6 seconds

        level values for "xp cost":
            set level 2 to 60_000
            set level 3 to 200_000
            set level 4 to 750_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 900_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_distance} to "distance" of "snatch" at {_level}
    set {_disable duration} to "disable duration" of "snatch" at {_level}
    return "&e[LMB] &7projectile that pulls in entities within &f%{_distance}%m&8, &7and applies &f%effectDisplay("elytra disable", customDuration: {_disable duration}, showAmplifier: false)%."

local function onLeftClick(player: player, item: item, level: integer):
    set {_origin} to location of {_player}'s head
    set {_direction} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch
    set {_distance} to "distance" of "snatch" at {_level}
    set {_steps} to {_distance} * 4

    loop {_steps} times:
        if {_stop} is set:
            stop loop

        if mod(loop-iteration, 4) is 0:
            wait 1 tick
        set {_vector} to {_direction}
        set vector length of {_vector} to loop-value / 4
        set {_bullet} to {_origin} ~ {_vector}

        draw 2 blue dust particle at {_bullet}
        loop all living entities in radius 2 around {_bullet}:
            if loop-entity is not {_player}:
                set cooldown of elytra for loop-entity to 3 seconds
                delete {_bullet}
                while distance between loop-entity and {_player} > 2.5:
                    wait 1 tick
                    add 1 to {_ticks}
                    if {_ticks} > 60:
                        set {_stop} to true
                        stop loop
                    push loop-entity towards {_player} with speed 0.25
                set {_stop} to true
