sword enchantment:
    id: "snatch"
    display: "&f<sprite:items:item/ominous_bottle> &5Snatch"
    max level: 5
    priority: 0
    item: ominous bottle
    cost: "normal"

    ability:
        id: "snatch"
        bind: "left click"

        > "cooldown":
            lvl. 1: 20 seconds
            lvl. 2: 18 seconds
            lvl. 3: 15 seconds
            lvl. 4: 12 seconds
            lvl. 5: 10 seconds

        > "distance":
            lvl. 1: 20
            lvl. 2: 22
            lvl. 3: 25
            lvl. 4: 27
            lvl. 5: 30

        > "disable duration":
            lvl. 1: 2 seconds
            lvl. 2: 3 seconds
            lvl. 3: 4 seconds
            lvl. 4: 5 seconds
            lvl. 5: 6 seconds

local function getDescription(level: integer) :: string:
    set {_distance} to "distance" of "snatch" at {_level}
    set {_disable duration} to "disable duration" of "snatch" at {_level}
    return "&e[<snatch>] &7pull in a target within &f%{_distance}%m&8, &7and apply &f%effectDisplay("elytra disable", customDuration: {_disable duration}, showAmplifier: false)%."

local function snatch(player: player, level: integer):
    set {_origin} to location of {_player}'s head
    set {_direction} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch
    set {_distance} to "distance" of "snatch" at {_level}
    set {_steps} to {_distance} * 4

    loop {_steps} times:
        if {_stop} is set:
            stop loop

        if mod(loop-iteration, 4) is 0:
            wait 1 tick
        set {_vector} to {_direction}
        set vector length of {_vector} to loop-value / 4
        set {_bullet} to {_origin} ~ {_vector}

        draw 2 blue dust particle at {_bullet}
        loop all living entities in radius 2 around {_bullet}:
            if loop-entity is not {_player}:
                set cooldown of elytra for loop-entity to 3 seconds
                delete {_bullet}
                while distance between loop-entity and {_player} > 2.5:
                    wait 1 tick
                    add 1 to {_ticks}
                    if {_ticks} > 60:
                        set {_stop} to true
                        stop loop
                    push loop-entity towards {_player} with speed 0.25
                set {_stop} to true
