ultimate sword enchantment:
    id: "amatarasu"
    display: "&f<sprite:particles:sculk_soul_7> <rainbow><bold>Amatarasu"
    max level: 5
    priority: 0
    item: netherite nautilus armor
    cost: "normal"

    ability:
        id: "amatarasu"
        bind: "left click"

        > "dps":
            lvl. 1: 0.5
            lvl. 2: 0.55
            lvl. 3: 0.6
            lvl. 4: 0.65
            lvl. 5: 0.7

        > "blindness":
            lvl. 1: potion effect of blindness 1 for 3 seconds
            lvl. 2: potion effect of blindness 1 for 3 seconds
            lvl. 3: potion effect of blindness 1 for 3 seconds
            lvl. 4: potion effect of blindness 1 for 3 seconds
            lvl. 5: potion effect of blindness 1 for 3 seconds

        > "blindness chance":
            lvl. 1: 33%
            lvl. 2: 30%
            lvl. 3: 25%
            lvl. 4: 20%
            lvl. 5: 10%

        > "cooldown":
            lvl. 1: 30 seconds
            lvl. 2: 27 seconds
            lvl. 3: 24 seconds
            lvl. 4: 21 seconds
            lvl. 5: 18 seconds

local function getDescription(level: integer) :: string:
    set {_dps} to "dps" of "amatarasu" at {_level}
    set {_blindness chance} to "blindness chance" of "amatarasu" at {_level}
    set {_blindness} to "blindness" of "amatarasu" at {_level}
    return "&e[<amatarasu>] &7set black flames to your target for &f7s &8(&c%{_dps}%&4<sprite:gui:hud/heart/full>&8/&fs &8, &7disable natural healing&8, &7Recoil&8: &f%{_blindness chance} * 100%%% &7for &f%effectDisplay({_blindness})%&8)"

local function amatarasu(player: player, level: integer):
    set {_target} to {_player}'s target entity
    if any:
        {_target} isn't set
        {_target} is dead
        {_target} isn't a living entity
        {_target} is invisible
    then:
        resetEnchantCooldown({_player}, "amatarasu")
    else:
        set {_chance} to "blindness chance" of "amatarasu" at {_level}
        chance of {_chance}:
            set {_blindness} to "blindness" of "amatarasu" at {_level}
            add {_blindness} to {_player}'s potion effects

        set {_dps} to "dps" of "amatarasu" at {_level}
        set {_per second} to 5
        set {_ticks} to {_per second} * 7
        set {_damage per tick} to {_dps} / {_per second}
        set {-amatarasu ends::%{_target}%} to 7 seconds from now

        set {_displays::*} to amatarasuDisplays({_target})

        loop {_ticks} times:
            if any:
                {_target} is dead
                {-amatarasu ends::%{_target}%} isn't set
            then:
                stop loop

            damage({_target}, {_player}, {_damage per tick})

            set interpolation duration of {_displays::*} to 2 ticks

            for {_display} in {_displays::*}:

                rotate {_display} around local y-axis by random number between -100 and 100
                rotate {_display} around local z-axis by random number between -50 and 50

                set {_scale} to random number between 0.35 and 0.85
                set scale of {_display} to vector({_scale}, {_scale}, {_scale})

            wait 1 / {_per second} * 1 second

        delete entities within {_displays::*}

on heal due to satiated:
    {-amatarasu ends::%player%} is set
    {-amatarasu ends::%player%} isn't in the past
    cancel event

on death:
    delete {-amatarasu ends::%victim%}
