on load:
    create ultimate sword enchantment named "cleave":
        set enchantment display to "&f<sprite:particles:damage> <rainbow><bold>Cleave"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to netherite spear

        level values for "requirement":
            set level 1 to 5
            set level 2 to 4
            set level 3 to 3
            set level 4 to 2
            set level 5 to 1

        level values for "damage":
            set level 1 to 1
            set level 2 to 1.15
            set level 3 to 1.35
            set level 4 to 1.45
            set level 5 to 1.75

        level values for "bleed":
            set level 1 to 0.5
            set level 2 to 0.6
            set level 3 to 0.7
            set level 4 to 0.8
            set level 5 to 1

        level values for "bleed duration":
            set level 1 to 3 seconds
            set level 2 to 3 seconds
            set level 3 to 3 seconds
            set level 4 to 3 seconds
            set level 5 to 3 seconds

        level values for "distance":
            set level 1 to 5
            set level 2 to 6
            set level 3 to 7
            set level 4 to 8
            set level 5 to 9

        level values for "radius":
            set level 1 to 2
            set level 2 to 2.5
            set level 3 to 3
            set level 4 to 3.5
            set level 5 to 4

        level values for "dust cost":
            set level 1 to 275
            set level 2 to 900
            set level 3 to 1_650
            set level 4 to 12_000
            set level 5 to 42_000

        level values for "money cost":
            set level 1 to 350_000
            set level 2 to 1_000_000
            set level 3 to 2_000_000
            set level 4 to 5_600_000
            set level 5 to 12_800_000

local function getDescription(level: integer) :: string:
    set {_damage} to "damage" of "cleave" at {_level}
    set {_bleed} to "bleed" of "cleave" at {_level}
    set {_bleed duration} to "bleed duration" of "cleave" at {_level}
    set {_requirement} to "requirement" of "cleave" at {_level}
    set {_distance} to "distance" of "cleave" at {_level}
    set {_radius} to "radius" of "cleave" at {_level}
    return "after &f%{_requirement}% &7attacks, &e[LMB] &7will cleave enemies. &8(&c%{_damage}%&f<sprite:gui:hud/heart/full>&8, &c%{_bleed}%&f<sprite:gui:hud/heart/full> &7over &f%timeFormat({_bleed duration})%&8, &f%{_distance}%m &7range, &f%{_radius}%m &7radius&8)"

local function onLeftClick(player: player, item: item, level: integer):
    set {_requirement} to "requirement" of "cleave" at {_level}
    if {-cleave::%{_player}%} >= {_requirement}:
        delete {-cleave::%{_player}%}
        set {_damage} to "damage" of "cleave" at {_level}
        set {_bleed} to "bleed" of "cleave" at {_level}
        set {_bleed duration} to "bleed duration" of "cleave" at {_level}
        set {_distance} to "distance" of "cleave" at {_level}
        set {_radius} to "radius" of "cleave" at {_level}

        playEnchantmentSound("combat", "entity.player.attack.sweep", 1, 1, location of {_player}, all players)
        set {_origin} to location of {_player}'s head
        set {_vector} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch

        add {_player} to {_affected::*}
        loop {_distance} * 4 times:
            if mod(loop-iteration, 5) is 0:
                wait 1 tick
            set vector length of {_vector} to loop-value / 4
            set {_bullet} to {_origin} ~ {_vector}
            playEnchantmentSound("combat", "entity.player.attack.sweep", 1, 1, {_bullet}, all players)
            loop clamp(({_radius} / 2), 1, 4) times:
                draw 4 sweep attack particle at ({_bullet} ~ vector((random numbers between -1 and 1), (random numbers between -1 and 1), (random numbers between -1 and 1)))

            loop all living entities in radius {_radius} around {_bullet}:
                {_affected::*} doesn't contain loop-entity
                add loop-entity to {_affected::*}
                cleave(loop-entity, {_player}, {_level})

local function onAttack(attacker: entity, sword: item, level: integer, victim: entity, damage: number) :: number:
    add 1 to {-cleave::%{_attacker}%}
    if {-cleave::%{_attacker}%} >= "requirement" of "cleave" at {_level}:
        send action bar "&4&lCleave &fis ready." to {_attacker}
    return 0

local function cleave(victim: entity, attacker: entity, level: integer):
    set {_damage} to "damage" of "cleave" at {_level}
    set {_bleed} to "bleed" of "cleave" at {_level}
    set {_bleed duration} to "bleed duration" of "cleave" at {_level}

    damage({_victim}, {_attacker}, {_damage})

    set {_interval} to 5 ticks
    set {_hits} to floor((ticks of {_bleed duration}) / 5)
    if {_hits} <= 0:
        set {_hits} to 1

    set {_bleed per hit} to {_bleed} / {_hits}

    loop {_hits} times:
        wait {_interval}
        if {_victim} is alive:
            damage({_victim}, {_attacker}, {_bleed per hit})
            show 4 red dust particle at ({_victim} ~ vector(random number between 0 and 1, random number between 0.5 and 1.5, random number between 0 and 1))
            