ultimate sword enchantment:
    id: "cleave"
    display: "&f<sprite:particles:damage> <rainbow><bold>Cleave"
    max level: 5
    priority: 0
    item: netherite spear
    cost: "normal"

    ability:
        id: "cleave"
        bind: "left click"

        > "requirement":
            lvl. 1: 5
            lvl. 2: 4
            lvl. 3: 3
            lvl. 4: 2
            lvl. 5: 1

        > "damage":
            lvl. 1: 1
            lvl. 2: 1.15
            lvl. 3: 1.35
            lvl. 4: 1.45
            lvl. 5: 1.75

        > "bleed":
            lvl. 1: 0.5
            lvl. 2: 0.6
            lvl. 3: 0.7
            lvl. 4: 0.8
            lvl. 5: 1

        > "bleed duration":
            lvl. 1: 3 seconds
            lvl. 2: 3 seconds
            lvl. 3: 3 seconds
            lvl. 4: 3 seconds
            lvl. 5: 3 seconds

        > "distance":
            lvl. 1: 5
            lvl. 2: 6
            lvl. 3: 7
            lvl. 4: 8
            lvl. 5: 9

        > "radius":
            lvl. 1: 2
            lvl. 2: 2.5
            lvl. 3: 3
            lvl. 4: 3.5
            lvl. 5: 4

local function getDescription(level: integer) :: string:
    set {_damage} to "damage" of "cleave" at {_level}
    set {_bleed} to "bleed" of "cleave" at {_level}
    set {_bleed duration} to "bleed duration" of "cleave" at {_level}
    set {_requirement} to "requirement" of "cleave" at {_level}
    set {_distance} to "distance" of "cleave" at {_level}
    set {_radius} to "radius" of "cleave" at {_level}
    return "after &f%{_requirement}% &7attacks, &e[<cleave>] &7will cleave enemies. &8(&c%{_damage}%&f<sprite:gui:hud/heart/full>&8, &c%{_bleed}%&f<sprite:gui:hud/heart/full> &7over &f%timeFormat({_bleed duration})%&8, &f%{_distance}%m &7range, &f%{_radius}%m &7radius&8)"

local function cleave(player: player, level: integer):
    set {_requirement} to "requirement" of "cleave" at {_level}
    if {-cleave::%{_player}%} >= {_requirement}:
        delete {-cleave::%{_player}%}
        set {_damage} to "damage" of "cleave" at {_level}
        set {_bleed} to "bleed" of "cleave" at {_level}
        set {_bleed duration} to "bleed duration" of "cleave" at {_level}
        set {_distance} to "distance" of "cleave" at {_level}
        set {_radius} to "radius" of "cleave" at {_level}

        playEnchantmentSound("combat", "entity.player.attack.sweep", 1, 1, location of {_player}, all players)
        set {_origin} to location of {_player}'s head
        set {_vector} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch

        add {_player} to {_affected::*}
        loop {_distance} * 4 times:
            if mod(loop-iteration, 5) is 0:
                wait 1 tick
            set vector length of {_vector} to loop-value / 4
            set {_bullet} to {_origin} ~ {_vector}
            playEnchantmentSound("combat", "entity.player.attack.sweep", 1, 1, {_bullet}, all players)
            loop clamp(({_radius} / 2), 1, 4) times:
                draw 4 sweep attack particle at ({_bullet} ~ vector((random numbers between -1 and 1), (random numbers between -1 and 1), (random numbers between -1 and 1)))

            loop all living entities in radius {_radius} around {_bullet}:
                {_affected::*} doesn't contain loop-entity
                add loop-entity to {_affected::*}
                applyCleave(loop-entity, {_player}, {_level})

local function onAttack(attacker: entity, sword: item, level: integer, victim: entity, damage: number) :: number:
    add 1 to {-cleave::%{_attacker}%}
    if {-cleave::%{_attacker}%} >= "requirement" of "cleave" at {_level}:
        send action bar "&4&lCleave &fis ready." to {_attacker}
    return 0

local function applyCleave(victim: entity, attacker: entity, level: integer):
    set {_damage} to "damage" of "cleave" at {_level}
    set {_bleed} to "bleed" of "cleave" at {_level}
    set {_bleed duration} to "bleed duration" of "cleave" at {_level}

    damage({_victim}, {_attacker}, {_damage})

    set {_interval} to 5 ticks
    set {_hits} to floor((ticks of {_bleed duration}) / 5)
    if {_hits} <= 0:
        set {_hits} to 1

    set {_bleed per hit} to {_bleed} / {_hits}

    loop {_hits} times:
        wait {_interval}
        if {_victim} is alive:
            damage({_victim}, {_attacker}, {_bleed per hit})
            show 4 red dust particle at ({_victim} ~ vector(random number between 0 and 1, random number between 0.5 and 1.5, random number between 0 and 1))
            
