define new bot named "beans":
    token: "%{-discord token}%"

    intents: guild members, guild moderation, guild messages, message content

on bot loaded:
    set {-discord::server chat channel} to text channel with id "821817712430940162"
    set {-discord::staff chat channel} to text channel with id "782793644226510859"
    set {-discord::beans} to guild with id "538205671712358450"
    set {-discord::linked role} to role with id "1504290363442073630"
    
    sendToServerChat("Beans is online!")
    updatePresence()

on skript stop:
    sendToServerChat("Beans is offline!")
        
function sendToServerChat(message: text):
    post {_message} to {-discord::server chat channel}

function sendToStaffChat(message: text):
    post {_message} to {-discord::staff chat channel}

function updatePresence():
    set presence of bot named "beans" to watching "beans.minehut.gg | %size of players where [{-vanish::%input%} isn't set]% players"

on join:
    {-vanish::%player%} isn't set
    updatePresence()
    set {_group} to {group::%player's uuid%} ? "default"
    sendToServerChat(":white_check_mark: **%uncolored {-prefix::%{_group}%}%%player's name%** joined the server.")

on quit:
    {-vanish::%player%} isn't set
    updatePresence()
    set {_group} to {group::%player's uuid%} ? "default"
    sendToServerChat(":x: **%uncolored {-prefix::%{_group}%}%%player's name%** left the server.")

on chat with priority monitor:
    event isn't cancelled
    set {_message} to message
    set {_name} to player's name
    set {_group} to {group::%player's uuid%} ? "default"
    set {_prefix} to uncolored {-prefix::%{_group}%}
    replace all "*" with "\*" in {_message} and {_name}
    replace all "_" with "\_" in {_message} and {_name}
    replace all "<" with "\<" in {_message} and {_name}
    replace all ">" with "\>" in {_message} and {_name}
    replace all "`" with "\`" in {_message} and {_name}
    sendToServerChat("**%{_prefix}%%{_name}%**: %{_message}%")

on message received:
    event-user is not a discord bot
    if event-channel is {-discord::server chat channel}:
        set {_id} to discord id of event-user
        set {_user} to linkedUser({_id})
        broadcast "%{_user}%"
        {_user} is set
        set {_message} to event-message
        replace all newline with " " in {_message}
        broadcast formatted "&b[Discord] &7%player_display({_user}, "[prefix][player]")%&8: &f%unformatted {_message}%"
    else if event-channel is {-discord::staff chat channel}:
        set {_id} to discord id of event-user
        set {_user} to linkedUser({_id})
        send "&8[&6Staff Chat (Discord)&8] &e%player_display({_user}, "[prefix][player]")%&8: &f%event-message%" to all players where [input has permission "beans.mod"]

command /discord:
    trigger:
        send formatted "&b<click:open_url:'https://discord.gg/wjQz6ea6JV'>Click here to join our Discord!"

slash command list:
    bot: beans
    guilds: 538205671712358450
    description: List all online players.
    trigger:
        async run 0 ticks later: 
            set {_players::*} to all players

            sort {_players::*} in descending order based on {-group weight::%{group::%input%}%}
            loop {_players::*}:
                set {_group} to {group::%loop-value%} ? "default"
                {-vanish::%loop-value%} isn't set
                add "%uncolored {-prefix::%{_group}%}%%loop-value%" to {_sorted players::*}

            make embed and store it in {_embed}:
                set title of embed to "Players (%size of {_sorted players::*}%/%max players%)"
                set embed color of embed to aqua
                set description of embed to "%{_sorted players::*} ? "No players online."%"
            reply with {_embed}