function linkedUser(discord id: text) :: offline player:
    return offlineplayer({discord linked uuid.%{_discord id}%}, false)

command /link [<text>]:
    cooldown: 5 seconds
    trigger:
        if arg 1 isn't set:
            if {discord linked account.%player%} is set:
                set {_id} to {discord linked account.%player%}
                async run 0 ticks later:
                    retrieve member with id {_id} from {-discord::beans} and store it in {_member}
                    send "Your account is linked to %{_member}%."
            else:
                send "Run /link in the Discord to generate a token."
        else:
            if {discord linked account.%player%} is set:
                set {_id} to {discord linked account.%player%}
                async run 0 ticks later:
                    retrieve member with id {_id} from {-discord::beans} and store it in {_member}
                    send "Your account is already linked to %{_member}%."
            else:
                if {-link token::%arg 1%} isn't set:
                    send "Invalid link token."
                else:
                    set {_id} to {-link token::%arg 1%}
                    set {discord linked uuid.%{_id}%} to uuid of player
                    set {discord linked account.%player%} to {_id}
                    async run 0 ticks later:
                        retrieve member with id {_id} from {-discord::beans} and store it in {_member}
                        add {-discord::linked role} to roles of {_member}
                        send "You're now linked to %{_member}%."
                        addTag(player, "verified")
                        delete {-link token::%arg 1%}
                        if {discord link reward::%player%} isn't set:
                            giveBeacons(player, 3)
                            send "&bReceived your one time link reward!"
                            set {discord link reward::%player%} to true

command /unlink:
    cooldown: 5 seconds
    trigger:
        if {discord linked account.%player%} isn't set:
            send "Your account isn't linked."
        else:
            async run 0 ticks later:
                set {_id} to {discord linked account.%player%}
                retrieve member with id {_id} from {-discord::beans} and store it in {_member}
                delete {discord linked uuid.%{_id}%}
                delete {discord linked account.%player%} 
                remove {-discord::linked role} from roles of {_member}
                removeTag(player, "verified")
                send "Your account has been unlinked from %{_member}%."

slash command link:
    bot: beans
    guilds: 538205671712358450
    description: Link your ingame and discord accounts.
    trigger:
        if {discord linked uuid.%discord id of event-user%} is set:
            reply with hidden "Your account is already linked. Use /unlink to unlink your account."
        else:
            set {_random} to first 5 characters of random uuid
            set {-link token::%{_random}%} to discord id of event-user
            reply with hidden "%{_random}%%nl%This is your link token. Use this in-game with /link <token> to link your account."

slash command unlink:
    bot: beans
    guilds: 538205671712358450
    description: Unlink your ingame and discord accounts.
    trigger:
        if {discord linked uuid.%discord id of event-user%} isn't set:
            reply with hidden "Your account isn't linked."
        else:
            set {_user} to linkedUser(discord id of event-user)
            set {_id} to discord id of event-user
            delete {discord linked uuid.%{_id}%}
            delete {discord linked account.%{_user}%} 
            remove {-discord::linked role} from roles of event-member
            removeTag({_user}, "verified")
            reply with hidden "Your account has been unlinked from %{_user}%."