on load:
    set {-vanilla enchantment::efficiency::display} to "Efficiency"
    
    set {-vanilla enchantment::efficiency::max level} to 10

    set {-vanilla enchantment::efficiency::dust cost::1} to 5
    set {-vanilla enchantment::efficiency::dust cost::2} to 15
    set {-vanilla enchantment::efficiency::dust cost::3} to 60
    set {-vanilla enchantment::efficiency::dust cost::4} to 250
    set {-vanilla enchantment::efficiency::dust cost::5} to 500
    set {-vanilla enchantment::efficiency::dust cost::6} to 750
    set {-vanilla enchantment::efficiency::dust cost::7} to 1_000
    set {-vanilla enchantment::efficiency::dust cost::8} to 1_500
    set {-vanilla enchantment::efficiency::dust cost::9} to 2_000
    set {-vanilla enchantment::efficiency::dust cost::10} to 3_000

    set {-vanilla enchantment::efficiency::money cost::1} to 1500
    set {-vanilla enchantment::efficiency::money cost::2} to 5000
    set {-vanilla enchantment::efficiency::money cost::3} to 15000
    set {-vanilla enchantment::efficiency::money cost::4} to 30000
    set {-vanilla enchantment::efficiency::money cost::5} to 75000
    set {-vanilla enchantment::efficiency::money cost::6} to 200000
    set {-vanilla enchantment::efficiency::money cost::7} to 400000
    set {-vanilla enchantment::efficiency::money cost::8} to 650000
    set {-vanilla enchantment::efficiency::money cost::9} to 850000
    set {-vanilla enchantment::efficiency::money cost::10} to 1250000