on load:
    set {-vanilla enchantment::fire aspect::display} to "Fire Aspect"
    
    set {-vanilla enchantment::fire aspect::max level} to 5

    set {-vanilla enchantment::fire aspect::dust cost::1} to 10
    set {-vanilla enchantment::fire aspect::dust cost::2} to 250
    set {-vanilla enchantment::fire aspect::dust cost::3} to 1_000
    set {-vanilla enchantment::fire aspect::dust cost::4} to 3_000
    set {-vanilla enchantment::fire aspect::dust cost::5} to 6_000

    set {-vanilla enchantment::fire aspect::money cost::1} to 12000
    set {-vanilla enchantment::fire aspect::money cost::2} to 36000
    set {-vanilla enchantment::fire aspect::money cost::3} to 150000
    set {-vanilla enchantment::fire aspect::money cost::4} to 375000
    set {-vanilla enchantment::fire aspect::money cost::5} to 750000