on load:
    set {-vanilla enchantment::flame::display} to "Flame"
    
    set {-vanilla enchantment::flame::max level} to 5

    set {-vanilla enchantment::fire aspect::dust cost::1} to 10
    set {-vanilla enchantment::fire aspect::dust cost::2} to 250
    set {-vanilla enchantment::fire aspect::dust cost::3} to 1_000
    set {-vanilla enchantment::fire aspect::dust cost::4} to 3_000
    set {-vanilla enchantment::fire aspect::dust cost::5} to 6_000

    set {-vanilla enchantment::flame::money cost::1} to 16000
    set {-vanilla enchantment::flame::money cost::2} to 32000
    set {-vanilla enchantment::flame::money cost::3} to 100000
    set {-vanilla enchantment::flame::money cost::4} to 350000
    set {-vanilla enchantment::flame::money cost::5} to 750000