on load:
    set {-vanilla enchantment::fortune::display} to "Fortune"
    
    set {-vanilla enchantment::fortune::max level} to 10

    set {-vanilla enchantment::fortune::dust cost::1} to 5
    set {-vanilla enchantment::fortune::dust cost::2} to 25
    set {-vanilla enchantment::fortune::dust cost::3} to 50
    set {-vanilla enchantment::fortune::dust cost::4} to 150
    set {-vanilla enchantment::fortune::dust cost::5} to 350
    set {-vanilla enchantment::fortune::dust cost::6} to 600
    set {-vanilla enchantment::fortune::dust cost::7} to 1_000
    set {-vanilla enchantment::fortune::dust cost::8} to 1_500
    set {-vanilla enchantment::fortune::dust cost::9} to 2_750
    set {-vanilla enchantment::fortune::dust cost::10} to 4_000

    set {-vanilla enchantment::fortune::money cost::1} to 1500
    set {-vanilla enchantment::fortune::money cost::2} to 12000
    set {-vanilla enchantment::fortune::money cost::3} to 32000
    set {-vanilla enchantment::fortune::money cost::4} to 100000
    set {-vanilla enchantment::fortune::money cost::5} to 150000
    set {-vanilla enchantment::fortune::money cost::6} to 400000
    set {-vanilla enchantment::fortune::money cost::7} to 650000
    set {-vanilla enchantment::fortune::money cost::8} to 1000000
    set {-vanilla enchantment::fortune::money cost::9} to 1500000
    set {-vanilla enchantment::fortune::money cost::10} to 2000000