on load:
    set {-vanilla enchantment::knockback::display} to "Knockback"
    
    set {-vanilla enchantment::knockback::max level} to 3

    set {-vanilla enchantment::knockback::dust cost::1} to 50
    set {-vanilla enchantment::knockback::dust cost::2} to 500
    set {-vanilla enchantment::knockback::dust cost::3} to 2_500

    set {-vanilla enchantment::knockback::money cost::1} to 6000
    set {-vanilla enchantment::knockback::money cost::2} to 100000
    set {-vanilla enchantment::knockback::money cost::3} to 750000