on load:
    set {-vanilla enchantment::knockback::display} to "Knockback"
    
    set {-vanilla enchantment::knockback::max} to 3

    set {-vanilla enchantment::knockback::xp cost::1} to 4000
    set {-vanilla enchantment::knockback::xp cost::2} to 75000
    set {-vanilla enchantment::knockback::xp cost::3} to 500000

    set {-vanilla enchantment::knockback::money cost::1} to 6000
    set {-vanilla enchantment::knockback::money cost::2} to 100000
    set {-vanilla enchantment::knockback::money cost::3} to 750000