on load:
    set {-vanilla enchantment::power::display} to "Power"
    
    set {-vanilla enchantment::power::max} to 5

    set {-vanilla enchantment::power::xp cost::1} to 4000
    set {-vanilla enchantment::power::xp cost::2} to 60_000
    set {-vanilla enchantment::power::xp cost::3} to 250_000
    set {-vanilla enchantment::power::xp cost::4} to 850_000
    set {-vanilla enchantment::power::xp cost::5} to 2_000_000

    set {-vanilla enchantment::power::money cost::1} to 5_000
    set {-vanilla enchantment::power::money cost::2} to 75_000
    set {-vanilla enchantment::power::money cost::3} to 350_000
    set {-vanilla enchantment::power::money cost::4} to 1_000_000
    set {-vanilla enchantment::power::money cost::5} to 3_000_000