on load:
    set {-vanilla enchantment::power::display} to "Power"
    
    set {-vanilla enchantment::power::max level} to 5

    set {-vanilla enchantment::power::dust cost::1} to 5
    set {-vanilla enchantment::power::dust cost::2} to 65
    set {-vanilla enchantment::power::dust cost::3} to 275
    set {-vanilla enchantment::power::dust cost::4} to 950
    set {-vanilla enchantment::power::dust cost::5} to 2_200

    set {-vanilla enchantment::power::money cost::1} to 5_000
    set {-vanilla enchantment::power::money cost::2} to 75_000
    set {-vanilla enchantment::power::money cost::3} to 350_000
    set {-vanilla enchantment::power::money cost::4} to 1_000_000
    set {-vanilla enchantment::power::money cost::5} to 3_000_000