on load:
    set {-vanilla enchantment::protection::display} to "Protection"
    
    set {-vanilla enchantment::protection::max level} to 5

    set {-vanilla enchantment::protection::dust cost::1} to 5
    set {-vanilla enchantment::protection::dust cost::2} to 50
    set {-vanilla enchantment::protection::dust cost::3} to 150
    set {-vanilla enchantment::protection::dust cost::4} to 500
    set {-vanilla enchantment::protection::dust cost::5} to 1_000

    set {-vanilla enchantment::protection::money cost::1} to 1500
    set {-vanilla enchantment::protection::money cost::2} to 5000
    set {-vanilla enchantment::protection::money cost::3} to 15000
    set {-vanilla enchantment::protection::money cost::4} to 30000
    set {-vanilla enchantment::protection::money cost::5} to 75000