on load:
    set {-vanilla enchantment::punch::display} to "Punch"
    
    set {-vanilla enchantment::punch::max level} to 3

    set {-vanilla enchantment::knockback::dust cost::1} to 50
    set {-vanilla enchantment::knockback::dust cost::2} to 500
    set {-vanilla enchantment::knockback::dust cost::3} to 2_500

    set {-vanilla enchantment::punch::money cost::1} to 12000
    set {-vanilla enchantment::punch::money cost::2} to 750000
    set {-vanilla enchantment::punch::money cost::3} to 1250000