on load:
    set {-max tier} to 4

    set {-tier::pickaxe::money cost::1} to 8000
    set {-tier::pickaxe::money cost::2} to 40000
    set {-tier::pickaxe::money cost::3} to 500000
    set {-tier::pickaxe::money cost::4} to 4000000
    set {-tier::pickaxe::dust cost::1} to 50
    set {-tier::pickaxe::dust cost::2} to 500
    set {-tier::pickaxe::dust cost::3} to 5_000
    set {-tier::pickaxe::dust cost::4} to 15_000

    set {-tier::pickaxe::max enchantments::0} to 4
    set {-tier::pickaxe::max enchantments::1} to 6
    set {-tier::pickaxe::max enchantments::2} to 8
    set {-tier::pickaxe::max enchantments::3} to 12
    set {-tier::pickaxe::max enchantments::4} to 25

    set {-tier::sword::money cost::1} to 9000
    set {-tier::sword::money cost::2} to 50000
    set {-tier::sword::money cost::3} to 400000
    set {-tier::sword::money cost::4} to 3000000
    set {-tier::sword::dust cost::1} to 50
    set {-tier::sword::dust cost::2} to 350
    set {-tier::sword::dust cost::3} to 3_000
    set {-tier::sword::dust cost::4} to 8_000

    set {-tier::sword::max enchantments::0} to 3
    set {-tier::sword::max enchantments::1} to 5
    set {-tier::sword::max enchantments::2} to 7
    set {-tier::sword::max enchantments::3} to 9
    set {-tier::sword::max enchantments::4} to 12

    set {-tier::armor::money cost::1} to 10000
    set {-tier::armor::money cost::2} to 60000
    set {-tier::armor::money cost::3} to 500000
    set {-tier::armor::money cost::4} to 3500000
    set {-tier::armor::dust cost::1} to 50
    set {-tier::armor::dust cost::2} to 350
    set {-tier::armor::dust cost::3} to 3_000
    set {-tier::armor::dust cost::4} to 8_000

    set {-tier::armor::max enchantments::0} to 3
    set {-tier::armor::max enchantments::1} to 5
    set {-tier::armor::max enchantments::2} to 7
    set {-tier::armor::max enchantments::3} to 9
    set {-tier::armor::max enchantments::4} to 12
 
    set {-tier::bow::money cost::1} to 5000
    set {-tier::bow::money cost::2} to 350000
    set {-tier::bow::money cost::3} to 1000000
    set {-tier::bow::money cost::4} to 5000000
    set {-tier::bow::dust cost::1} to 50
    set {-tier::bow::dust cost::2} to 400
    set {-tier::bow::dust cost::3} to 4_000
    set {-tier::bow::dust cost::4} to 10_000

    set {-tier::bow::max enchantments::0} to 3
    set {-tier::bow::max enchantments::1} to 5
    set {-tier::bow::max enchantments::2} to 7
    set {-tier::bow::max enchantments::3} to 9
    set {-tier::bow::max enchantments::4} to 12

    set {-tier::level requirement::1} to 0
    set {-tier::level requirement::2} to 10
    set {-tier::level requirement::3} to 25
    set {-tier::level requirement::4} to 50

function createTierUpgradeItem(player: player, item: item type) :: item type:
    set {_type} to enchantmentTypeFromItem({_item})
    if {_type} is not set:
        return barrier named "&cInvalid Item"

    set {_tier} to (data tag "tier" of {_item}) ? 0

    if {_tier} + 1 > {-max tier}:
        set {_upgrade} to bedrock named "&cMax Tier Reached" with lore "&7Your item has reached the maximum tier."
        return {_upgrade}

    set {_new tier} to {_tier} + 1
    set {_money cost} to {-tier::%{_type}%::money cost::%{_new tier}%}
    set {_dust cost} to {-tier::%{_type}%::dust cost::%{_new tier}%}
    set {_level requirement} to {-tier::level requirement::%{_new tier}%}

    set {_new enchantment limit} to {-tier::%{_type}%::max enchantments::%{_new tier}%}
    set {_old enchantment limit} to {-tier::%{_type}%::max enchantments::%{_tier}%}

    if any:
        {money::%{_player}%} < {_money cost}
        {dust::%{_player}%} < {_dust cost}
        {level::%{_player}%} < {_level requirement}
    then:
        set {_upgrade} to red concrete
    else:
        set {_upgrade} to green concrete

    set name of {_upgrade} to "&fUpgrade to Tier %{_new tier}%"
    set lore of {_upgrade} to "&7Level Requirement: %levelDisplay({_level requirement})%", "&7Money Cost: $%formatNumber({_money cost})% &7&o(%formatNumber({money::%{_player}%})%)", "&7Dust Cost: %formatNumber({_dust cost})% &7&o(%formatNumber({dust::%{_player}%})%)", "&7Enchantment Limit: &m%{_old enchantment limit}%&r &6%formatNumber({_new enchantment limit})%"
    return {_upgrade}

on inventory click:
    player's current inventory is {-upgrade gui::%player%}
    if event-item is green concrete:
        set {_result} to tryUpgradeTier(player, index of player's tool)
        send {_result} to player
        openUpgradeGui(player)
    else if event-item is red concrete:
        send tryUpgradeTier(player, index of player's tool) to player
    cancel event

function getMaxEnchantments(item: item type) :: integer:
    set {_type} to enchantmentTypeFromItem({_item})
    if {_type} is not set:
        return 0

    set {_tier} to (data tag "tier" of {_item}) ? 0
    return {-tier::%{_type}%::max enchantments::%{_tier}%}

function tryUpgradeTier(player: player, slot: integer) :: string:
    set {_item} to slot {_slot} of {_player}

    set {_type} to enchantmentTypeFromItem({_item})
    if {_type} is not set:
        return "Invalid item type."

    set {_tier} to data tag "tier" of {_item}
    set {_new tier} to {_tier} + 1
    if {_new tier} > {-max tier}:
        return "Your item cannot be upgraded any further."

    set {_money cost} to {-tier::%{_type}%::money cost::%{_new tier}%}
    set {_dust cost} to {-tier::%{_type}%::dust cost::%{_new tier}%}
    set {_level requirement} to {-tier::level requirement::%{_new tier}%}

    if {money::%{_player}%} < {_money cost}:
        return "&cYou don't have enough money."

    if {dust::%{_player}%} < {_dust cost}:
        return "&cYou don't have enough Dust."

    if {level::%{_player}%} < {_level requirement}:
        return "&cYou need to be at least level %{_level requirement}%."

    set {_new item} to upgradeTier({_item})
    if {_new item} is set:
        set slot {_slot} of {_player} to {_new item}
        remove {_money cost} from {money::%{_player}%}
        remove {_dust cost} from {dust::%{_player}%}
        return "&aSuccessfully upgraded your item to tier %{_new tier}%!"
    else:
        return "&cAn error occurred while upgrading your item."

function upgradeTier(item: item type) :: item type:
    set {_type} to enchantmentTypeFromItem({_item})
    {_type} is set
    set {_tier} to (data tag "tier" of {_item} ? 0)
    set {_new tier} to {_tier} + 1
    {_new tier} <= {-max tier}
    set data tag "tier" of {_item} to {_new tier}
    return {_item}