on load:
    set {-trim::1} to "none"
    loop trim materials:
        set {-trim::%loop-iteration + 1%} to loop-value

    set {-trim pattern::1} to "none"
    loop trim patterns:
        set {-trim pattern::%loop-iteration + 1%} to loop-value

function openTrimGui(player: player):
    if {_player}'s tool isn't tagged with paper tag "helmets":
        send "&cYou can only change the trim of helmets!" to {_player}
        stop

    set {-trim gui::%{_player}%} to hopper inventory named "Trim Selection"

    set {_material} to gold ingot named "&7Trim Material" with lore "&7Left click to go forward.", "&7Right click to go back.", ""
    set {_current material} to trim material of armor trim of {_player}'s tool

    loop {-trim::*}:
        if loop-value is "none":
            if {_current material} is not set:
                add formatted "<yellow>None" to lore of {_material}
            else:
                add formatted "<gray>None" to lore of {_material}
        else:
            set {_name} to "%loop-value%"
            replace "minecraft:" with "" in {_name}
            replace "_material" with "" in {_name}

            if loop-value is {_current material}:
                add formatted "<yellow><lang:trim_material.minecraft.%{_name}%>" to lore of {_material}
            else:
                add formatted "<gray><lang:trim_material.minecraft.%{_name}%>" to lore of {_material}

    add "" to lore of {_material}
    set slot 1 of {-trim gui::%{_player}%} to {_material}

    # Trim Pattern
    set {_pattern} to black banner named "&7Trim Pattern" with lore "&7Left click to go forward.", "&7Right click to go back.", ""
    set {_current pattern} to trim pattern of armor trim of {_player}'s tool

    loop {-trim pattern::*}:
        if loop-value is "none":
            if {_current pattern} is not set:
                add formatted "<yellow>None" to lore of {_pattern}
            else:
                add formatted "<gray>None" to lore of {_pattern}
        else:
            set {_name} to "%loop-value%"
            replace "minecraft:" with "" in {_name}
            replace "_pattern" with "" in {_name}

            if loop-value is {_current pattern}:
                add formatted "<yellow><lang:trim_pattern.minecraft.%{_name}%>" to lore of {_pattern}
            else:
                add formatted "<gray><lang:trim_pattern.minecraft.%{_name}%>" to lore of {_pattern}

    add "" to lore of {_pattern}
    set slot 3 of {-trim gui::%{_player}%} to {_pattern}

    open {-trim gui::%{_player}%} to {_player}

on inventory click:
    if player's current inventory is {-trim gui::%player%}:
        cancel event

        set {_current material} to trim material of armor trim of player's tool
        set {_current pattern} to trim pattern of armor trim of player's tool

        if event-item is a gold ingot:
            set {_index} to 1

            if {_current material} is set:
                loop {-trim::*}:
                    if loop-value is {_current material}:
                        set {_index} to loop-index parsed as number

            if click type is right mouse button:
                set {_next} to {_index} - 1
                if {_next} < 1:
                    set {_next} to size of {-trim::*}
            else:
                set {_next} to {_index} + 1
                if {_next} > size of {-trim::*}:
                    set {_next} to 1

            if {-trim::%{_next}%} is "none":
                delete armor trim of player's tool
            else:
                add armor trim using {-trim::%{_next}%} with ({_current pattern} ? {-trim pattern::2}) to armor trim of player's tool

        else if event-item is a black banner:
            set {_index} to 1

            if {_current pattern} is set:
                loop {-trim pattern::*}:
                    if loop-value is {_current pattern}:
                        set {_index} to loop-index parsed as number

            if click type is right mouse button:
                set {_next} to {_index} - 1
                if {_next} < 1:
                    set {_next} to size of {-trim pattern::*}
            else:
                set {_next} to {_index} + 1
                if {_next} > size of {-trim pattern::*}:
                    set {_next} to 1

            if {-trim pattern::%{_next}%} is "none":
                delete armor trim of player's tool
            else:
                add armor trim using ({_current material} ? {-trim::2}) with {-trim pattern::%{_next}%} to armor trim of player's tool

        openTrimGui(player)
