name: beans
version: '${project.version}'
main: me.mrscopes.beans.Beans
api-version: 1.19
depend:
  - Vault
commands:
  staffchat:
    aliases: sc
    description: beans staff chat between discord and mc
    permission: beans.staffchat
    usage: /sc <message>
  adminchat:
    aliases: ac
    description: beans admin chat between discord and mc
    permission: beans.adminchat
    usage: /ac <message>
  balance:
    aliases: bal
    description: Check a player's money
  pay:
    description: Pay a user money
    usage: /pay <player> <amount>