ultimate pickaxe enchantment:
    id: "genesis"
    display: "&f<sprite:items:item/nether_star> <rainbow><bold>Genesis"
    max level: 5
    priority: 0
    item: nether star
    cost: "cheap"

    > "distance":
        lvl. 1: 8
        lvl. 2: 10
        lvl. 3: 12
        lvl. 4: 14
        lvl. 5: 16

    > "radius":
        lvl. 1: 4
        lvl. 2: 6
        lvl. 3: 8
        lvl. 4: 10
        lvl. 5: 12

    > "cooldown":
        lvl. 1: 3 minutes
        lvl. 2: 2 minutes and 45 seconds
        lvl. 3: 2 minutes and 30 seconds
        lvl. 4: 2 minutes and 15 seconds
        lvl. 5: 2 minutes

local function getDescription(level: integer) :: string:
    set {_distance} to "distance" of "genesis" at {_level}
    set {_radius} to "radius" of "genesis" at {_level}

    return "in each direction&8, &7shoot a beam of light &f%{_distance}%m &7that will break blocks in a &f%{_radius}%m &7radius"

local function onBreak(player: player, level: integer, block: block):
    set {_distance} to "distance" of "genesis" at {_level}
    set {_radius} to "radius" of "genesis" at {_level}
    set {_origin} to location of {_block}
    
    playEnchantmentSound("mining", "minecraft:entity.ender_dragon.growl", 0.5, 1, location of {_player}, all players, {_player})

    set {_safe distance} to ({_distance} + {_radius}) / 2.5

    loop {_distance} times:
        set {_step} to loop-number + {_safe distance}

        set {_north} to {_origin} ~ vector(0, 0, {_step} * -1)
        set {_south} to {_origin} ~ vector(0, 0, {_step})
        set {_east} to {_origin} ~ vector({_step}, 0, 0)
        set {_west} to {_origin} ~ vector({_step} * -1, 0, 0)

        draw 20 white flash particle at {_north}
        draw 20 white flash particle at {_south}
        draw 20 white flash particle at {_east}
        draw 20 white flash particle at {_west}

        fastRadiusClear({_player}, {_north}, {_radius})
        fastRadiusClear({_player}, {_south}, {_radius})
        fastRadiusClear({_player}, {_east}, {_radius})
        fastRadiusClear({_player}, {_west}, {_radius})