using reflection

on load:
    create ultimate pickaxe enchantment named "miracle":
        set enchantment display to "&f<sprite:gui:icon/link> <rainbow><bold>Miracle"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to end crystal (item)

        level values for "cooldown":
            set level 1 to 3 minutes
            set level 2 to 2 minutes and 30 seconds
            set level 3 to 2 minutes
            set level 4 to 1 minute and 30 seconds
            set level 5 to 1 minute

        level values for "dust cost":
            set level 2 to 325
            set level 3 to 900
            set level 4 to 1_950
            set level 5 to 3_900

        level values for "money cost":
            set level 2 to 400_000
            set level 3 to 1_000_000
            set level 4 to 2_000_000
            set level 5 to 4_000_000

local function getDescription(level: integer) :: string:
    return "activate most enchantments, bypassing chance and cooldown"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    playEnchantmentSound("mining", "minecraft:entity.ender_dragon.growl", 0.5, 1, location of {_player}, all players, {_player})
    set {_enchantments::*} to custom enchantments of {_tool}
    set {_indices::*} to indices of {_enchantments::*}
    set {_indices::*} to shuffled {_indices::*}
    remove "miracle", "reroll", "jackpot", "chaos", "beacon finder" from {_indices::*}
    loop {_indices::*}:
        run {-ce::%loop-value%::onBreak} with arguments ({_player}, {_player}'s tool, {_enchantments::%loop-value%}, {_block}, {_block type})