using reflection

ultimate pickaxe enchantment:
    id: "miracle"
    display: "&f<sprite:gui:icon/link> <rainbow><bold>Miracle"
    max level: 5
    priority: 0
    item: end crystal (item)
    cost: "cheap"

    > "cooldown":
        lvl. 1: 3 minutes
        lvl. 2: 2 minutes and 30 seconds
        lvl. 3: 2 minutes
        lvl. 4: 1 minute and 30 seconds
        lvl. 5: 1 minute

local function getDescription(level: integer) :: string:
    return "activate most enchantments&8, &7bypassing chance and cooldown"

local function onBreak(player: player, level: integer, block: block):
    playEnchantmentSound("mining", "minecraft:entity.ender_dragon.growl", 0.5, 1, location of {_player}, all players, {_player})
    set {_enchantments::*} to {-cached enchantments::%{_player}%::pickaxe::*}
    set {_indices::*} to indices of {_enchantments::*}
    set {_indices::*} to shuffled {_indices::*}
    remove "miracle", "reroll", "jackpot", "chaos", "beacon finder", "genesis", "overdrive" from {_indices::*}
    loop {_indices::*}:
        run {-ce::%loop-value%::onBreak} with arguments ({_player}, {_enchantments::%loop-value%}, {_block})