using reflection

on load:
    setting("miracle", "ultimate", value: true)
    setting("miracle", "display", value: "&f<sprite:gui:icon/link> <rainbow><bold>Miracle")
    setting("miracle", "max", value: 5)
    setting("miracle", "priority", value: 0)
    setting("miracle", "type", value: "pickaxe")
    setting("miracle", "item", value: end crystal (item))

    setting("miracle", "cooldown", l1: 3 minutes, l2: 2 minutes and 30 seconds, l3: 2 minutes, l4: 1 minute and 30 seconds, l5: 1 minute)

    setting("miracle", "xp cost", l2: 300_000, l3: 800_000, l4: 1_750_000, l5: 3_500_000)
    setting("miracle", "money cost", l2: 400_000, l3: 1_000_000, l4: 2_000_000, l5: 4_000_000)

local function getDescription(level: integer) :: string:
    return "activate most enchantments, bypassing chance and cooldown"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    play sound "minecraft:entity.ender_dragon.growl" with volume 0.5 and pitch 1 at location of {_player}
    set {_enchantments::*} to custom enchantments of {_tool} # keyed getEnchantments({_tool})
    set {_indices::*} to indices of {_enchantments::*}
    set {_indices::*} to shuffled {_indices::*}
    remove "miracle", "reroll", "jackpot", "chaos", "beacon finder" from {_indices::*}
    loop {_indices::*}:
        run {-ce::%loop-value%::onbreak} with arguments ({_player}, {_player}'s tool, {_enchantments::%loop-value%}, {_block}, {_block type})