using reflection

ultimate pickaxe enchantment:
    id: "overdrive"
    display: "&f<sprite:items:item/recovery_compass_00> <rainbow><bold>Overdrive"
    max level: 3
    priority: 0
    item: recovery compass
    cost: "cheap"

    > "chance":
        lvl. 1: 5%
        lvl. 2: 7.5%
        lvl. 3: 10%

    > "enchantments":
        lvl. 1: 1
        lvl. 2: 2
        lvl. 3: 3

    > "level boost":
        lvl. 1: 1
        lvl. 2: 2
        lvl. 3: 3

local function getDescription(level: integer) :: string:
    set {_enchantments} to "enchantments" of "overdrive" at {_level}
    set {_level boost} to "level boost" of "overdrive" at {_level}
    return "spin &f%{_enchantments}% &7random enchantments on your tool&8, &7but at &f%{_level boost}% &7levels higher"

local function onBreak(player: player, level: integer, block: block):
    set {_enchantments} to "enchantments" of "overdrive" at {_level}
    set {_level boost} to "level boost" of "overdrive" at {_level}

    playEnchantmentSound("mining", "minecraft:entity.wither.spawn", 0.5, 1, location of {_player}, all players, {_player})

    set {_enchantments::*} to indexes of {-cached enchantments::%{_player}%::pickaxe::*}
    set {_viable::*} to viableEnchantments({_enchantments::*})
    loop {_enchantments} times:
        set {_enchantment} to random element out of {_viable::*}
        if {_enchantment} is set:
            set {_level} to {_enchantments::%{_enchantment}%} + {_level boost}
            if enchantCanRun({_player}, {_enchantment}, {_level}) is true:
                startEnchantCooldown({_player}, {_enchantment}, {_level})
                run {-ce::%{_enchantment}%::onBreak} with arguments ({_player}, {_level}, {_block})

local function viableEnchantments(enchantments: strings) :: strings:
    remove "overdrive", "reroll", "lucky", "jackpot" from {_enchantments::*}
    for {_enchantment} in {_enchantments::*}:
        {-ce::%{_enchantment}%::onBreak} is set
        {-ce::%{_enchantment}%::max level} > 1
        add {_enchantment} to {_viable::*}
    return {_viable::*}