command /afk:
    trigger:
        if all:
            player's gamemode isn't creative
            {-vanish::%player%} isn't set
        then:
            set {_seconds} to 3
            set {_starting location} to player's location
            while {_seconds} > 0:
                send "&7Teleporting to AFK in &b%{_seconds}%s&7... Don't move." to player
                wait 1 second
                subtract 1 from {_seconds}

                if distance between player's location and {_starting location} > 2:
                    send "&cCanceled teleportation due to movement."
                    delete {_seconds}
                    stop loop

                if {_seconds} is 0:
                    teleport player to {afk}
        else:
            teleport player to {afk}

on bound exit with id "afk":
    delete {-afk timer::%player%}

async every second:
    loop all players where [bounds at input contains bound with id "afk"]:
        add 1 second to {-afk timer::%loop-player%}
        wait 1 tick
        send action bar "You have been AFK for %time_format({-afk timer::%loop-player%} ? 0 seconds)%" to loop-player

        # every 5 seconds, give basic rewards
        if mod(seconds of {-afk timer::%loop-player%}, 5) is 0:
            add 1 * afkrewards_multi_player(loop-player) to {total level progress::%loop-player%}
            add 1 * afkrewards_multi_player(loop-player) to {level progress::%loop-player%}
            add 1 * afkrewards_multi_player(loop-player) to {money::%loop-player%}
            add 1 * afkrewards_multi_player(loop-player) to {money source::%loop-player%::afk}
            add 1 * afkrewards_multi_player(loop-player) to {xp source::%loop-player%::afk}
            add 1 * afkrewards_multi_player(loop-player) to loop-player's experience

        # every 2 hours, give a beacon. the multi might make it a decimal, so wait until it's whole to count it.
        if mod(seconds of {-afk timer::%loop-player%}, 7200) is 0:
            add 1 * afkrewards_multi_player(loop-player) to {-afk beacons::%loop-player%}

            set {_whole} to floor({-afk beacons::%loop-player%})

            if {_whole} > 0:
                remove {_whole} from {-afk beacons::%loop-player%}
                giveBeacons(loop-player, {_whole})

                send title "&b&lBEACON" with subtitle "You received %{_whole}% beacon(s) for being AFK for 2 hours!" to loop-player
