function customDamage(victim: entity, damage: number, attacker: entity = {_}) :: number:
    set {_strength} to 0
    if {_attacker} is set:
        set {_strength} to (potion level of strength effect of {_attacker}) ? 0
    set {_armor} to (sum(modifier amount of armor attribute modifiers of {_victim}'s helmet)) ? 0
    set {_resistance} to (potion level of {_victim}'s resistance effect) ? 0

    set {_damage} to {_damage} * (1 + ({_strength} * 0.2))
    set {_damage} to {_damage} * (1 - ({_resistance} * 0.2))
    set {_damage} to {_damage} * (1 - ({_armor} * 0.02))
    return {_damage}

function damage(victim: entity, attacker: entity, damage: number, customDamage: boolean = true, calculateWithEffects: boolean = false) :: number:
    set {-last attacker::%{_victim}%} to {_attacker}
    if {_customDamage} is true:
        if {_calculateWithEffects} is false:
            set {_damage} to customDamage({_victim}, {_damage})
        else:
            set {_damage} to customDamage({_victim}, {_damage}, {_attacker})
    reset {_victim}'s no damage time
    damage {_victim} by {_damage}
    reset {_victim}'s no damage time

on damage of player:
    if attacker is a player:
        set {-last attacker::%victim%} to attacker
    else if attacker is a mob:
        set {-last attacker::%victim%} to {-owner::%attacker%}

on death of player:
    set {_attacker} to {-last attacker::%victim%} ? attacker
    add 1 to {deaths::%victim%}
    if {_attacker} isn't set:
        set death message to "%player_display(victim)% &7has died&7."
    else:
        set death message to "%player_display({_attacker})% &7killed %player_display(victim)%&7."
        add 1 to {kills::%{_attacker}%}
        set {_money reward} to {money::%victim%} * 0.02
        add {_money reward} to {money::%{_attacker}%}
        remove {_money reward} from {money::%victim%}
        send "&7You received &a$%kNumber({_money reward})% &7for killing %player_display(victim)%&7." to {_attacker}
        send "&7You lost &c$%kNumber({_money reward})% &7for being killed by %player_display({_attacker})%&7." to victim

command /protection:
    trigger:
        if difference between {-pvp protection confirm::%player%} and now < 10 seconds:
            delete {pvp protection::%player%}
            delete {-pvp protection confirm::%player%}
            send ""
            send " &bPVP protection disabled." to player
            send ""
        else:
            if {pvp protection::%player%} is set:
                send ""
                send " &bYou have PVP protection enabled."
                send " &bTo disable it, Run the command again within 10s to confirm."
                send ""
                set {-pvp protection confirm::%player%} to 10 seconds from now

on damage with priority low:
    event isn't canceled
    attacker is a player
    victim is a player

    if {pvp protection::%attacker%} is set:
        cancel event
        send "&7You can't attack players while you have PVP protection." to attacker
        send "&7Disable with /protection." to attacker

    else if {pvp protection::%victim%} is set:
        cancel event
        send "&7That player has starter PVP protection on." to attacker