using reflection

on load:
    delete {-top command::*}

    set {_kNumber} to function named "kNumber"
    set {_formatNumber} to function named "formatNum"
    set {_timeFormat} to function named "timeFormat"

    set {-top command::money} to "money"
    set {-top command::money::display} to "&a$value"
    set {-top command::money::display function} to {_kNumber}
    set {-top command::money::title} to "Top Money"
    set {-top command::money::leaderboard} to location(79.5, 52, 90.5)

    set {-top command::bounty} to "bounty"
    set {-top command::bounty::display} to "&c$value"
    set {-top command::bounty::display function} to {_kNumber}
    set {-top command::bounty::title} to "Top Bounties"

    set {-top command::blocks} to "blocks"
    set {-top command::blocks::display} to "&bvalue blocks"
    set {-top command::blocks::display function} to {_formatNumber}
    set {-top command::blocks::title} to "Block Top"
    set {-top command::blocks::leaderboard} to location(79.5, 52, 95.5)

    set {-top command::trophies} to "trophies"
    set {-top command::trophies::display} to "&6🏆value"
    set {-top command::trophies::display function} to {_formatNumber}
    set {-top command::trophies::title} to "Top Trophies"

    set {-top command::level} to "level"
    set {-top command::level::display} to "&fvalue"
    set {-top command::level::display function} to function named "levelDisplay"
    set {-top command::level::title} to "Highest Level"

    set {-top command::playtime} to "cached playtime"
    set {-top command::playtime::display} to "&evalue"
    set {-top command::playtime::display function} to {_timeFormat}
    set {-top command::playtime::title} to "Most Playtime"
    
    set {-top command::dust} to "dust"
    set {-top command::dust::display} to "%{-dust sprite}%&fvalue"
    set {-top command::dust::display function} to {_formatNumber}
    set {-top command::dust::title} to "Top Dust"

    set {-top command::kills} to "kills"
    set {-top command::kills::display} to "&fvalue kills"
    set {-top command::kills::display function} to {_formatNumber}
    set {-top command::kills::title} to "Top Kills"

    set {-top command::deaths} to "deaths"
    set {-top command::deaths::display} to "&fvalue deaths"
    set {-top command::deaths::display function} to {_formatNumber}
    set {-top command::deaths::title} to "Top Deaths"

    set {-top command::kdr} to "cached kdr"
    set {-top command::kdr::display} to "&evalue KDR"
    set {-top command::kdr::display function} to function named "kdrDisplay"
    set {-top command::kdr::title} to "Top KDR (more than 20 kills)"

function calculateTops():
    for {_stat} in indexes of {-top command::*}:
        set {_variable} to {-top command::%{_stat}%}
        delete {-sorted::%{_variable}%::*}

        for {_player} in sorted indices of {%{_variable}%::*} in descending order:
            set {-sorted::%{_variable}%::%loop-iteration-2%::player} to {_player}
            set {-sorted::%{_variable}%::%loop-iteration-2%::value} to {%{_variable}%::%{_player}%}
            set {-sorted::%{_variable}%::%{_player}%} to loop-iteration-2

function topEntryDisplay(player: offline player, stat: text) :: text:
    set {_variable} to {-top command::%{_stat}%}

    set {_index} to {-sorted::%{_variable}%::%{_player}%}
    set {_raw value} to {-sorted::%{_variable}%::%{_index}%::value}

    set {_value} to {_raw value}

    if {-top command::%{_stat}%::display function} is set:
        set {_function} to {-top command::%{_stat}%::display function}
        set {_value} to result of {_function} with arguments {_raw value}

    if {-top command::%{_stat}%::display variable} is set:
        set {_display variable} to {-top command::%{_stat}%::display variable}
        set {_display value} to {%{_display variable}%::%{_raw value}%}

        if {_display value} is set:
            set {_value} to {_display value}

    set {_stat display} to {-top command::%{_stat}%::display}
    replace all "value" in {_stat display} with "%{_value}%"

    return "&b#%{_index}% &f<head:%{_player}%> &7%playerDisplay({_player}, "[level] [prefix][player]")%&8: &f%{_stat display}%"

command /top [<text>]:
    trigger:
        async run 0 ticks later:
            set {_variable} to {-top command::%arg 1%}
            if {_variable} is set:
                loop 5 times:
                    set {_player} to offlineplayer({-sorted::%{_variable}%::%loop-value%::player}, false)
                    {_player} is set
                    set {_top::%loop-iteration-2%} to topEntryDisplay({_player}, arg 1)

                if {-sorted::%{_variable}%::%player%} is set:
                    set {_player iteration} to {-sorted::%{_variable}%::%player%}
                    if {_player iteration} > 5:
                        set {_top::%{_player iteration}%} to topEntryDisplay(player, arg 1)
    
                send ""
                send {-top command::%arg 1%::title}
                send ""
                send formatted {_top::*}
                send ""
            else:
                send "&c/top <%join (indexes of {-top command::*}) with " | "%>"

on tab complete of "/top":
    set tab completions for position 1 to indexes of {-top command::*}

function cacheStats():
    loop all players:
        set {cached playtime::%loop-player%} to playtime of loop-player

        if {kills::%loop-player%} > 20:
            set {_deaths} to max(1, {deaths::%loop-player%})
            set {_kdr} to {kills::%loop-player%} / {_deaths}
            set {cached kdr::%loop-player%} to {_kdr}

async every 5 minutes:
    calculateTops()
    leaderboardText()

async every minute:
    cacheStats()

on load:
    buildLeaderboards()

    async run 0 ticks later:
        cacheStats()
        calculateTops()
        leaderboardText()

function buildLeaderboards():
    set {_leaderboard::money} to location(79.5, 52, 90.5)
    set {_leaderboard::blocks} to location(79.5, 52, 95.5)

    for {_leaderboard type} in indexes of {-top command::*}:
        {-top command::%{_leaderboard type}%::leaderboard} is set
        if {-leaderboard::%{_leaderboard type}%} is set:
            delete entity within {-leaderboard::%{_leaderboard type}%}

        spawn text display at {-top command::%{_leaderboard type}%::leaderboard}:
            set {-leaderboard::%{_leaderboard type}%} to display
            make display not persistent     
            set billboard of display to center
            set color of display to rgb(0, 0, 0, 0)
            apply drop shadow to display

function leaderboardText():
    for {_leaderboard} in indexes of {-leaderboard::*}:
        set {_variable} to {-top command::%{_leaderboard}%}
        loop 5 times:
            set {_player} to offlineplayer({-sorted::%{_variable}%::%loop-number%::player}, false)
            {_player} is set
            set {_top::%loop-iteration-2%} to topEntryDisplay({_player}, {_leaderboard})
        
        set text of {-leaderboard::%{_leaderboard}%} to formatted "", {-top command::%{_leaderboard}%::title}, "", {_top::*}, ""

local function formatNum(number: number) :: text:
    return formatNumber({_number})
