on load:
    loop integers between 1 and 100:
        set {-level display::%loop-value%} to levelDisplay(loop-value)
        set {-required xp::%loop-value%} to requiredXp(loop-value)

function requiredXp(level: integer) :: integer:
    if {_level} <= 10:
        return {_level} * 100
    if {_level} <= 25:
        return {_level} * 500
    else if {_level} <= 50:
        return requiredXp(25) + ({_level} - 25) * 5000
    else if {_level} <= 90:
        return requiredXp(50) + ({_level} - 50) * 50000
    else:
        return requiredXp(90) + ({_level} - 90) * 250000
    # return ({_level} * 500) ^ 1.2 #(100 * (1.1 ^ ({_level} - 1) * 50))

function levelDisplay(level: integer) :: text:
    if {_level} < 10:
        return "<shadow:black:1>&7[%{_level}%]</shadow>"
    else if {_level} < 20:
        return "<shadow:black:1>&2[&a%{_level}%&2]</shadow>"
    else if {_level} < 30:
        return "<shadow:black:1>&3[&b%{_level}%&3]</shadow>"
    else if {_level} < 40:
        return "<shadow:black:1><#1E90FF>[&3%{_level}%<#1E90FF>]</shadow>"
    else if {_level} < 50:
        return "<shadow:black:1>&5[&d%{_level}%&5]</shadow>"
    else if {_level} < 60:
        return "<shadow:black:1>&6[&e%{_level}%&6]</shadow>"
    else if {_level} < 70:
        return "<shadow:black:1>&7[&f%{_level}%&7]</shadow>"
    else if {_level} < 80:
        return "<shadow:black:1><#00FF00>[&2%{_level}%<#00FF00>]</shadow>"
    else if {_level} < 90:
        return "<shadow:black:1>&4[&c%{_level}%&4]</shadow>"
    else if {_level} < 100:
        return "<shadow:black:1>&4[&4%{_level}%&4]</shadow>"
    else:
        return "<shadow:black:1>&4&l[%{_level}%]</shadow>"

command /leveldisplays:
    trigger:
        loop 1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100:
            send "%{-level display::%loop-value%}%"