on load:
    set {-mine corner 1} to location(-0.5, -49.5, -0.5, world "world")
    set {-mine corner 2} to location(-99.5, 0, -99.5, world "world")
    delete bound with id "mine"
    create bound with id "mine" within {-mine corner 1} and {-mine corner 2}

    add 4 to y coordinate of {-mine corner 2}
    remove 4 from y coordinate of {-mine corner 1}
    delete bound with id "mine flight"
    create bound with id "mine flight" within {-mine corner 1} and {-mine corner 2}

on load:
    set {-sell::%("cobblestone" parsed as item type)%} to 1
    set {-sell::%("stone" parsed as item type)%} to 1

    set {-sell::%("coal" parsed as item type)%} to 2
    set {-sell::%("coal ore" parsed as item type)%} to 2

    set {-sell::%("raw iron" parsed as item type)%} to 3
    set {-sell::%("iron ore" parsed as item type)%} to 3

    set {-sell::%("diamond" parsed as item type)%} to 5
    set {-sell::%("diamond ore" parsed as item type)%} to 5

    set {-sell::%("emerald" parsed as item type)%} to 10
    set {-sell::%("emerald ore" parsed as item type)%} to 10
    
    set {-sell::%("packed ice" parsed as item type)%} to 30
    set {-sell::%("obsidian" parsed as item type)%} to 250

    set {-dust::%("stone" parsed as item type)%} to 0.0025
    set {-dust::%("coal ore" parsed as item type)%} to 0.004
    set {-dust::%("iron ore" parsed as item type)%} to 0.007
    set {-dust::%("diamond ore" parsed as item type)%} to 0.01
    set {-dust::%("emerald ore" parsed as item type)%} to 0.015
    set {-dust::%("packed ice" parsed as item type)%} to 0.009
    set {-dust::%("obsidian" parsed as item type)%} to 0.05
    set {-dust::%("beacon" parsed as item type)%} to 10.0

on break with priority highest:
    event isn't canceled
    cancel drops
    blockReward(player, player's tool, block, "mining")

function blockReward(player: player, tool: item, block: block, reason: text):
    if type of {_block} isn't air:
        add 1 to {blocks::%{_player}%}

    add 1 to {level progress::%{_player}%}
    add 1 to {total level progress::%{_player}%}

    set {_fortune} to level of fortune of {_tool}
    set {_dust} to {-dust::%type of {_block}%} * (1 + ({_fortune} * 0.025))
    add {_dust} to {dust::%{_player}%}

    set {_drops::*} to drops of {_block} using {_tool}
    if type of {_block} is packed ice:
        add ((level of fortune on {_tool} + 1) of packed ice) to {_drops::*}

    loop {_drops::*}:
        set {_money} to ({-sell::%type of loop-value%} * item amount of loop-value)
        add {_money} to {money::%{_player}%}

    if {_block} is a beacon:
        broadcast "%{_player}% found a beacon!"
        giveBeacons({_player}, 2)
        async run 0 ticks later:
            loop all blocks within bound (bound with id "mine"):
                if loop-block is a beacon:
                    add 1 to {_beacons}
            broadcast "There are currently %{_beacons}% beacons in the mine."
            if {_beacons} isn't set:
                broadcast "The mine is out of beacons! Resetting..."
                wait 1 tick
                execute console command "mine"