on load:
    set {-vault amount::patron} to 10
    set {-daily beacons::patron} to 13
    set {-daily wheel spins::patron} to 6
    set {-onetime beacons::patron} to 20
    set {-afk rewards multi::patron} to 2

    set {-vault amount::gamer} to 8
    set {-daily beacons::gamer} to 9
    set {-daily wheel spins::gamer} to 5
    set {-onetime beacons::gamer} to 10
    set {-afk rewards multi::gamer} to 1.75

    set {-vault amount::legend} to 6
    set {-daily beacons::legend} to 7
    set {-daily wheel spins::legend} to 4
    set {-onetime beacons::legend} to 7
    set {-afk rewards multi::legend} to 1.5

    set {-vault amount::premium} to 4
    set {-daily beacons::premium} to 6
    set {-daily wheel spins::premium} to 4
    set {-onetime beacons::premium} to 5
    set {-afk rewards multi::premium} to 1.25
    
    set {-vault amount::vip} to 2
    set {-daily beacons::vip} to 5
    set {-daily wheel spins::vip} to 3
    set {-onetime beacons::vip} to 4
    set {-afk rewards multi::vip} to 1.15

    set {-vault amount::default} to 1
    set {-daily beacons::default} to 3
    set {-daily wheel spins::default} to 2

command /prefixes:
    trigger:
        loop "admin", "sr-mod", "mod", "patron", "gamer", "legend", "premium", "vip", "default":
            send formatted "%group prefix of loop-value%%player%&8: <%group chat color of loop-value%>%player%" to player

function updatePlayerTabName(player: player):
    set tablist name of {_player} to player_display({_player}, "[level] [prefix][player] [trophies]")

on join:
   updatePlayerTabName(player)

async every second:
    loop all players:
        updatePlayerTabName(loop-player)

        set {_group weight} to group weight of loop-player's group * 1_000_000
        set {_level weight} to ({level::%loop-player%} ? 0) * 250
        set {_trophy weight} to ({trophies::%loop-player's uuid%} ? 0) * 1
        set {_order} to {_group weight} + {_level weight} + {_trophy weight}
        
        loop-player.setPlayerListOrder({_order})

function daily_beacons_player(player: player) :: integer:
    if {_player} has permission "group.patron":
        return {-daily beacons::patron}

    if {_player} has permission "group.gamer":
        return {-daily beacons::gamer}

    if {_player} has permission "group.legend":
        return {-daily beacons::legend}

    if {_player} has permission "group.premium":
        return {-daily beacons::premium}
    
    if {_player} has permission "group.vip":
        return {-daily beacons::vip}
    
    return {-daily beacons::default}

function daily_wheel_spins_player(player: player) :: integer:
    if {_player} has permission "group.patron":
        return {-daily wheel spins::patron}

    if {_player} has permission "group.gamer":
        return {-daily wheel spins::gamer}

    if {_player} has permission "group.legend":
        return {-daily wheel spins::legend}

    if {_player} has permission "group.premium":
        return {-daily wheel spins::premium}
    
    if {_player} has permission "group.vip":
        return {-daily wheel spins::vip}
    
    return {-daily wheel spins::default}

function afkrewards_multi_player(player: player) :: number:
    if {_player} has permission "group.patron":
        return {-afk rewards multi::patron}

    if {_player} has permission "group.gamer":
        return {-afk rewards multi::gamer}

    if {_player} has permission "group.legend":
        return {-afk rewards multi::legend}

    if {_player} has permission "group.premium":
        return {-afk rewards multi::premium}
    
    if {_player} has permission "group.vip":
        return {-afk rewards multi::vip}
    
    return 1

function vault_amount_player(player: offline player) :: number:
    if {_player} has permission "group.default":
        set {_amount} to {-vault amount::default}

    if {_player} has permission "group.vip":
        set {_amount} to {-vault amount::vip}

    if {_player} has permission "group.premium":
        set {_amount} to {-vault amount::premium}

    if {_player} has permission "group.legend":
        set {_amount} to {-vault amount::legend}

    if {_player} has permission "group.gamer":
        set {_amount} to {-vault amount::gamer}

    if {_player} has permission "group.patron":
        set {_amount} to {-vault amount::patron}

    return {_amount} + {unlocked vaults::%{_player}%}

command /purchase <offline player> <text> <text>:
    permission: beans.admin
    trigger:
        if arg 2 is "rank":
            set {_rank} to arg 3
            if {_rank} isn't "patron", "gamer", "legend", "premium", or "vip":
                send "UNKNOWN RANK: %{_rank}%" to console
                send "You purchased a rank but it's unknown. report this asap. '%{_rank}%'" to arg 1
            else:
                add arg 3 to groups of arg 1
                set {_prefix::*} to split (group prefix of "%{_rank}%") at " "
                delete {_prefix::%size of {_prefix::*}%}
                set {_prefix} to join {_prefix::*} with " "
                broadcast "", formatted " &7%player_display(arg 1)% &7has purchased %{_prefix}%&8!", " &7Access the beans store with /buy&8.", ""
                send "&bThank you for your purchase!" to arg 1
                set {_onetime} to {-onetime beacons::%{_rank}%}
                add {_onetime} to {beacons::%arg 1's uuid%}
                send "&7You have received &b%{_onetime}% &lBEACONS&7!" to arg 1
                send "&7You can access your beacons with &b/beacons&7." to arg 1
        else if arg 2 is "beacons":
            set {_beacons} to arg 3 parsed as integer
            if {_beacons} isn't set:
                send "unknown integer: %arg 3%" to console
                send "You purchased beacons but the amount is unknown. report this asap. '%arg 3%'" to arg 1
            else:
                broadcast "", formatted " &7%player_display(arg 1)% &7has purchased &b%arg 3% &lBEACONS&7!", " &7Access the beans store with /buy&8.", ""
                add {_beacons} to {beacons::%arg 1's uuid%}
                send "&bThank you for your purchase!" to arg 1
                send "&7You can access your beacons with &b/beacons&7." to arg 1
        else if arg 2 is "spins":
            set {_spins} to arg 3 parsed as integer
            if {_spins} isn't set:
                send "unknown integer: %arg 3%" to console
                send "You purchased spins but the amount is unknown. report this asap. '%arg 3%'" to arg 1
            else:
                broadcast "", formatted " &7%player_display(arg 1)% &7has purchased &a%{_spins}% &lSPINS&7!", " &7Access the beans store with /buy&8.", ""
                add {_spins} to {spins::%arg 1's uuid%}
                send "&bThank you for your purchase!" to arg 1
                send "&7You can access your spins with &b/spins&7." to arg 1

command /buy [<text>]:
    trigger:
        if arg 1 isn't set:
            set {-buy gui::%player%} to hopper inventory named "All purchases are appreciated!"

            set slot 1 of {-buy gui::%player%} to name tag named "&bRanks" with lore "&7Click to purchase ranks."
            set slot 3 of {-buy gui::%player%} to beacon named "&b&lBEACONS" with lore "&7Click to purchase beacons."
            open {-buy gui::%player%} to player

        else if arg 1 is "ranks":
            set {-ranks gui::%player%} to hopper inventory named "All purchases are appreciated!"
            set slot 0 of {-ranks gui::%player%} to coal named group prefix of "vip" with lore "&7Cost: &b$4.99", "&7Includes:", "&7- &b%{-onetime beacons::vip}% &lBEACONS&7 (one-time)", "&7- &a%{-daily wheel spins::vip}% &lSPINS&7 (/daily)", "&7- &fWhite &7chat. ", "&7- No anti-spam.", "&7- &a%{-vault amount::vip}% &7total vaults.", "&7- AFK rewards boosted by &d%{-afk rewards multi::vip}%x&7." 
            set slot 1 of {-ranks gui::%player%} to iron ingot named group prefix of "premium" with lore "&7Cost: &b$11.99", "&7Includes:", "&7- &b%{-onetime beacons::premium}% &lBEACONS&7 (one-time)", "&7- &a%{-daily wheel spins::premium}% &lSPINS&7 (/daily)", "&7- &fWhite &7chat. ", "&7- No anti-spam.", "&7- &a%{-vault amount::premium}% &7total vaults.", "&7- AFK rewards boosted by &d%{-afk rewards multi::premium}%x&7."
            set slot 2 of {-ranks gui::%player%} to diamond named group prefix of "legend" with lore "&7Cost: &b$24.99", "&7Includes:", "&7- &b%{-onetime beacons::legend}% &lBEACONS&7 (one-time)", "&7- &a%{-daily wheel spins::legend}% &lSPINS&7 (/daily)", "&7- &fWhite &7chat. ", "&7- No anti-spam.", "&7- &a%{-vault amount::legend}% &7total vaults.", "&7- AFK rewards boosted by &d%{-afk rewards multi::legend}%x&7."
            set slot 3 of {-ranks gui::%player%} to emerald named group prefix of "gamer" with lore "&7Cost: &b$39.99", "&7Includes:", "&7- &b%{-onetime beacons::gamer}% &lBEACONS&7 (one-time)", "&7- &a%{-daily wheel spins::gamer}% &lSPINS&7 (/daily)", "&7- &fWhite &7chat. ", "&7- No anti-spam.", "&7- &a%{-vault amount::gamer}% &7total vaults.", "&7- AFK rewards boosted by &d%{-afk rewards multi::gamer}%x&7."
            set slot 4 of {-ranks gui::%player%} to bedrock named group prefix of "patron" with lore "&7Cost: &b$59.99", "&7Includes:", "&7- &b%{-onetime beacons::patron}% &lBEACONS&7 (one-time)", "&7- &a%{-daily wheel spins::patron}% &lSPINS&7 (/daily)", "&7- &fWhite &7chat. ", "&7- No anti-spam.", "&7- &a%{-vault amount::patron}% &7total vaults.", "&7- AFK rewards boosted by &d%{-afk rewards multi::patron}%x&7."
            open {-ranks gui::%player%} to player

        else if arg 1 is "beacons":
            set {-beacons gui::%player%} to hopper inventory named "All purchases are appreciated!"
            set {_price::3} to 2.99
            set {_price::10} to 9.99
            set {_price::30} to 19.99
            set {_price::60} to 34.99
            set {_price::100} to 49.99

            loop indexes of {_price::*}:
                set slot (loop-iteration - 1) of {-beacons gui::%player%} to beacon named "&b%loop-value% &lBEACONS" with lore "&7Cost: &b$%{_price::%loop-value%}%"
            
            open {-beacons gui::%player%} to player

on inventory click:
    if player's current inventory is {-buy gui::%player%}:
        cancel event
        if index of event-slot is 1:
            player command "/buy ranks"
        else if index of event-slot is 3:
            player command "/buy beacons"

    else if player's current inventory is {-ranks gui::%player%}:
        cancel event
        if index of event-slot is 0:
            set {_package} to 1551680
        else if index of event-slot is 1:
            set {_package} to 1551683
        else if index of event-slot is 2:
            set {_package} to 1551686
        else if index of event-slot is 3:
            set {_package} to 1551689
        else if index of event-slot is 4:
            set {_package} to 1551692

    else if player's current inventory is {-beacons gui::%player%}:
        cancel event
        if index of event-slot is 0:
            set {_package} to 1551695
        else if index of event-slot is 1:
            set {_package} to 1551698
        else if index of event-slot is 2:
            set {_package} to 1551704
        else if index of event-slot is 3:
            set {_package} to 1551707
        else if index of event-slot is 4:
            set {_package} to 1551710
        
    if {_package} is set:
        set {-don't open buy gui again when closing ranks or beacons gui::%player%} to now
        send formatted "<click:open_url:'https://beans2026.craftingstore.net/package/%{_package}%'>&bClick here to complete your purchase!"
        close player's inventory

on inventory close:
    event-inventory is {-ranks gui::%player%} or {-beacons gui::%player%}
    difference between {-don't open buy gui again when closing ranks or beacons gui::%player%} and now isn't less than 1 second
    wait 1 tick
    player command "/buy"