import:
    me.lucko.spark.api.SparkProvider
    me.lucko.spark.api.statistic.StatisticWindow
    org.bukkit.Bukkit
    
on load:
    set {-spark} to SparkProvider.get()

async every tick:
    set {_mspt} to Bukkit.getAverageTickTime() #Bukkit.getTickTimes()[0] / 1_000_000

    #if {_mspt} > 50:
    #set {_tps} to 1000 / {_mspt}
    #else:
    set {_tps} to {-spark}.tps().poll(StatisticWindow.TicksPerSecond.SECONDS_10)
    if {_tps} > 19.9:
        set {_tps} to "<green>*20.0"
    else if {_tps} > 19.5:
        set {_tps} to "<green>%{_tps}%"
    else if {_tps} > 18.0:
        set {_tps} to "<yellow>%{_tps}%"
    else:
        set {_tps} to "<red>%{_tps}%"

    if {_mspt} < 35:
        set {_mspt} to "<green>%{_mspt}%ms"
    else if {_mspt} < 45:
        set {_mspt} to "<yellow>%{_mspt}%ms"
    else if {_mspt} < 50:
        set {_mspt} to "<gold>%{_mspt}%ms"
    else:
        set {_mspt} to "<red>%{_mspt}%ms"
            
    loop all players:
        set loop-player's tablist header to "", "     &b&lWelcome to &lBEANS&b!     ", "     &fThere are %size of players% players online.     ", ""
        set loop-player's tablist footer to "", "&f/help", "&f/discord", "&f/buy", "", "&bServer TPS: &f%{_tps}%", "&bServer MSPT: &f%{_mspt}%", "&bYour Ping: &f%loop-player's ping%ms", "&7&obeans.minehut.gg", ""

        if {level::%loop-player%} < 100:
            set {_required xp} to {-required xp::%{level::%loop-player%} + 1%}

            while {level progress::%loop-player%} >= {_required xp}:
                remove {_required xp} from {level progress::%loop-player%}
                add 1 to {level::%loop-player%}

                if {level::%loop-player%} >= 100:
                    stop loop

                set {_required xp} to {-required xp::%{level::%loop-player%} + 1%}

            if {level::%loop-player%} >= 100:
                set {-level progress percent::%loop-player%} to 100
                set loop-player's level to 100
                set loop-player's level progress to 0.99
            else:
                set {_required xp} to {-required xp::%{level::%loop-player%} + 1%}
                set {_progress} to clamp(({level progress::%loop-player%} ? 0) / {_required xp}, 0, 1)

                set {-level progress percent::%loop-player%} to {_progress} * 100
                set loop-player's level to {level::%loop-player%}
                set loop-player's level progress to {_progress}
        else:
            set {-level progress percent::%loop-player%} to 100
            set loop-player's level to 100
            set loop-player's level progress to 0.99

        set line 4 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ &bBlocks&8: &f%kNumber({blocks::%loop-player%})% "
        set line 5 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ &bMoney&8: &f$%kNumber({money::%loop-player%})% "
        set line 6 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ &bDust&8: &f%{-dust sprite}%%formatNumber(floor({dust::%loop-player%} ? 0))% "
        set line 8 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ &bK/D&8: &f%kNumber({kills::%loop-player%})%&8/&f%kNumber({deaths::%loop-player%})% &8(&f%kdrDisplay({kills::%loop-player%} / max(1, {deaths::%loop-player%}))%&8) "

        set {_clamped} to clamp({level::%loop-player%} ? 1, 1, 100)
        if {_clamped} is 100:
            set line 10 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ &bLevel&8: &f%{-level display::%{_clamped}%}% "
            delete line 11 of loop-player's fastboard
        else:
            set line 10 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ %{-level display::%{_clamped}%}% &8➔ %{-level display::%{_clamped} + 1%}% "
            set line 11 of loop-player's fastboard to formatted "<shadow:black:1> &8▪ &f%{-level progress percent::%loop-player%}%%%&r "

on join:
    async run 0.1 seconds later:
        set player's tablist header to "", "", "     &b&lWelcome to &lBEANS&b!     ", "     &fThere are %size of players% players online.     ", "", ""
        set player's tablist footer to "", "", "&f/help", "&f/discord", "&f/buy", "", "&bServer TPS: &f%{-tps}%", "&bYour Ping: &f%player's ping%ms", "&7&obeans.minehut.gg", ""
        set title of player's fastboard to formatted "&0      <shadow:black:1>&b&lbeans     &0"
        # we need a character instead of an empty space, to avoid flickering if the blocks or money entry number becomes long
        set line 3 of player's fastboard to ("&0 " repeated 24 times)
        set line 9 of player's fastboard to ("&0 " repeated 24 times)
        set line 12 of player's fastboard to ""
