function simpleToggleSetting(player: player, item: item type, setting: text, title: text, description: text):
    set {_index} to index of first empty slot of {-settings gui::%{_player}%}

    set {_item} to {_item} named "&f%{_title}%"
    
    if {setting::%{_player}%::%{_setting}%} isn't set:
        force {_item} to glint
        set lore of {_item} to "&7Click to &cdisable &7%{_description}%."
    else:
        force {_item} to stop glinting
        set lore of {_item} to "&7Click to &aenable &7%{_description}%."

    set {-settings gui::%{_player}%::%{_index}%::type} to "toggle"
    set {-settings gui::%{_player}%::%{_index}%::setting} to {_setting}

    set slot {_index} of {-settings gui::%{_player}%} to {_item}

command /settings:
    trigger:
        set {-settings gui::%player%} to chest inventory with 1 rows named "Settings"

        simpleToggleSetting(player, note block, "mining enchantment sounds", "Mining Enchantment Sounds", "mining enchantment sounds")

        open {-settings gui::%player%} to player

on inventory click:
    player's current inventory is {-settings gui::%player%}
    cancel event
    event-inventory is {-settings gui::%player%}
    set {_type} to {-settings gui::%player%::%index of event-slot%::type}
    set {_setting} to {-settings gui::%player%::%index of event-slot%::setting}
    {_type} is set
    {_setting} is set
    if {_type} is "toggle":
        if {setting::%player%::%{_setting}%} isn't set:
            set {setting::%player%::%{_setting}%} to true
        else:
            delete {setting::%player%::%{_setting}%}
    player command "/settings"