function simpleToggleSetting(player: player, item: item type, setting: text, title: text, description: text, enabledByDefault: boolean):
    set {_index} to index of first empty slot of {-settings gui::%{_player}%}

    set {_item} to {_item} named "&f%{_title}%" with all item flags

    set {_enabled} to {setting::%{_player}%::%{_setting}%} ? {_enabledByDefault}

    if {_enabled} is true:
        force {_item} to glint
        set lore of {_item} to "&7Click to &cdisable &7%{_description}%."
    else:
        force {_item} to stop glinting
        set lore of {_item} to "&7Click to &aenable &7%{_description}%."

    set {-settings gui::%{_player}%::%{_index}%::type} to "toggle"
    set {-settings gui::%{_player}%::%{_index}%::setting} to {_setting}
    set {-settings gui::%{_player}%::%{_index}%::default} to {_enabledByDefault}

    set slot {_index} of {-settings gui::%{_player}%} to {_item}

command /settings:
    trigger:
        set {-settings gui::%player%} to chest inventory with 1 rows named "Settings"

        simpleToggleSetting(player, note block, "mining enchantment sounds", "Mining Enchantment Sounds", "mining enchantment sounds", true)
        simpleToggleSetting(player, diamond sword, "combat enchantment sounds", "Combat Enchantment Sounds", "combat enchantment sounds", true)
        simpleToggleSetting(player, compass, "chat pinging", "Chat Pinging", "players pinging you in chat", true)
        simpleToggleSetting(player, music disc far, "instant wheel", "Instant Wheel Spin", "instant wheel spin", false)

        open {-settings gui::%player%} to player

on inventory click:
    player's current inventory is {-settings gui::%player%}
    cancel event
    event-inventory is {-settings gui::%player%}
    set {_type} to {-settings gui::%player%::%index of event-slot%::type}
    set {_setting} to {-settings gui::%player%::%index of event-slot%::setting}
    set {_default} to {-settings gui::%player%::%index of event-slot%::default}
    {_type} is set
    {_setting} is set
    if {_type} is "toggle":
        set {_current} to {setting::%player%::%{_setting}%} ? {_default}
        if {_current} is true:
            set {setting::%player%::%{_setting}%} to false
        else:
            set {setting::%player%::%{_setting}%} to true

    player command "/settings"