on load:
    set {-shop} to chest inventory with 3 rows named "&8Shop"

    add shopItem(16 cooked beef, "Steak", 250) to {-shop}
    add shopItem(16 golden carrot, "Golden Carrot", 40000) to {-shop}
    add shopItem(16 arrow, "Arrow", 500) to {-shop}

    add shopItem(4 white concrete, "White Concrete", 100) to {-shop}
    add shopItem(4 orange concrete, "Orange Concrete", 100) to {-shop}
    add shopItem(4 magenta concrete, "Magenta Concrete", 100) to {-shop}
    add shopItem(4 light blue concrete, "Light Blue Concrete", 100) to {-shop}
    add shopItem(4 yellow concrete, "Yellow Concrete", 100) to {-shop}
    add shopItem(4 lime concrete, "Lime Concrete", 100) to {-shop}
    add shopItem(4 pink concrete, "Pink Concrete", 100) to {-shop}
    add shopItem(4 light gray concrete, "Light Gray Concrete", 100) to {-shop}
    add shopItem(4 cyan concrete, "Cyan Concrete", 100) to {-shop}
    add shopItem(4 purple concrete, "Purple Concrete", 100) to {-shop}
    add shopItem(4 blue concrete, "Blue Concrete", 100) to {-shop}
    add shopItem(4 brown concrete, "Brown Concrete", 100) to {-shop}
    add shopItem(4 green concrete, "Green Concrete", 100) to {-shop}
    add shopItem(4 red concrete, "Red Concrete", 100) to {-shop}

function shopItem(item: item type, display: text, price: integer) :: item:
    set {_amount} to item amount of {_item}
    set {_item} to {_item} named "&7%item amount of {_item}%x %{_display}%"
    add "&7Left &a%{_amount}%x &7for &a$%kNumber({_price})%" to lore of {_item}
    if {_price} > 0:
        add "&7Right &a%{_amount} * 4%x &7for &a$%kNumber({_price} * 4)%" to lore of {_item}
        add "&7Drop &a%{_amount} * 16%x &7for &a$%kNumber({_price} * 16)%" to lore of {_item}
        #add "&7Ctrl + Q to purchase &a%{_amount} * 16%x &7for &a$%kNumber({_price} * 16)%" to lore of {_item}
    set {-shop::%type of {_item}%} to {_price}
    set {_item} to {_item} with all item flags
    return {_item}

command /shop:
    trigger:
        open {-shop} to player

on inventory click:
    player's current inventory is {-shop}
    cancel event

    set {_price} to {-shop::%type of event-item%}

    set {_amount} to item amount of event-item
    if {_price} > 0:
        if click type is right mouse button:
            set {_price} to {_price} * 4
            set {_amount} to {_amount} * 4
        else if click type is q:
            set {_price} to {_price} * 16
            set {_amount} to {_amount} * 16
        ###
        else if click type is ctrl+q:
            set {_price} to {_price} * 16
            set {_amount} to {_amount} * 16
        else if click type is swap offhand:
            set {_price} to {_price} * 64
            set {_amount} to {_amount} * 64
        ###
    if {_price} is set:
        if {money::%player%} >= {_price}:
            remove {_price} from {money::%player%}
            give {_amount} of type of event-item to player

on right click with xp bottle:
    data tag "stored_levels" of (player's tool) isn't set
    player is sneaking
    cancel event
    loop item amount of player's tool times:
        set {_rng} to random number between 3 and 11
        add {_rng} to player's experience
        remove 1 from item amount of player's tool