command /tpa <target: player>:
    trigger:
        if {_target} is player:
            send "&cYou cannot send a tpa request to yourself."
            stop

        set {_setting} to setting "tpa requests" for {_target}
        if {_setting} isn't "All":
            if {_setting} is "None":
                send "&cThat player has tpa requests disabled!"
                stop
            else if {_setting} is "Clan Only":
                if {clan::%player%} isn't {clan::%{_target}%}:
                    send "&cThat player only accepts tpa requests from clan members!"
                    stop

        if {-tpa requests::%{_target}%::*} contains player:
            send "&cYou already have a teleport request to %{_target}%."
            stop

        set {-tpa requests::%{_target}%::%player%} to "tpa"
        set {-latest tpa request::%{_target}%} to player

        send "&aTpa request sent to %{_target}%."
        send "&eYou can cancel this request with /tpacancel."
        send "&e%player% has requested to teleport to you." to {_target}
        send formatted "<click:run_command:'/tpaccept %player%'>&a&l[ACCEPT] <click:run_command:'/tpdeny %player%'>&c&l[DENY]" to {_target}

command /tpahere <target: player>:
    trigger:
        if {_target} is player:
            send "&cYou cannot send a tpahere request to yourself."
            stop

        set {_setting} to setting "tpa requests" for {_target}
        if {_setting} isn't "All":
            if {_setting} is "None":
                send "&cThat player has tpa requests disabled!"
                stop
            else if {_setting} is "Clan Only":
                if {clan::%player%} isn't {clan::%{_target}%}:
                    send "&cThat player only accepts tpa requests from clan members!"
                    stop

        if {-tpa requests::%{_target}%::*} contains player:
            send "&cYou already have a teleport request to %{_target}%."
            stop

        set {-tpa requests::%{_target}%::%player%} to "tpahere"
        set {-latest tpa request::%{_target}%} to player

        send "&aTpahere request sent to %{_target}%."
        send "&eYou can cancel this request with /tpacancel."
        send "&e%player% has requested that you teleport to them." to {_target}
        send formatted "<click:run_command:'/tpaccept %player%'>&a&l[ACCEPT] <click:run_command:'/tpdeny %player%'>&c&l[DENY]" to {_target}

command /tpaccept [<target: player>]:
    trigger:
        set {_target} to {_target} ? {-latest tpa request::%player%}

        if {_target} is not set:
            send "&cYou don't have a teleport request."
            stop

        set {_type} to {-tpa requests::%player%::%{_target}%}

        if {_type} is not set:
            send "&cYou don't have a teleport request from %{_target}%."
            stop

        delete {-tpa requests::%player%::%{_target}%}
        delete {-latest tpa request::%player%}

        send "&aTeleport request from %{_target}% accepted."
        send "&a%player% has accepted your teleport request." to {_target}

        wait 10 ticks

        if {_type} is "tpa":
            timedTP({_target}, player)
        else if {_type} is "tpahere":
            timedTP(player, {_target})

command /tpdeny [<target: player>]:
    trigger:
        set {_target} to {_target} ? {-latest tpa request::%player%}

        if {_target} is not set:
            send "&cYou don't have a teleport request."
            stop

        if {-tpa requests::%player%::%{_target}%} isn't set:
            send "&cYou don't have a teleport request from %{_target}%."
            stop

        delete {-tpa requests::%player%::%{_target}%}
        delete {-latest tpa request::%player%}

        send "&cTeleport request from %{_target}% denied."
        send "&c%player% has denied your teleport request." to {_target}

on tab complete of "/tpaccept" or "/tpdeny":
    set tab completions for position 1 to {-tpa requests::%player%::*}