ultimate bow enchantment:
    id: "domain"
    display: "&f<sprite:items:item/barrier> <rainbow><bold>Domain"
    max level: 5
    priority: 10
    item: barrier
    cost: "normal"

    > "cooldown":
        lvl. 1: 1 minute
        lvl. 2: 1 minute
        lvl. 3: 1 minute
        lvl. 4: 1 minute
        lvl. 5: 1 minute

    > "radius":
        lvl. 1: 20
        lvl. 2: 18
        lvl. 3: 16
        lvl. 4: 14
        lvl. 5: 12

    > "duration":
        lvl. 1: 10 seconds
        lvl. 2: 11 seconds
        lvl. 3: 12 seconds
        lvl. 4: 13 seconds
        lvl. 5: 15 seconds

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of "domain" at {_level}
    set {_radius} to "radius" of "domain" at {_level}
    return "on hit&8, &7create an inescapable &f%{_radius}%m &7domain for &f%timeFormat({_duration})%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a player:
        set {_duration} to "duration" of "domain" at {_level}
        set {_radius} to "radius" of "domain" at {_level}
        playEnchantmentSound("combat", "entity.enderman.death", 1, 1, location of {_victim}, all players)
        send "%{_victim}% was trapped in a domain!" to {_shooter}
        set worldborder of {_victim} to a virtual worldborder:
            set worldborder radius of event-worldborder to {_radius}
            set worldborder center of event-worldborder to location of {_victim}
            set worldborder damage amount of event-worldborder to 5
        set {_border} to worldborder of {_victim}
        wait {_duration}
        {_border} is worldborder of {_victim}
        reset worldborder of {_victim}
        