on load:
    create ultimate bow enchantment named "domain":
        set enchantment display to "&f<sprite:items:item/barrier> <rainbow><bold>Domain"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to barrier

        level values for "cooldown":
            set level 1 to 1 minute
            set level 2 to 1 minute
            set level 3 to 1 minute
            set level 4 to 1 minute
            set level 5 to 1 minute

        level values for "radius":
            set level 1 to 20
            set level 2 to 18
            set level 3 to 16
            set level 4 to 14
            set level 5 to 12

        level values for "duration":
            set level 1 to 10 seconds
            set level 2 to 11 seconds
            set level 3 to 12 seconds
            set level 4 to 13 seconds
            set level 5 to 15 seconds

        level values for "xp cost":
            set level 2 to 200_000
            set level 3 to 1_000_000
            set level 4 to 2_000_000
            set level 5 to 5_000_000

        level values for "money cost":
            set level 2 to 250_000
            set level 3 to 1_250_000
            set level 4 to 2_500_000
            set level 5 to 5_550_000

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of {_level} for "domain"
    set {_radius} to "radius" of {_level} for "domain"
    return "on hit&8, &7create an inescapable &f%{_radius}%m &7domain for &f%time_format({_duration})%"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a player:
        set {_duration} to "duration" of {_level} for "domain"
        set {_radius} to "radius" of {_level} for "domain"
        play sound "entity.enderman.death" with volume 1 and pitch 1 at {_victim}
        send "%{_victim}% was trapped in a domain!" to {_shooter}
        set worldborder of {_victim} to a virtual worldborder:
            set worldborder radius of event-worldborder to {_radius}
            set worldborder center of event-worldborder to location of {_victim}
            set worldborder damage amount of event-worldborder to 5
        set {_border} to worldborder of {_victim}
        wait {_duration}
        {_border} is worldborder of {_victim}
        reset worldborder of {_victim}
