condition create [disabled:disabled] [ultimate:ultimate] (pickaxe:pickaxe|sword:sword|armor:armor|bow:bow) enchantment named %string%:
    parse:
        set {_type} to first element out of parse tags where [input isn't "ultimate" or "disabled"]
        continue
    check:
        delete {-ce::%expr-1%::*}
        set {-current ce::%event%::name} to expr-1
        set {-current ce::%event%::type} to {_type}
        set {-ce::%expr-1%::type} to {_type}
        if parse tags contains "ultimate":
            set {-ce::%expr-1%::ultimate} to true
        if parse tags contains "disabled":
            set {-ce::%expr-1%::disabled} to true
        return true

condition level values for %string%:
    check:
        set {-current ce::%event%::level value key} to expr-1
        return true

expression enchantment (display:display|max level:max level|priority:priority|item:item|disabled:disabled|ultimate:ultimate) [of %-string%]:
    parse:
        set {_key} to first element out of parse tags
        continue
    get:
        set {_current enchantment} to expr-1 ? {-current ce::%event%::name}
        return {-ce::%{_current enchantment}%::%{_key}%}
    set:
        set {_current enchantment} to expr-1 ? {-current ce::%event%::name}
        set {-ce::%{_current enchantment}%::%{_key}%} to change value

expression level %integer% [%-string% of %-string%]:
    get:
        set {_current enchantment} to {-current ce::%event%::name}
        set {_current level value key} to {-current ce::%event%::level value key}
        return {-ce::%{_current enchantment}%::%{_current level value key}%::%expr-1%}
    set:
        set {_current enchantment} to {-current ce::%event%::name}
        set {_current level value key} to {-current ce::%event%::level value key}
        set {-ce::%{_current enchantment}%::%{_current level value key}%::%expr-1%} to change value

expression %string% of %integer% for %string%:
    get:
        set {_key} to expr-1
        set {_enchantment} to expr-3
        set {_level} to expr-2

        set {_value} to {-ce::%{_enchantment}%::%{_key}%::%{_level}%}
        if {_value} isn't set:
            set {_max} to enchantment max level of {_enchantment}
            if {_max} is set:
                set {_maxValue} to {-ce::%{_enchantment}%::%{_key}%::%{_max}%}
                set {_previousValue} to {-ce::%{_enchantment}%::%{_key}%::%{_max} - 1%}

                set {_value} to {_maxValue}

                if {_level} > {_max}:
                    if {_maxValue} and {_previousValue} are set:
                        if {_maxValue} > {_previousValue}:
                            set {_difference} to {_maxValue} - {_previousValue}
                            set {_value} to {_maxValue} + ({_level} - {_max}) * {_difference}
                        else:
                            set {_ratio} to {_previousValue} / {_maxValue}
                            set {_value} to {_maxValue} / ({_ratio} ^ ({_level} - {_max}))
        return {_value}