using reflection

function enchantCanRun(player: player, enchantment: string, level: integer, luck: number = 0) :: boolean:
    if {-ce::%{_enchantment}%::disabled} is true:
        if {_player} isn't op:
            return false

    if "manual chance" of {_level} for {_enchantment} isn't set:
        set {_chance} to "chance" of {_level} for {_enchantment}
        {_chance} is set
        set {_chance} to {_chance} * (1 + {_luck})
        chance of (100 - {_chance})%:
            return false

    if "manual cooldown" of {_level} for {_enchantment} isn't set:
        set {_cooldown} to "cooldown" of {_level} for {_enchantment}
        {_cooldown} is set
        if difference between now and {-enchant cooldown::%{_player}%::%{_enchantment}%} < {_cooldown}:
            return false

    return true

function startEnchantCooldown(player: player, enchantment: string, level: integer):
    set {_cooldown} to "cooldown" of {_level} for {_enchantment}
    if {_cooldown} is set:
        set {-enchant cooldown::%{_player}%::%{_enchantment}%} to now

function miningEnchants(player: player, block: block):
    {_block} is within bound with id "mine"

    for {_enchantment}, {_level} in keyed sortedEnchantments({_player}'s tool):
        set {_onbreak} to {-ce::%{_enchantment}%::onbreak}
        {_onbreak} is set

        enchantCanRun({_player}, {_enchantment}, {_level}, {-mining luck::%{_player}%} ? 0) is true

        startEnchantCooldown({_player}, {_enchantment}, {_level})
        run {_onbreak} with arguments ({_player}, {_player}'s tool, {_level}, {_block}, type of {_block})

on break with priority high:
    event isn't canceled
    miningEnchants(player, block)

on entity shoot bow:
    location of shooter isn't within bound with id "spawn"
    location of projectile isn't within bound with id "spawn"
    projectile is an arrow

    set {-%projectile%::force} to projectile force

    for {_enchantment}, {_level} in keyed sortedEnchantments(shooter's tool):
        set {_onshoot} to {-ce::%{_enchantment}%::onshoot}
        if {_onshoot} isn't set:
            continue

        set {_threshold} to {-ce::%{_enchantment}%::threshold::%{_level}%}
        if {_threshold} is set:
            if projectile force < {_threshold}:
                continue

        if enchantCanRun(shooter, {_enchantment}, {_level}) is false:
            continue

        startEnchantCooldown(shooter, {_enchantment}, {_level})
        run {_onshoot} with arguments (shooter, shooter's tool, projectile, {_level}, projectile force)

on projectile hit with priority highest:
    event isn't canceled
    location of shooter isn't within bound with id "spawn"
    location of projectile isn't within bound with id "spawn"
    projectile is an arrow
    {-%projectile%::force} is set

    for {_enchantment}, {_level} in keyed sortedEnchantments(shooter's tool):
        set {_onhit} to {-ce::%{_enchantment}%::onhit}
        if {_onhit} isn't set:
            continue

        set {_threshold} to {-ce::%{_enchantment}%::threshold::%{_level}%}
        if {_threshold} is set:
            if {-%projectile%::force} < {_threshold}:
                continue

        if enchantCanRun(shooter, {_enchantment}, {_level}) is false:
            continue

        startEnchantCooldown(shooter, {_enchantment}, {_level})
        run {_onhit} with arguments (shooter, shooter's tool, projectile, {_level}, {-%projectile%::force}, (victim ? block))

on damage with priority highest:
    event isn't cancelled
    final damage > 0

    if damage cause is projectile:
        attacker is holding a bow

        for {_enchantment}, {_level} in keyed sortedEnchantments(attacker's tool):
            set {_onattack} to {-ce::%{_enchantment}%::onattack}
            if {_onattack} isn't set:
                continue

            set {_threshold} to {-ce::%{_enchantment}%::threshold::%{_level}%}
            if {_threshold} is set:
                if {-%projectile%::force} < {_threshold}:
                    continue

            if enchantCanRun(attacker, {_enchantment}, {_level}) is false:
                continue

            startEnchantCooldown(attacker, {_enchantment}, {_level})
            add result of {_onattack} with arguments (attacker, victim, projectile, {_level}, {-%projectile%::force}, damage) to damage

    else if damage cause is attack:
        for {_enchantment}, {_level} in keyed sortedEnchantments(attacker's tool):
            set {_onattack} to {-ce::%{_enchantment}%::onattack}
            {_onattack} is set

            enchantCanRun(attacker, {_enchantment}, {_level}) is true

            startEnchantCooldown(attacker, {_enchantment}, {_level})
            add result of {_onattack} with arguments (attacker, attacker's tool, {_level}, victim, damage) to damage

    for {_enchantment}, {_level} in keyed sortedEnchantments(victim's tool):
        set {_onattacked} to {-ce::%{_enchantment}%::onattacked}
        {_onattacked} is set

        enchantCanRun(victim, {_enchantment}, {_level}) is true

        startEnchantCooldown(victim, {_enchantment}, {_level})
        add result of {_onattacked} with arguments (victim, victim's tool, {_level}, attacker, damage, damage cause) to damage

    if attacker's helmet is a leather helmet:
        for {_enchantment}, {_level} in keyed sortedEnchantments(attacker's helmet):
            if {_attacker armor already processed::%{_enchantment}%} is set:
                continue

            set {_attacker armor already processed::%{_enchantment}%} to true
            set {_onattack} to {-ce::%{_enchantment}%::onattack}
            {_onattack} is set

            enchantCanRun(attacker, {_enchantment}, {_level}) is true

            startEnchantCooldown(attacker, {_enchantment}, {_level})
            add result of {_onattack} with arguments (attacker, attacker's helmet, {_level}, victim, damage, damage cause) to damage

    if victim's helmet is set:
        set {_attacker} to attacker ? victim

        for {_enchantment}, {_level} in keyed sortedEnchantments(victim's helmet):
            if {_victim armor already processed::%{_enchantment}%} is set:
                continue

            set {_victim armor already processed::%{_enchantment}%} to true
            set {_onattacked} to {-ce::%{_enchantment}%::onattacked}
            {_onattacked} is set

            enchantCanRun(victim, {_enchantment}, {_level}) is true

            startEnchantCooldown(victim, {_enchantment}, {_level})
            add result of {_onattacked} with arguments (victim, victim's helmet, {_level}, {_attacker}, damage, damage cause) to damage

    if damage < 0:
        cancel event

on swap items:
    bounds at player does not contain bound with id "spawn"

    for {_enchantment}, {_level} in keyed sortedEnchantments(player's tool):
        set {_onoffhand} to {-ce::%{_enchantment}%::onoffhand}
        {_onoffhand} is set

        enchantCanRun(player, {_enchantment}, {_level}) is true

        startEnchantCooldown(player, {_enchantment}, {_level})
        set {_should cancel} to result of {_onoffhand} with arguments (player, player's tool, {_level})

        if {_should cancel} is true:
            cancel event

on right click with priority monitor:
    bounds at player does not contain bound with id "spawn"

    for {_enchantment}, {_level} in keyed sortedEnchantments(player's tool):
        set {_onrightclick} to {-ce::%{_enchantment}%::onrightclick}
        {_onrightclick} is set

        enchantCanRun(player, {_enchantment}, {_level}) is true

        startEnchantCooldown(player, {_enchantment}, {_level})
        run {_onrightclick} with arguments (player, player's tool, {_level})

on left click with priority monitor:
    bounds at player does not contain bound with id "spawn"

    for {_enchantment}, {_level} in keyed sortedEnchantments(player's tool):
        set {_onleftclick} to {-ce::%{_enchantment}%::onleftclick}
        {_onleftclick} is set

        enchantCanRun(player, {_enchantment}, {_level}) is true

        startEnchantCooldown(player, {_enchantment}, {_level})
        run {_onleftclick} with arguments (player, player's tool, {_level})

on death with priority monitor:
    bounds at victim does not contain bound with id "spawn"

    for {_item} in victim's tool and victim's armor:
        {_item} isn't air
        for {_enchantment}, {_level} in keyed sortedEnchantments({_item}):
            set {_ondeath} to {-ce::%{_enchantment}%::ondeath}
            {_ondeath} is set

            enchantCanRun(victim, {_enchantment}, {_level}) is true

            startEnchantCooldown(victim, {_enchantment}, {_level})
            run {_ondeath} with arguments (victim, {_item}, {_level}, attacker)

    for {_item} in attacker's tool and attacker's armor:
        {_item} isn't air
        for {_enchantment}, {_level} in keyed sortedEnchantments({_item}):
            set {_onkill} to {-ce::%{_enchantment}%::onkill}
            {_onkill} is set

            enchantCanRun(attacker, {_enchantment}, {_level}) is true

            startEnchantCooldown(attacker, {_enchantment}, {_level})
            run {_onkill} with arguments (attacker, {_item}, {_level}, victim)


### summon related events

on entity removed from world:
    {-%entity%::*} is set
    delete {-%entity%::*}

on target:
    {-%entity%::owner} is set
    target is {-%entity%::owner}
    cancel event
