using reflection

on load:
    set {_now} to current ns

    loop indexes of {-ce::*}:
        cacheSpecificEnchantment(loop-value, false)

    loop indexes of {-vanilla enchantment::*}:
        loop "max level", "display":
            if {-vanilla enchantment::%loop-value-1%::%loop-value-2%} is not set:
                broadcast "Vanilla enchantment %loop-value-1% is missing %loop-value-2%!"

        loop integers between 2 and {-vanilla enchantment::%loop-value%::max}:
            if {-vanilla enchantment::%loop-value-1%::dust cost::%loop-value-2%} is not set:
                broadcast "Vanilla enchantment %loop-value-1% level %loop-value-2% is missing a dust cost!"
            if {-vanilla enchantment::%loop-value-1%::money cost::%loop-value-2%} is not set:
                broadcast "Vanilla enchantment %loop-value-1% level %loop-value-2% is missing a money cost!"


    refreshEnchantmentGui()
    
    set {_ms took} to (current ns - {_now}) / 1_000_000
    broadcast "Loaded %size of indices of {-ce::*}% enchantments in %{_ms took}% ms."

function cacheSpecificEnchantment(enchantment: string, broadcast: boolean = true):
    set {_now} to current ns

    set {_type} to {-ce::%{_enchantment}%::type}
    set {_ultimate} to {-ce::%{_enchantment}%::ultimate}

    set {_script name} to {_enchantment}
    replace all "_" in {_script name} with " "

    if {_ultimate} is true:
        set {_script} to script named "enchantments/custom/%{_type}%/ultimate/%{_script name}%"
    else:
        set {_script} to script named "enchantments/custom/%{_type}%/%{_script name}%"

    loop "onBreak", "onAttack", "onAttacked", "onDeath", "onOffHand", "onApply", "onUnapply", "onShoot", "onHit", "onRightClick", "onLeftClick", "onKill", "onDeath", "getDescription":
        set {-ce::%{_enchantment}%::%loop-value%} to function named loop-value from {_script}

    loop "getDescription", "max level", "display", "type", "priority", "item":
        if {-ce::%{_enchantment}%::%loop-value%} is not set:
            broadcast "Enchantment %{_enchantment}% is missing %loop-value%!"

    if {-ce::%{_enchantment}%::item} is set:
        apply tooltip display component to {-ce::%{_enchantment}%::item}:
            hidden_components: minecraft:potion_contents, minecraft:ominous_bottle_amplifier

    loop integers between 1 and {-ce::%{_enchantment}%::max level}:
        if {-ce::%{_enchantment}%::getDescription} is set:
            set {-ce::%{_enchantment}%::description::%loop-value%} to result of {-ce::%{_enchantment}%::getDescription} with arguments loop-value

        if {-ce::%{_enchantment}%::description::%loop-value%} is not set:
            broadcast "Enchantment %{_enchantment}% is missing a description for level %loop-value%!"

        if loop-value > 1:
            if {-ce::%{_enchantment}%::dust cost::%loop-value%} is not set:
                broadcast "Enchantment %{_enchantment}% level %loop-value% is missing a dust cost!"

            if {-ce::%{_enchantment}%::money cost::%loop-value%} is not set:
                broadcast "Enchantment %{_enchantment}% level %loop-value% is missing a money cost!"

    if {_broadcast} is true:
        broadcast "Cached %{_enchantment}% enchantment in %((current ns - {_now}) / 1_000_000)% ms."