using reflection

on load:
    set {_now} to current ns

    loop indexes of {-ce::*}:
        cacheSpecificEnchantment(loop-value, false)

    loop indexes of {-vanilla enchantment::*}:
        loop "max level", "display":
            if {-vanilla enchantment::%loop-value-1%::%loop-value-2%} is not set:
                send "Vanilla enchantment %loop-value-1% is missing %loop-value-2%!" to ops and console

        loop integers between 2 and {-vanilla enchantment::%loop-value%::max}:
            if {-vanilla enchantment::%loop-value-1%::dust cost::%loop-value-2%} is not set:
                send "Vanilla enchantment %loop-value-1% level %loop-value-2% is missing a dust cost!" to ops and console
            if {-vanilla enchantment::%loop-value-1%::money cost::%loop-value-2%} is not set:
                send "Vanilla enchantment %loop-value-1% level %loop-value-2% is missing a money cost!" to ops and console

    refreshEnchantmentGui()

    set {_ms took} to (current ns - {_now}) / 1_000_000
    send "Loaded %size of indices of {-ce::*}% enchantments in %{_ms took}% ms." to ops and console

    delete {-current ce::*}
    delete {-current ce ability}

function cacheSpecificEnchantment(enchantment: string, broadcast: boolean = true):
    set {_now} to current ns

    set {_type} to {-ce::%{_enchantment}%::type}
    set {_ultimate} to {-ce::%{_enchantment}%::ultimate}

    set {_script name} to {_enchantment}
    replace all "_" in {_script name} with " "

    if {_ultimate} is true:
        set {_script} to script named "enchantments/custom/%{_type}%/ultimate/%{_script name}%"
    else:
        set {_script} to script named "enchantments/custom/%{_type}%/%{_script name}%"

    for {_function} in "onBreak", "onAttack", "onAttacked", "onDeath", "onApply", "onUnapply", "onShoot", "onHit", "onKill", "getDescription":
        set {-ce::%{_enchantment}%::%{_function}%} to function named {_function} from {_script}

    for {_property} in "getDescription", "max level", "display", "type", "priority", "item":
        if {-ce::%{_enchantment}%::%{_property}%} is not set:
            send "Enchantment %{_enchantment}% is missing %{_property}%!" to ops and console

    if {-ce::%{_enchantment}%::item} is set:
        apply tooltip display component to {-ce::%{_enchantment}%::item}:
            hidden_components: minecraft:potion_contents, minecraft:ominous_bottle_amplifier

    for {_level} in integers between 1 and {-ce::%{_enchantment}%::max level}:
        if {-ce::%{_enchantment}%::getDescription} is set:
            set {_description} to result of {-ce::%{_enchantment}%::getDescription} with arguments {_level}

            if {_description} is not set:
                send "Enchantment %{_enchantment}% is missing a description for level %{_level}%!" to ops and console

        if {_level} > 1:
            if {-ce::%{_enchantment}%::dust cost::%{_level}%} is not set:
                send "Enchantment %{_enchantment}% level %{_level}% is missing a dust cost!" to ops and console

            if {-ce::%{_enchantment}%::money cost::%{_level}%} is not set:
                send "Enchantment %{_enchantment}% level %{_level}% is missing a money cost!" to ops and console

    for {_ability} in {-ce::%{_enchantment}%::abilities::*}:
        if {-ce ability::%{_ability}%::function} is not set:
            send "Enchantment %{_enchantment}% ability %{_ability}% is missing a function!" to ops and console

        broadcast "%{-ability binds::*}% - %{-ce ability::%{_ability}%::bind}%"
        if {-ability binds::*} doesn't contain {-ce ability::%{_ability}%::bind}:
            send "Enchantment %{_enchantment}% ability %{_ability}% has an invalid bind: %{_ce ability::%{_ability}%::bind} ? "none"%" to ops and console

    if {_broadcast} is true:
        send "Cached %{_enchantment}% enchantment in %((current ns - {_now}) / 1_000_000)% ms." to ops and console
