ultimate armor enchantment:
    id: "overload"
    display: "&f<sprite:gui:mob_effect/instant_health> <rainbow><bold>Overload"
    max level: 5
    priority: 1
    item: health potion
    cost: "expensive"

    > "regeneration":
        lvl. 1: potion effect of regeneration 2 for 3 seconds
        lvl. 2: potion effect of regeneration 2 for 4 seconds
        lvl. 3: potion effect of regeneration 2 for 5 seconds
        lvl. 4: potion effect of regeneration 2 for 6 seconds
        lvl. 5: potion effect of regeneration 3 for 6 seconds

    > "speed":
        lvl. 1: potion effect of speed 2 for 3 seconds
        lvl. 2: potion effect of speed 2 for 4 seconds
        lvl. 3: potion effect of speed 2 for 5 seconds
        lvl. 4: potion effect of speed 2 for 5 seconds
        lvl. 5: potion effect of speed 3 for 6 seconds

    > "health boost":
        lvl. 1: potion effect of health boost 1 for 15 seconds
        lvl. 2: potion effect of health boost 2 for 15 seconds
        lvl. 3: potion effect of health boost 2 for 15 seconds
        lvl. 4: potion effect of health boost 2 for 15 seconds
        lvl. 5: potion effect of health boost 3 for 15 seconds

    > "absorption":
        lvl. 1: potion effect of absorption 1 for 5 seconds
        lvl. 2: potion effect of absorption 1 for 6 seconds
        lvl. 3: potion effect of absorption 1 for 7 seconds
        lvl. 4: potion effect of absorption 2 for 8 seconds
        lvl. 5: potion effect of absorption 2 for 10 seconds

    > "feed":
        lvl. 1: 2
        lvl. 2: 3
        lvl. 3: 4
        lvl. 4: 5
        lvl. 5: 10

local function getDescription(level: integer) :: string:
    set {_feed} to "feed" of "overload" at {_level}
    set {_regeneration} to "regeneration" of "overload" at {_level}
    set {_speed} to "speed" of "overload" at {_level}
    set {_health boost} to "health boost" of "overload" at {_level}
    set {_absorption} to "absorption" of "overload" at {_level}
    return "on kill&8, &7feed you by &f%{-effect::saturation::display}%%{_feed}%&8, &7and grant &f%effectDisplay({_regeneration})%&8, &f%effectDisplay({_speed})%&8, &f%effectDisplay({_health boost})%&8, &7and &f%effectDisplay({_absorption})%"

local function onKill(attacker: entity, armor: item, level: integer, victim: entity):
    {_victim} is a player
    set {_feed} to "feed" of "overload" at {_level}
    set {_regeneration} to "regeneration" of "overload" at {_level}
    set {_speed} to "speed" of "overload" at {_level}
    set {_health boost} to "health boost" of "overload" at {_level}
    set {_absorption} to "absorption" of "overload" at {_level}

    set {_attacker}'s food level to clamp({_attacker}'s food level + {_feed}, 0, 10)
    add {_regeneration} to {_attacker}'s potion effects
    add {_speed} to {_attacker}'s potion effects
    add {_health boost} to {_attacker}'s potion effects
    add {_absorption} to {_attacker}'s potion effects
    