on load:
    create ultimate armor enchantment named "overload":
        set enchantment ultimate to true
        set enchantment display to "&f<sprite:gui:mob_effect/instant_health> <rainbow><bold>Overload"
        set enchantment max level to 5
        set enchantment priority to 1
        set enchantment item to health potion

        level values for "regeneration":
            set level 1 to potion effect of regeneration 2 for 3 seconds
            set level 2 to potion effect of regeneration 2 for 4 seconds
            set level 3 to potion effect of regeneration 2 for 5 seconds
            set level 4 to potion effect of regeneration 2 for 6 seconds
            set level 5 to potion effect of regeneration 3 for 6 seconds

        level values for "speed":
            set level 1 to potion effect of speed 2 for 3 seconds
            set level 2 to potion effect of speed 2 for 4 seconds
            set level 3 to potion effect of speed 2 for 5 seconds
            set level 4 to potion effect of speed 2 for 5 seconds
            set level 5 to potion effect of speed 3 for 6 seconds

        level values for "health boost":
            set level 1 to potion effect of health boost 1 for 15 seconds
            set level 2 to potion effect of health boost 2 for 15 seconds
            set level 3 to potion effect of health boost 2 for 15 seconds
            set level 4 to potion effect of health boost 2 for 15 seconds
            set level 5 to potion effect of health boost 3 for 15 seconds

        level values for "absorption":
            set level 1 to potion effect of absorption 1 for 5 seconds
            set level 2 to potion effect of absorption 1 for 6 seconds
            set level 3 to potion effect of absorption 1 for 7 seconds
            set level 4 to potion effect of absorption 2 for 8 seconds
            set level 5 to potion effect of absorption 2 for 10 seconds

        level values for "feed":
            set level 1 to 2
            set level 2 to 3
            set level 3 to 4
            set level 4 to 5
            set level 5 to 10

        level values for "xp cost":
            set level 1 to 400_000
            set level 2 to 1_500_000
            set level 3 to 2_500_000
            set level 4 to 4_000_000
            set level 5 to 6_000_000

        level values for "money cost":
            set level 1 to 500_000
            set level 2 to 2_000_000
            set level 3 to 3_000_000
            set level 4 to 5_000_000
            set level 5 to 7_500_000

local function getDescription(level: integer) :: string:
    set {_feed} to "feed" of {_level} for "overload"
    set {_regeneration} to "regeneration" of {_level} for "overload"
    set {_speed} to "speed" of {_level} for "overload"
    set {_health boost} to "health boost" of {_level} for "overload"
    set {_absorption} to "absorption" of {_level} for "overload"
    return "on kill&8, &7feed you by &f%{-effect::saturation::display}%%{_feed}%&8, &7and grant &f%effectDisplay({_regeneration})%&8, &f%effectDisplay({_speed})%&8, &f%effectDisplay({_health boost})%&8, &7and &f%effectDisplay({_absorption})%"

local function onkill(attacker: entity, armor: item, level: integer, victim: entity):
    {_victim} is a player
    set {_feed} to "feed" of {_level} for "overload"
    set {_regeneration} to "regeneration" of {_level} for "overload"
    set {_speed} to "speed" of {_level} for "overload"
    set {_health boost} to "health boost" of {_level} for "overload"
    set {_absorption} to "absorption" of {_level} for "overload"

    set {_attacker}'s food level to clamp({_attacker}'s food level + {_feed}, 0, 10)
    add {_regeneration} to {_attacker}'s potion effects
    add {_speed} to {_attacker}'s potion effects
    add {_health boost} to {_attacker}'s potion effects
    add {_absorption} to {_attacker}'s potion effects