function bar(entity: entity):
    canBeBarred({_entity}) is true

    # clean the old bar
    deleteBar({_entity})

    # healthbar
    spawn text display at {_entity}:
        set {-healthbar::%{_entity}%} to text display
        make text display not persistent
        make text display ride {_entity}
        set billboard of text display to center
        set color of text display to rgb(0, 0, 0, 0)
        set transformation translation of text display to vector(0, 0.25 + {-bar height modifier::%{_entity}%}, 0)
        set transformation scale of text display to vector(0.35, 1.25, 0.35)
        set line width of text display to 400
        set view range of text display to 0.5
        apply drop shadow to text display
        set data tag "bar" of text display to true

    # health number
    spawn text display at {_entity}:
        set {-health number::%{_entity}%} to text display
        make text display not persistent
        make text display ride {_entity}
        set billboard of text display to center
        set transformation translation of text display to vector(0, 0.45 + {-bar height modifier::%{_entity}%}, 0)
        set transformation scale of text display to vector(0.6, 0.6, 0.6)
        set line width of text display to 400
        set view range of text display to 0.5
        apply drop shadow to text display
        set data tag "bar" of text display to true

    # nametag
    spawn text display at {_entity}:
        set {-nametag::%{_entity}%} to text display
        make text display not persistent
        make text display ride {-healthbar::%{_entity}%}
        set billboard of text display to center
        set transformation translation of text display to vector(0, 0.15 + {-bar height modifier::%{_entity}%}, 0)
        set transformation scale of text display to vector(0.75, 0.75, 0.75)
        set line width of text display to 400
        set view range of text display to 0.5
        make text display visible through blocks
        apply drop shadow to text display
        set data tag "bar" of text display to true

    updateHealthbar({_entity})
    updateNametag({_entity})
    updateVisibility({_entity})

function canBeBarred(entity: entity) :: boolean:
    {_entity} is a living entity
    {_entity} isn't an armor stand
    {-no bar::%{_entity}%} isn't set
    return true

function deleteBar(entity: entity):
    delete {-no bar::%{_entity}%}
    kill {-healthbar::%{_entity}%}, {-nametag::%{_entity}%}, {-health number::%{_entity}%}
    delete {-healthbar::%{_entity}%}, {-nametag::%{_entity}%}, {-health number::%{_entity}%}, {-lasthealth::%{_entity}%}

function updateHealthbar(entity: entity):
    set {_currentHealth} to {_entity}'s health
    set {_maxHealth} to {_entity}'s max health
    set {_absorption} to {_entity}'s absorption amount / 2

    {_maxHealth} > 0

    set {_totalPercentage} to (({_currentHealth} + {_absorption}) / {_maxHealth}) * 100
    set text of {-health number::%{_entity}%} to "%round({_totalPercentage})%"

    set {_totalCapacity} to {_maxHealth} + {_absorption}
    set {_lastHealth} to {-lasthealth::%{_entity}%} ? {_currentHealth}

    set {_filledGreen} to round(({_currentHealth} / {_totalCapacity}) * 50)
    set {_filledGold} to round(({_absorption} / {_totalCapacity}) * 50)

    set {_filledGreen} to clamp({_filledGreen}, 0, 50)
    set {_filledGold} to clamp({_filledGold}, 0, 50 - {_filledGreen})

    set {_deltaHealth} to round((({_currentHealth} - {_lastHealth}) / {_totalCapacity}) * 50)

    set {_healthColor} to "&a"
    if {_filledGreen} <= 10:
        set {_healthColor} to "&c"
    else if {_filledGreen} <= 24:
        set {_healthColor} to "&e"

    if {_deltaHealth} != 0:
        if {_deltaHealth} < 0:
            set {_oldGreen} to {_filledGreen} + (0 - {_deltaHealth})
            set {_oldGreen} to clamp({_oldGreen}, 0, 50 - {_filledGold})

            add "%{_healthColor}%&m " repeated {_filledGreen} times to {_flashBar::*}

            set {_damageSegments} to {_oldGreen} - {_filledGreen}
            set {_damageSegments} to clamp({_damageSegments}, 0, 50 - {_filledGreen} - {_filledGold})

            add "&4&m " repeated {_damageSegments} times to {_flashBar::*}

            set {_flashUsed} to {_filledGreen} + {_damageSegments} + {_filledGold}

        else:
            set {_oldGreen} to {_filledGreen} - {_deltaHealth}
            set {_oldGreen} to clamp({_oldGreen}, 0, {_filledGreen})

            add "%{_healthColor}%&m " repeated {_oldGreen} times to {_flashBar::*}

            set {_healSegments} to {_filledGreen} - {_oldGreen}
            set {_healSegments} to clamp({_healSegments}, 0, 50 - {_oldGreen} - {_filledGold})

            add "&2&m " repeated {_healSegments} times to {_flashBar::*}

            set {_flashUsed} to {_oldGreen} + {_healSegments} + {_filledGold}

        add "&6&m " repeated {_filledGold} times to {_flashBar::*}

        set {_remaining} to 50 - {_flashUsed}
        set {_remaining} to clamp({_remaining}, 0, 50)

        add "&8&m " repeated {_remaining} times to {_flashBar::*}

        set text of {-healthbar::%{_entity}%} to join {_flashBar::*} with ""

        wait 1 tick
        delete {_flashBar::*}

    add "%{_healthColor}%&m " repeated {_filledGreen} times to {_bar::*}
    add "&6&m " repeated {_filledGold} times to {_bar::*}

    set {_remainingEmpty} to 50 - ({_filledGreen} + {_filledGold})
    set {_remainingEmpty} to clamp({_remainingEmpty}, 0, 50)

    add "&8&m " repeated {_remainingEmpty} times to {_bar::*}

    set text of {-healthbar::%{_entity}%} to join {_bar::*} with ""
    set {-lasthealth::%{_entity}%} to {_currentHealth}

function updateNametag(entity: entity):
    set {_name} to {_entity}'s display name

    if {_name} is not set:
        set {_name} to {_entity}'s name

    if {_entity} is a player:
        set {_display} to playerDisplay({_entity}, "[level] [prefix][player]")
    else:
        set {_display} to {_name}

    set text of {-nametag::%{_entity}%} to {_display} ? "&7%{_name}%"

function updateVisibility(entity: entity):
    set color of {-healthbar::%{_entity}%} to rgb(0, 0, 0, 0)

    if bound at {_entity} contains bound with id "spawn":
        reset color of {-nametag::%{_entity}%}
        set text opacity of {-nametag::%{_entity}%} to 255

        set color of {-health number::%{_entity}%} to rgb(0, 0, 0, 0)
        set text opacity of {-healthbar::%{_entity}%} to 0
        set text opacity of {-health number::%{_entity}%} to 0
    else:
        if any:
            {_entity} is sneaking
            potion level of invisibility potion effect of {_entity} > 0
        then:
            set color of {-nametag::%{_entity}%} to rgb(0, 0, 0, 0)
            set color of {-health number::%{_entity}%} to rgb(0, 0, 0, 0)

            set text opacity of {-nametag::%{_entity}%} to 0
            set text opacity of {-healthbar::%{_entity}%} to 0
            set text opacity of {-health number::%{_entity}%} to 0
        else:
            reset color of {-nametag::%{_entity}%}
            reset color of {-health number::%{_entity}%}

            set text opacity of {-nametag::%{_entity}%} to 255
            set text opacity of {-healthbar::%{_entity}%} to 255
            set text opacity of {-health number::%{_entity}%} to 255

on load:
    resetBars()

function resetBars(wait: boolean = true):
    loop all entities where [input is a display or a living entity]:
        if {_wait} is true:
            wait 1 tick
        if loop-entity is a display:
            set {_isHealthbar} to data tag "bar" of loop-entity
            if {_isHealthbar} is set:
                kill loop-entity
        else:
            bar(loop-entity)

function heal(entity: entity, amount: number):
    {_amount} > 0
    heal {_entity} by {_amount}
    wait 1 tick
    updateHealthbar({_entity})
    damageIndicator({_entity}, healing: {_amount})

function damageIndicator(entity: entity, damage: number = {_}, healing: number = {_}):
    spawn text display at {_entity}'s head ~ vector(random number between -0.5 and 0.5, 0.5, random number between -0.5 and 0.5):
        set {_display} to text display
        set billboard of {_display} to center
        make {_display} not persistent
        if {_healing} is set:
            set text of {_display} to "&a%{_healing}%"
        else if {_damage} is set:
            set text of {_display} to "&c%{_damage}%"
        apply drop shadow to text of {_display}
        set teleport duration of {_display} to 5 ticks
    teleport {_display} to {_display} ~ vector(0, 0.5, 0)

    wait 5 ticks
    kill {_display}