on load:
    create pickaxe enchantment named "beacon_finder":
        set enchantment display to "&f<sprite:blocks:block/beacon> &b&lBEACON &bFinder"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to beacon

        level values for "chance":
            set level 1 to 0.001
            set level 2 to 0.002
            set level 3 to 0.003
            set level 4 to 0.004
            set level 5 to 0.005

        level values for "xp cost":
            set level 2 to 55_000
            set level 3 to 250_000
            set level 4 to 700_000
            set level 5 to 1_600_000

        level values for "money cost":
            set level 2 to 75_000
            set level 3 to 300_000
            set level 4 to 800_000
            set level 5 to 2_000_000

local function getDescription(level: integer) :: string:
    return "instantly gives you a beacon"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    playEnchantmentSound("mining", "minecraft:block.beacon.activate", 0.5, 1, location of {_player}, all players, {_player})
    giveBeacons({_player}, 1)
