pickaxe enchantment:
    id: "beacon_finder"
    display: "&f<sprite:blocks:block/beacon> &b&lBEACON &bFinder"
    max level: 5
    priority: 10
    item: beacon
    cost: "expensive"

    > "chance":
        lvl. 1: 0.001%
        lvl. 2: 0.002%
        lvl. 3: 0.003%
        lvl. 4: 0.004%
        lvl. 5: 0.005%

local function getDescription(level: integer) :: string:
    return "instantly gives you a beacon"

local function onBreak(player: player, level: integer, block: block):
    playEnchantmentSound("mining", "minecraft:block.beacon.activate", 0.5, 1, location of {_player}, all players, {_player})
    giveBeacons({_player}, 1)