on load:
    create pickaxe enchantment named "beam":
        set enchantment display to "&f<sprite:gui:container/bundle/bundle_progressbar_full> &4Beam"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to blaze rod

        level values for "chance":
            set level 1 to 5
            set level 2 to 7
            set level 3 to 9
            set level 4 to 11
            set level 5 to 13

        level values for "radius":
            set level 1 to 1.25
            set level 2 to 1.35
            set level 3 to 1.5
            set level 4 to 1.65
            set level 5 to 1.75

        level values for "distance":
            set level 1 to 30
            set level 2 to 35
            set level 3 to 40
            set level 4 to 45
            set level 5 to 50

        level values for "xp cost":
            set level 2 to 40_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

        level values for "money cost":
            set level 2 to 60_000
            set level 3 to 200_000
            set level 4 to 600_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "beam" at {_level}
    return "break blocks in a &f%{_radius}%m &7beam"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_distance} to "distance" of "beam" at {_level}
    set {_radius} to "radius" of "beam" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.ender_dragon.flap", 0.5, 1, location of {_player}, all players, {_player})
    set {_origin} to location of {_player}'s head
    set {_vector} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch

    loop {_distance} times:
        set vector length of {_vector} to loop-value / 4
        set {_bullet} to {_origin} ~ {_vector}
        
        draw 4 red dust particle at {_bullet}

        loop all blocks in radius {_radius} around {_bullet}:
            loop-block isn't air
            loop-block isn't bedrock, beacon, obsidian, black concrete, or packed ice
            loop-block is within bound with id "mine"
            {_affected::*} doesn't contain loop-block

            if mod(loop-iteration-1, 8) = 0:
                wait 1 tick

            blockReward({_player}, {_player}'s tool, loop-block, "beam enchantment")

            set loop-block to air
            add loop-block to {_affected::*}
