pickaxe enchantment:
    id: "beam"
    display: "&f<sprite:gui:container/bundle/bundle_progressbar_full> &4Beam"
    max level: 5
    priority: 10
    item: blaze rod
    cost: "normal"

    > "chance":
        lvl. 1: 5
        lvl. 2: 7
        lvl. 3: 9
        lvl. 4: 11
        lvl. 5: 13

    > "radius":
        lvl. 1: 1.25
        lvl. 2: 1.35
        lvl. 3: 1.5
        lvl. 4: 1.65
        lvl. 5: 1.75

    > "distance":
        lvl. 1: 30
        lvl. 2: 35
        lvl. 3: 40
        lvl. 4: 45
        lvl. 5: 50

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "beam" at {_level}
    return "break blocks in a &f%{_radius}%m &7beam"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_distance} to "distance" of "beam" at {_level}
    set {_radius} to "radius" of "beam" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.ender_dragon.flap", 0.5, 1, location of {_player}, all players, {_player})
    set {_origin} to location of {_player}'s head
    set {_vector} to vector from yaw {_player}'s yaw and pitch {_player}'s pitch

    loop {_distance} times:
        set vector length of {_vector} to loop-value / 4
        set {_bullet} to {_origin} ~ {_vector}
        
        draw 4 red dust particle at {_bullet}

        loop all blocks in radius {_radius} around {_bullet}:
            loop-block isn't air
            loop-block isn't bedrock, beacon, obsidian, black concrete, or packed ice
            loop-block is within bound with id "mine"
            {_affected::*} doesn't contain loop-block

            if mod(loop-iteration-1, 8) = 0:
                wait 1 tick

            blockReward({_player}, {_player}'s tool, loop-block, "beam enchantment")

            set loop-block to air
            add loop-block to {_affected::*}