pickaxe enchantment:
    id: "blast"
    display: "&f<sprite:blocks:block/tnt_side> &cBlast"
    max level: 5
    priority: 10
    item: tnt
    cost: "normal"

    > "chance":
        lvl. 1: 12%
        lvl. 2: 14%
        lvl. 3: 16%
        lvl. 4: 18%
        lvl. 5: 22%

    > "radius":
        lvl. 1: 1.75
        lvl. 2: 1.85
        lvl. 3: 2
        lvl. 4: 2.15
        lvl. 5: 2.4

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "blast" at {_level}
    return "break blocks within &f%{_radius}%m"

local function onBreak(player: player, level: integer, block: block):
    set {_radius} to "radius" of "blast" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.generic.explode", 0.25, 1, location of {_block}, all players, {_player})
    fastRadiusClear({_player}, location of {_block}, {_radius})
    