on load:
    create pickaxe enchantment named "blast":
        set enchantment display to "&f<sprite:blocks:block/tnt_side> &cBlast"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to tnt

        level values for "chance":
            set level 1 to 12
            set level 2 to 14
            set level 3 to 16
            set level 4 to 18
            set level 5 to 22

        level values for "radius":
            set level 1 to 1.75
            set level 2 to 1.85
            set level 3 to 2
            set level 4 to 2.15
            set level 5 to 2.4

        level values for "money cost":
            set level 2 to 160_000
            set level 3 to 500_000
            set level 4 to 1_800_000
            set level 5 to 3_000_000

        level values for "dust cost":
            set level 2 to 40
            set level 3 to 150
            set level 4 to 2_300
            set level 5 to 4_900

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "blast" at {_level}
    return "break blocks within &f%{_radius}%m"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    playEnchantmentSound("mining", "minecraft:entity.generic.explode", 0.25, 1, location of {_block}, all players, {_player})
    set {_radius} to "radius" of "blast" at {_level}
    fastRadiusClear({_player}, location of {_block}, {_radius})