using reflection

on load:
    create pickaxe enchantment named "chaos":
        set enchantment display to "&f<sprite:items:item/echo_shard> &5Chaos"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to echo shard

        level values for "chance":
            set level 1 to 5
            set level 2 to 6
            set level 3 to 7
            set level 4 to 8
            set level 5 to 10

        level values for "enchantments":
            set level 1 to 1
            set level 2 to 2
            set level 3 to 2
            set level 4 to 3
            set level 5 to 5

        level values for "luck boost":
            set level 1 to 0.05
            set level 2 to 0.1
            set level 3 to 0.15
            set level 4 to 0.2
            set level 5 to 0.25

        level values for "xp cost":
            set level 2 to 50_000
            set level 3 to 200_000
            set level 4 to 450_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 65_000
            set level 3 to 275_000
            set level 4 to 550_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_enchantments} to "enchantments" of {_level} for "chaos"
    set {_luck boost} to "luck boost" of {_level} for "chaos"
    return "spin &f%{_enchantments}% &7random enchantments with &f%{_luck boost} * 100%%% &7luck boost"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_enchantments} to "enchantments" of {_level} for "chaos"
    set {_luck boost} to "luck boost" of {_level} for "chaos"
    playEnchantmentSound("mining", "minecraft:entity.evoker.cast_spell", 0.5, 1, location of {_player}, all players, {_player})
    set {_enchantments::*} to custom enchantments of {_tool}
    set {_indices::*} to indices of {_enchantments::*}
    set {_indices::*} to shuffled {_indices::*}
    remove "chaos", "reroll", "lucky" from {_indices::*}
    loop {_indices::*}:
        if loop-iteration > {_enchantments}:
            stop
        set {_chance} to {-ce::%loop-value%::chance::%{_enchantments::%loop-value%}%}
        if {-ce::%loop-value%::onbreak} is set:
            if {_chance} is set:
                # if chance doesn't succeed, skip the enchantment
                set {_chance} to {_chance} * (1 + ({-mining luck::%{_player}%} ? 0) + ({_luck boost} ? 0))
                chance of (100 - {_chance})%:
                    continue

            run {-ce::%loop-value%::onbreak} with arguments ({_player}, {_player}'s tool, {_enchantments::%loop-value%}, {_block}, {_block type})
