using reflection

on load:
    setting("chaos", "display", value: "&f<sprite:items:item/echo_shard> &5Chaos")
    setting("chaos", "max", value: 5)
    setting("chaos", "priority", value: 0)
    setting("chaos", "type", value: "pickaxe")
    setting("chaos", "item", value: echo shard)

    setting("chaos", "chance", l1: 5, l2: 6, l3: 7, l4: 8, l5: 10)

    setting("chaos", "enchantments", l1: 1, l2: 2, l3: 2, l4: 3, l5: 5)
    setting("chaos", "luck boost", l1: 0.05, l2: 0.1, l3: 0.15, l4: 0.2, l5: 0.25)

    setting("chaos", "xp cost", l2: 50_000, l3: 200_000, l4: 450_000, l5: 1_000_000)
    setting("chaos", "money cost", l2: 65_000, l3: 275_000, l4: 550_000, l5: 1_500_000)

local function getDescription(level: integer) :: string:
    return "spin %get_setting("chaos", "enchantments", {_level})% random enchantments with %get_setting("chaos", "luck boost", {_level}) * 100%%% luck boost"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    play sound "minecraft:entity.evoker.cast_spell" with volume 0.5 and pitch 1 at location of {_player}
    set {_enchantments::*} to custom enchantments of {_tool} # keyed getEnchantments({_tool})
    set {_indices::*} to indices of {_enchantments::*}
    set {_indices::*} to shuffled {_indices::*}
    remove "chaos", "reroll", "lucky" from {_indices::*}
    loop {_indices::*}:
        if loop-iteration > get_setting("chaos", "enchantments", {_level}):
            stop
        set {_chance} to {-ce::%loop-value%::chance::%{_enchantments::%loop-value%}%}
        if {-ce::%loop-value%::onbreak} is set:
            if {_chance} is set:
                # if chance doesn't succeed, skip the enchantment
                set {_chance} to {_chance} * (1 + ({-mining luck::%{_player}%} ? 0) + (get_setting("chaos", "luck boost", {_level}) ? 0))
                chance of (100 - {_chance})%:
                    continue

            run {-ce::%loop-value%::onbreak} with arguments ({_player}, {_player}'s tool, {_enchantments::%loop-value%}, {_block}, {_block type})