using reflection

pickaxe enchantment:
    id: "chaos"
    display: "&f<sprite:items:item/echo_shard> &5Chaos"
    max level: 5
    priority: 0
    item: echo shard
    cost: "normal"

    > "chance":
        lvl. 1: 5%
        lvl. 2: 6%
        lvl. 3: 7%
        lvl. 4: 8%
        lvl. 5: 10%

    > "enchantments":
        lvl. 1: 1
        lvl. 2: 2
        lvl. 3: 2
        lvl. 4: 3
        lvl. 5: 5

    > "luck boost":
        lvl. 1: 5%
        lvl. 2: 10%
        lvl. 3: 15%
        lvl. 4: 20%
        lvl. 5: 25%

local function getDescription(level: integer) :: string:
    set {_enchantments} to "enchantments" of "chaos" at {_level}
    set {_luck boost} to "luck boost" of "chaos" at {_level}
    return "spin &f%{_enchantments}% &7random enchantments with &f%{_luck boost} * 100%%% &7luck boost"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_enchantments} to "enchantments" of "chaos" at {_level}
    set {_luck boost} to "luck boost" of "chaos" at {_level}

    playEnchantmentSound("mining", "minecraft:entity.evoker.cast_spell", 0.5, 1, location of {_player}, all players, {_player})
    
    set {_enchantments::*} to {-cached enchantments::%{_player}%::pickaxe::*}
    set {_indices::*} to indices of {_enchantments::*}
    set {_indices::*} to shuffled {_indices::*}
    remove "chaos", "reroll", "lucky" from {_indices::*}
    loop {_indices::*}:
        if loop-iteration > {_enchantments}:
            stop
        if {-ce::%loop-value%::onBreak} is set:
            if enchantCanRun({_player}, loop-value, {_enchantments::%loop-value%}, {_luck boost}) is true:
                startEnchantCooldown({_player}, loop-value, {_enchantments::%loop-value%})
                run {-ce::%loop-value%::onBreak} with arguments ({_player}, {_player}'s tool, {_enchantments::%loop-value%}, {_block}, type of {_block})