on load:
    create pickaxe enchantment named "corrode":
        set enchantment display to "&f<sprite:items:item/fermented_spider_eye> &8Corrode"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to fermented spider eye

        level values for "chance":
            set level 1 to 1
            set level 2 to 2
            set level 3 to 3
            set level 4 to 4
            set level 5 to 5

        level values for "radius":
            set level 1 to 3
            set level 2 to 3
            set level 3 to 3
            set level 4 to 3
            set level 5 to 3

        level values for "expansion":
            set level 1 to 0.5
            set level 2 to 0.5
            set level 3 to 0.5
            set level 4 to 0.5
            set level 5 to 0.75

        level values for "xp cost":
            set level 2 to 80_000
            set level 3 to 200_000
            set level 4 to 600_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 750_000
            set level 5 to 1_300_000

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of {_level} for "corrode"
    set {_expansion} to "expansion" of {_level} for "corrode"
    return "break blocks within %{_radius}%m, expanding by %{_expansion}% * 5"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    play sound "minecraft:entity.zombie.break_wooden_door" with volume 0.5 and pitch 1 at location of {_player}

    set {_center} to location of {_block}
    set {_radius} to "radius" of {_level} for "corrode"
    set {_expansion} to "expansion" of {_level} for "corrode"
    
    loop 5 times:
        wait 10 ticks
        play sound "minecraft:entity.zombie.break_wooden_door" with volume 0.5 and pitch 1 at {_center}
        add {_expansion} to {_radius}

        fastRadiusClear({_player}, {_center}, {_radius})
