pickaxe enchantment:
    id: "corrode"
    display: "&f<sprite:items:item/fermented_spider_eye> &8Corrode"
    max level: 5
    priority: 10
    item: fermented spider eye
    cost: "normal"

    > "chance":
        lvl. 1: 1
        lvl. 2: 2
        lvl. 3: 3
        lvl. 4: 4
        lvl. 5: 5

    > "radius":
        lvl. 1: 3
        lvl. 2: 3
        lvl. 3: 3
        lvl. 4: 3
        lvl. 5: 3

    > "expansion":
        lvl. 1: 0.5
        lvl. 2: 0.5
        lvl. 3: 0.5
        lvl. 4: 0.5
        lvl. 5: 0.75

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "corrode" at {_level}
    set {_expansion} to "expansion" of "corrode" at {_level}
    return "break blocks within &f%{_radius}%m&8, &7expanding by &f%{_expansion}% * 5"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    playEnchantmentSound("mining", "minecraft:entity.zombie.break_wooden_door", 0.5, 1, location of {_player}, all players, {_player})

    set {_center} to location of {_block}
    set {_radius} to "radius" of "corrode" at {_level}
    set {_expansion} to "expansion" of "corrode" at {_level}
    
    loop 5 times:
        wait 10 ticks
        playEnchantmentSound("mining", "minecraft:entity.zombie.break_wooden_door", 0.5, 1, {_center}, all players, {_player})
        add {_expansion} to {_radius}

        fastRadiusClear({_player}, {_center}, {_radius})