pickaxe enchantment:
    id: "dust_boost"
    display: "&f<sprite:items:item/gunpowder> &bDust Boost"
    max level: 10
    priority: 9999
    item: gunpowder
    cost: "expensive"

    > "chance":
        lvl. 1: 20%
        lvl. 2: 25%
        lvl. 3: 30%
        lvl. 4: 35%
        lvl. 5: 40%
        lvl. 6: 45%
        lvl. 7: 50%
        lvl. 8: 55%
        lvl. 9: 60%
        lvl. 10: 75%

    > "multiplier":
        lvl. 1: 5
        lvl. 2: 5.5
        lvl. 3: 6
        lvl. 4: 6.5
        lvl. 5: 7
        lvl. 6: 7.5
        lvl. 7: 8
        lvl. 8: 8.5
        lvl. 9: 9
        lvl. 10: 10

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "dust_boost" at {_level}
    return "boost dust gain &f%{_multiplier}%x"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_multiplier} to "multiplier" of "dust_boost" at {_level}
    set {_dust} to {_multiplier} * {-dust::%{_block type}%}
    add {_dust} to {dust::%{_player}%}
    playEnchantmentSound("mining", "minecraft:entity.experience_orb.pickup", 0.5, 1, location of {_player}, all players, {_player})