on load:
    create pickaxe enchantment named "dust_boost":
        set enchantment display to "&f<sprite:items:item/gunpowder> &bDust Boost"
        set enchantment max level to 10
        set enchantment priority to 9999
        set enchantment item to gunpowder

        level values for "chance":
            set level 1 to 20
            set level 2 to 25
            set level 3 to 30
            set level 4 to 35
            set level 5 to 40
            set level 6 to 45
            set level 7 to 50
            set level 8 to 55
            set level 9 to 60
            set level 10 to 75

        level values for "multiplier":
            set level 1 to 5
            set level 2 to 5.5
            set level 3 to 6
            set level 4 to 6.5
            set level 5 to 7
            set level 6 to 7.5
            set level 7 to 8
            set level 8 to 8.5
            set level 9 to 9
            set level 10 to 10

        level values for "dust cost":
            set level 2 to 0
            set level 3 to 5
            set level 4 to 20
            set level 5 to 70
            set level 6 to 275
            set level 7 to 1_100
            set level 8 to 2_200
            set level 9 to 17_000
            set level 10 to 24_000

        level values for "money cost":
            set level 2 to 1_500
            set level 3 to 6_000
            set level 4 to 24_000
            set level 5 to 96_000
            set level 6 to 384_000
            set level 7 to 1_250_000
            set level 8 to 2_500_000
            set level 9 to 7_000_000
            set level 10 to 11_300_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "dust_boost" at {_level}
    return "boost dust gain &f%{_multiplier}%x"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_multiplier} to "multiplier" of "dust_boost" at {_level}
    set {_dust} to {_multiplier} * {-dust::%{_block type}%}
    add {_dust} to {dust::%{_player}%}
    playEnchantmentSound("mining", "minecraft:entity.experience_orb.pickup", 0.5, 1, location of {_player}, all players, {_player})