on load:
    create pickaxe enchantment named "excavator":
        set enchantment display to "&f<sprite:items:item/netherite_shovel> &9Excavator"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to netherite shovel

        level values for "chance":
            set level 1 to 5
            set level 2 to 6
            set level 3 to 7
            set level 4 to 8
            set level 5 to 15

        level values for "dust cost":
            set level 2 to 35
            set level 3 to 200
            set level 4 to 350
            set level 5 to 900

        level values for "money cost":
            set level 2 to 40_000
            set level 3 to 225_000
            set level 4 to 375_000
            set level 5 to 1_000_000

local function getDescription(level: integer) :: string:
    return "make you break a nearby block"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    playEnchantmentSound("mining", "minecraft:block.gravel.break", 0.5, 1, location of {_player}, all players, {_player})
    while {_target} isn't set:
        add 1 to {_n}
        set {_potential} to random element out of (blocks in radius 3 around {_block})
        if all:
            {_potential} is within bound with id "mine"
            {_potential} isn't bedrock, beacon, obsidian, black concrete, or packed ice
        then:
            set {_target} to {_potential}
            stop loop
        if {_n} > 5:
            set {_target} to {_block}
    {_player}.breakBlock({_target})