pickaxe enchantment:
    id: "excavator"
    display: "&f<sprite:items:item/netherite_shovel> &9Excavator"
    max level: 5
    priority: 10
    item: netherite shovel
    cost: "normal"

    > "chance":
        lvl. 1: 5%
        lvl. 2: 6%
        lvl. 3: 7%
        lvl. 4: 8%
        lvl. 5: 15%

local function getDescription(level: integer) :: string:
    return "make you break a nearby block"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    playEnchantmentSound("mining", "minecraft:block.gravel.break", 0.5, 1, location of {_player}, all players, {_player})
    while {_target} isn't set:
        add 1 to {_n}
        set {_potential} to random element out of (blocks in radius 3 around {_block})
        if all:
            {_potential} is within bound with id "mine"
            {_potential} isn't bedrock, beacon, obsidian, black concrete, or packed ice
        then:
            set {_target} to {_potential}
            stop loop
        if {_n} > 5:
            set {_target} to {_block}
    {_player}.breakBlock({_target})