on load:
    create pickaxe enchantment named "experienced":
        set enchantment display to "&f<sprite:items:item/experience_bottle> &aExperienced"
        set enchantment max level to 5
        set enchantment priority to 100
        set enchantment item to experience bottle

        level values for "chance":
            set level 1 to 0.5
            set level 2 to 0.6
            set level 3 to 0.7
            set level 4 to 0.8
            set level 5 to 1

        level values for "xp":
            set level 1 to 750
            set level 2 to 1000
            set level 3 to 1500
            set level 4 to 2000
            set level 5 to 3000

        level values for "xp cost":
            set level 2 to 35_000
            set level 3 to 225_000
            set level 4 to 500_000
            set level 5 to 900_000

        level values for "money cost":
            set level 2 to 50_000
            set level 3 to 275_000
            set level 4 to 700_000
            set level 5 to 1_000_000

local function getDescription(level: integer) :: string:
    return "gain %"xp" of {_level} for "experienced"% experience"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    play sound "minecraft:entity.experience_orb.pickup" with volume 0.5 and pitch 1 at location of {_player}
    add "xp" of {_level} for "experienced" to {_player}'s experience
    add "xp" of {_level} for "experienced" to {xp source::%{_player}%::experienced enchantment}
