on load:
    create pickaxe enchantment named "feeding":
        set enchantment display to "&f<sprite:items:item/cooked_beef> &fFeeding"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to cooked beef

        level values for "chance":
            set level 1 to 5
            set level 2 to 10
            set level 3 to 15
            set level 4 to 20
            set level 5 to 25

        level values for "feed":
            set level 1 to 1
            set level 2 to 2
            set level 3 to 3
            set level 4 to 4
            set level 5 to 5

        level values for "xp cost":
            set level 2 to 40_000
            set level 3 to 100_000
            set level 4 to 250_000
            set level 5 to 500_000

        level values for "money cost":
            set level 2 to 60_000
            set level 3 to 125_000
            set level 4 to 300_000
            set level 5 to 600_000

local function getDescription(level: integer) :: string:
    set {_feed} to "feed" of {_level} for "feeding"
    return "feed you by %{_feed}% food"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_dif} to difference between {-combat tag::%{_player}%} and now
    {_dif} isn't less than {-combat log time}
    set {_feed} to "feed" of {_level} for "feeding"
    set {_player}'s food level to clamp({_player}'s food level + {_feed}, 0, 15)
