on load:
    setting("feeding", "display", value: "&f<sprite:items:item/cooked_beef> &fFeeding")
    setting("feeding", "max level", value: 5)
    setting("feeding", "priority", value: 0)
    setting("feeding", "type", value: "pickaxe")
    setting("feeding", "item", value: cooked beef)
    
    setting("feeding", "chance", l1: 5, l2: 10, l3: 15, l4: 20, l5: 25)

    setting("feeding", "feed", l1: 1, l2: 2, l3: 3, l4: 4, l5: 5)

    setting("feeding", "xp cost", l2: 40_000, l3: 100_000, l4: 250_000, l5: 500_000)
    setting("feeding", "money cost", l2: 60_000, l3: 125_000, l4: 300_000, l5: 600_000)

local function getDescription(level: integer) :: string:
    return "feed you by %get_setting("feeding", "feed", {_level})% food"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_dif} to difference between {-combat tag::%{_player}%} and now
    {_dif} isn't less than {-combat log time}
    set {_player}'s food level to clamp({_player}'s food level + get_setting("feeding", "feed", {_level}), 0, 15)