pickaxe enchantment:
    id: "feeding"
    display: "&f<sprite:items:item/cooked_beef> &fFeeding"
    max level: 5
    priority: 0
    item: cooked beef
    cost: "cheap"

    > "chance":
        lvl. 1: 5%
        lvl. 2: 10%
        lvl. 3: 15%
        lvl. 4: 20%
        lvl. 5: 25%

    > "feed":
        lvl. 1: 1
        lvl. 2: 2
        lvl. 3: 3
        lvl. 4: 4
        lvl. 5: 5

local function getDescription(level: integer) :: string:
    set {_feed} to "feed" of "feeding" at {_level}
    return "feed you by &f%{-effect::saturation::display}%%{_feed}%"

local function onBreak(player: player, level: integer, block: block):
    set {_dif} to difference between {-combat tag::%{_player}%} and now
    {_dif} isn't less than {-combat log time}
    set {_feed} to "feed" of "feeding" at {_level}
    set {_player}'s food level to clamp({_player}'s food level + {_feed}, 0, 15)