on load:
    create pickaxe enchantment named "flight":
        set enchantment display to "&f<sprite:items:item/elytra> &dFlight"
        set enchantment max level to 1
        set enchantment priority to 10
        set enchantment item to elytra

local function getDescription(level: integer) :: string:
    return "enables flight while mining"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_dif} to difference between {-combat tag::%{_player}%} and now
    {_dif} isn't less than {-combat log time}
    if {-fly loop::%{_player}%} is not set:
        set {-fly loop::%{_player}%} to true
        while {-fly loop::%{_player}%} is true:
            wait 1 tick
            set {_dif} to difference between {-combat tag::%{_player}%} and now
            if {_dif} < {-combat log time}:
                set {-fly loop::%{_player}%} to false
                if {_player}'s game mode isn't creative:
                    set {_player}'s flight mode to false
                reset {_player}'s block break speed attribute
                delete {-fly loop::%{_player}%}

            if {_player} is within bound with id "mine flight":
                set {_player}'s flight mode to true
                if {_player} is flying:
                    set {_player}'s block break speed attribute to 5
                else:
                    reset {_player}'s block break speed attribute
            else:
                set {-fly loop::%{_player}%} to false
                if {_player}'s game mode isn't creative:
                    set {_player}'s flight mode to false
                reset {_player}'s block break speed attribute
                delete {-fly loop::%{_player}%}
