on load:
    create pickaxe enchantment named "grinder":
        set enchantment display to "&f<sprite:blocks:block/grindstone_side> &cGrinder"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to grindstone

        level values for "requirement":
            set level 1 to 100
            set level 2 to 90
            set level 3 to 85
            set level 4 to 80
            set level 5 to 75

        level values for "boost":
            set level 1 to 0.001
            set level 2 to 0.0015
            set level 3 to 0.002
            set level 4 to 0.0025
            set level 5 to 0.003

        level values for "xp cost":
            set level 2 to 60_000
            set level 3 to 160_000
            set level 4 to 500_000
            set level 5 to 1_250_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 225_000
            set level 4 to 750_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_boost} to "boost" of "grinder" at {_level}
    set {_requirement} to "requirement" of "grinder" at {_level}
    return "boost luck by &f%formatNumber({_boost}, "#.#####")%x &7every &f%{_requirement}% &7blocks"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    {_player} is within bound with id "mine flight"
    set {_boost} to "boost" of "grinder" at {_level}
    set {_requirement} to "requirement" of "grinder" at {_level}

    startGrinderWatcher({_player})
    

    add 1 to {-grinder blocks::%{_player}%}

    if {-grinder blocks::%{_player}%} >= {_requirement}:
        remove {_requirement} from {-grinder blocks::%{_player}%}
        if {-grinder mining luck::%{_player}%} isn't greater than or equal to 0.5:
            add {_boost} to {-grinder mining luck::%{_player}%}
            add {_boost} to {-mining luck::%{_player}%}
        send action bar "Grinder boost: +%formatNumber({-grinder mining luck::%{_player}%}, "#.#####")%x | Total proc rate: %formatNumber(1 + {-mining luck::%{_player}%}, "#.#####")%x" to {_player}

local function startGrinderWatcher(player: player):
    {-grinder watcher::%{_player}%} isn't set

    set {-grinder watcher::%{_player}%} to true

    wait 1 tick
    while {_player} is within bound with id "mine flight":
        wait 1 tick

    remove {-grinder mining luck::%{_player}%} from {-mining luck::%{_player}%}
    delete {-grinder mining luck::%{_player}%}
    delete {-grinder blocks::%{_player}%}
    delete {-grinder watcher::%{_player}%}
