pickaxe enchantment:
    id: "grinder"
    display: "&f<sprite:blocks:block/grindstone_side> &cGrinder"
    max level: 5
    priority: 10
    item: grindstone
    cost: "normal"

    > "requirement":
        lvl. 1: 100
        lvl. 2: 90
        lvl. 3: 85
        lvl. 4: 80
        lvl. 5: 75

    > "boost":
        lvl. 1: 0.001%
        lvl. 2: 0.0015%
        lvl. 3: 0.002%
        lvl. 4: 0.0025%
        lvl. 5: 0.003%

local function getDescription(level: integer) :: string:
    set {_boost} to "boost" of "grinder" at {_level}
    set {_requirement} to "requirement" of "grinder" at {_level}
    return "boost luck by &f%formatNumber({_boost} * 100, "#.#####")%x &7every &f%{_requirement}% &7blocks"

local function onBreak(player: player, level: integer, block: block):
    {_player} is within bound with id "mine flight"
    set {_boost} to ("boost" of "grinder" at {_level}) * 100
    set {_requirement} to "requirement" of "grinder" at {_level}

    startGrinderWatcher({_player})

    add 1 to {-grinder blocks::%{_player}%}

    if {-grinder blocks::%{_player}%} >= {_requirement}:
        remove {_requirement} from {-grinder blocks::%{_player}%}
        if {-grinder mining luck::%{_player}%} isn't greater than or equal to 0.5:
            add {_boost} to {-grinder mining luck::%{_player}%}
            add {_boost} to {-mining luck::%{_player}%}
        send action bar "Grinder boost: +%formatNumber({-grinder mining luck::%{_player}%}, "#.#####")%x | Total proc rate: %formatNumber(1 + {-mining luck::%{_player}%}, "#.#####")%x" to {_player}

local function startGrinderWatcher(player: player):
    {-grinder watcher::%{_player}%} isn't set

    set {-grinder watcher::%{_player}%} to true

    wait 1 tick
    while {_player} is within bound with id "mine flight":
        wait 1 tick

    remove {-grinder mining luck::%{_player}%} from {-mining luck::%{_player}%}
    delete {-grinder mining luck::%{_player}%}
    delete {-grinder blocks::%{_player}%}
    delete {-grinder watcher::%{_player}%}