on load:
    create pickaxe enchantment named "haste":
        set enchantment display to "&f<sprite:items:item/sugar> &6Haste"
        set enchantment max level to 4
        set enchantment priority to 0
        set enchantment item to sugar

        level values for "chance":
            set level 1 to 4
            set level 2 to 8
            set level 3 to 10
            set level 4 to 12

        level values for "haste":
            set level 1 to potion effect of haste 1 for 5 seconds
            set level 2 to potion effect of haste 2 for 5 seconds
            set level 3 to potion effect of haste 3 for 5 seconds
            set level 4 to potion effect of haste 4 for 5 seconds
            set level 5 to potion effect of haste 5 for 5 seconds

        level values for "speed":
            set level 1 to potion effect of speed 1 for 5 seconds
            set level 2 to potion effect of speed 2 for 5 seconds
            set level 3 to potion effect of speed 3 for 5 seconds
            set level 4 to potion effect of speed 4 for 5 seconds
            set level 5 to potion effect of speed 5 for 5 seconds

        level values for "dust cost":
            set level 2 to 90
            set level 3 to 450
            set level 4 to 900

        level values for "money cost":
            set level 2 to 140_000
            set level 3 to 500_000
            set level 4 to 1_000_000

local function getDescription(level: integer) :: string:
    set {_speed} to "speed" of "haste" at {_level}
    set {_haste} to "haste" of "haste" at {_level}
    return "apply &f%effectDisplay({_speed})% &7and &f%effectDisplay({_haste})%"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_dif} to difference between {-combat tag::%{_player}%} and now
    {_dif} isn't less than {-combat log time}
    set {_haste} to "haste" of "haste" at {_level}
    set {_speed} to "speed" of "haste" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.generic.drink", 0.5, 1, location of {_player}, all players, {_player})
    add {_haste} to {_player}'s potion effects
    add {_speed} to {_player}'s potion effects