pickaxe enchantment:
    id: "haste"
    display: "&f<sprite:items:item/sugar> &6Haste"
    max level: 4
    priority: 0
    item: sugar
    cost: "normal"

    > "chance":
        lvl. 1: 4
        lvl. 2: 8
        lvl. 3: 10
        lvl. 4: 12

    > "haste":
        lvl. 1: potion effect of haste 1 for 5 seconds
        lvl. 2: potion effect of haste 2 for 5 seconds
        lvl. 3: potion effect of haste 3 for 5 seconds
        lvl. 4: potion effect of haste 4 for 5 seconds
        lvl. 5: potion effect of haste 5 for 5 seconds

    > "speed":
        lvl. 1: potion effect of speed 1 for 5 seconds
        lvl. 2: potion effect of speed 2 for 5 seconds
        lvl. 3: potion effect of speed 3 for 5 seconds
        lvl. 4: potion effect of speed 4 for 5 seconds
        lvl. 5: potion effect of speed 5 for 5 seconds

local function getDescription(level: integer) :: string:
    set {_speed} to "speed" of "haste" at {_level}
    set {_haste} to "haste" of "haste" at {_level}
    return "apply &f%effectDisplay({_speed})% &7and &f%effectDisplay({_haste})%"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_dif} to difference between {-combat tag::%{_player}%} and now
    {_dif} isn't less than {-combat log time}
    set {_haste} to "haste" of "haste" at {_level}
    set {_speed} to "speed" of "haste" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.generic.drink", 0.5, 1, location of {_player}, all players, {_player})
    add {_haste} to {_player}'s potion effects
    add {_speed} to {_player}'s potion effects