on load:
    create pickaxe enchantment named "ice":
        set enchantment display to "&f<sprite:blocks:block/ice> &bIce"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to packed ice

        level values for "chance":
            set level 1 to 1
            set level 2 to 1.15
            set level 3 to 1.25
            set level 4 to 1.35
            set level 5 to 1.5

        level values for "radius":
            set level 1 to 1.5
            set level 2 to 1.65
            set level 3 to 1.75
            set level 4 to 1.85
            set level 5 to 2.2

        level values for "dust cost":
            set level 2 to 45
            set level 3 to 200
            set level 4 to 2_800
            set level 5 to 6_000

        level values for "money cost":
            set level 2 to 50_000
            set level 3 to 250_000
            set level 4 to 1_200_000
            set level 5 to 3_000_000

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "ice" at {_level}
    return "set ice within &f%{_radius}%m"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    type of {_block} isn't packed ice or air
    set {_radius} to "radius" of "ice" at {_level}
    loop all blocks in radius {_radius} around location of {_block}:
        loop-block isn't bedrock, beacon, obsidian, or packed ice
        loop-block is within bound with id "mine"

        set loop-block to packed ice