pickaxe enchantment:
    id: "ice"
    display: "&f<sprite:blocks:block/ice> &bIce"
    max level: 5
    priority: 10
    item: packed ice
    cost: "normal"

    > "chance":
        lvl. 1: 1%
        lvl. 2: 1.15%
        lvl. 3: 1.25%
        lvl. 4: 1.35%
        lvl. 5: 1.5%

    > "radius":
        lvl. 1: 1.5
        lvl. 2: 1.65
        lvl. 3: 1.75
        lvl. 4: 1.85
        lvl. 5: 2.2

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "ice" at {_level}
    return "set ice within &f%{_radius}%m"

local function onBreak(player: player, level: integer, block: block):
    type of {_block} isn't packed ice or air
    set {_radius} to "radius" of "ice" at {_level}
    loop all blocks in radius {_radius} around location of {_block}:
        loop-block isn't bedrock, beacon, obsidian, or packed ice
        loop-block is within bound with id "mine"

        set loop-block to packed ice