using reflection

pickaxe enchantment:
    id: "jackhammer"
    display: "&f<sprite:items:item/netherite_pickaxe> &eJackhammer"
    max level: 5
    priority: 10
    item: netherite pickaxe
    cost: "normal"

    > "chance":
        lvl. 1: 10%
        lvl. 2: 13%
        lvl. 3: 15%
        lvl. 4: 15%
        lvl. 5: 15%

    > "width":
        lvl. 1: 4
        lvl. 2: 5
        lvl. 3: 6
        lvl. 4: 7
        lvl. 5: 8

    > "height":
        lvl. 1: 1
        lvl. 2: 1
        lvl. 3: 2
        lvl. 4: 2
        lvl. 5: 3

local function getDescription(level: integer) :: string:
    set {_width} to "width" of "jackhammer" at {_level}
    set {_height} to "height" of "jackhammer" at {_level}
    return "mine &f%{_width}%&7x&f%{_width}%&7x&f%{_height}% &7area"

local function onBreak(player: player, level: integer, block: block):
    {_block} is within bound with id "mine"
    set {_width} to "width" of "jackhammer" at {_level}
    set {_height} to "height" of "jackhammer" at {_level}

    playEnchantmentSound("mining", "minecraft:block.anvil.land", 0.5, 1, location of {_block}, all players, {_player})

    set {_centerX} to x-coordinate of {_block}
    set {_centerY} to y-coordinate of {_block}
    set {_centerZ} to z-coordinate of {_block}
    set {_world} to world of {_block}

    set {_left} to floor(({_width} - 1) / 2)
    set {_right} to ceil(({_width} - 1) / 2)

    set {_minX} to {_centerX} - {_left}
    set {_maxX} to {_centerX} + {_right}
    set {_minZ} to {_centerZ} - {_left}
    set {_maxZ} to {_centerZ} + {_right}
    set {_maxY} to {_centerY} + ({_height} - 1)

    loop all numbers between {_centerY} and {_maxY}:
        set {_y} to loop-value
        wait 3 ticks
        loop all numbers between {_minX} and {_maxX}:
            set {_x} to loop-value-2
            loop all numbers between {_minZ} and {_maxZ}:
                set {_z} to loop-value-3
                set {_b} to block at location({_x}, {_y}, {_z}, {_world})

                {_b} is within bound with id "mine"
                {_b} isn't air, bedrock, beacon, obsidian, packed ice, or black concrete

                blockReward({_player}, {_tool}, {_b}, "jackhammer enchantment")
                
                set block within {_b} to air