using reflection

on load:
    create pickaxe enchantment named "jackhammer":
        set enchantment display to "&f<sprite:items:item/netherite_pickaxe> &eJackhammer"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to netherite pickaxe

        level values for "chance":
            set level 1 to 10
            set level 2 to 13
            set level 3 to 15
            set level 4 to 15
            set level 5 to 15

        level values for "width":
            set level 1 to 4
            set level 2 to 5
            set level 3 to 6
            set level 4 to 7
            set level 5 to 8

        level values for "height":
            set level 1 to 1
            set level 2 to 1
            set level 3 to 2
            set level 4 to 2
            set level 5 to 3

        level values for "xp cost":
            set level 2 to 40_000
            set level 3 to 200_000
            set level 4 to 600_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 50_000
            set level 3 to 300_000
            set level 4 to 750_000
            set level 5 to 1_300_000

local function getDescription(level: integer) :: string:
    set {_width} to "width" of {_level} for "jackhammer"
    set {_height} to "height" of {_level} for "jackhammer"
    return "mine &f%{_width}%&7x&f%{_width}%&7x&f%{_height}% &7area"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    {_block} is within bound with id "mine"
    set {_width} to "width" of {_level} for "jackhammer"
    set {_height} to "height" of {_level} for "jackhammer"

    playEnchantmentSound("mining", "minecraft:block.anvil.land", 0.5, 1, location of {_block}, all players, {_player})

    set {_centerX} to x-coordinate of {_block}
    set {_centerY} to y-coordinate of {_block}
    set {_centerZ} to z-coordinate of {_block}
    set {_world} to world of {_block}

    set {_left} to floor(({_width} - 1) / 2)
    set {_right} to ceil(({_width} - 1) / 2)

    set {_minX} to {_centerX} - {_left}
    set {_maxX} to {_centerX} + {_right}
    set {_minZ} to {_centerZ} - {_left}
    set {_maxZ} to {_centerZ} + {_right}
    set {_maxY} to {_centerY} + ({_height} - 1)

    loop all numbers between {_centerY} and {_maxY}:
        set {_y} to loop-value
        wait 3 ticks
        loop all numbers between {_minX} and {_maxX}:
            set {_x} to loop-value-2
            loop all numbers between {_minZ} and {_maxZ}:
                set {_z} to loop-value-3
                set {_b} to block at location({_x}, {_y}, {_z}, {_world})

                {_b} is within bound with id "mine"
                {_b} isn't air, bedrock, beacon, obsidian, packed ice, or black concrete

                blockReward({_player}, {_tool}, {_b}, "jackhammer enchantment")
                
                set block within {_b} to air
