on load:
    create pickaxe enchantment named "jackpot":
        set enchantment display to "&f<sprite:items:item/gold_ingot> &6Jackpot"
        set enchantment max level to 3
        set enchantment priority to 0
        set enchantment item to gold ingot

        level values for "chance":
            set level 1 to 0.01
            set level 2 to 0.02
            set level 3 to 0.04

        level values for "xp":
            set level 1 to 50_000
            set level 2 to 50_000
            set level 3 to 50_000

        level values for "xp cost":
            set level 2 to 250_000
            set level 3 to 1_000_000

        level values for "money cost":
            set level 2 to 400_000
            set level 3 to 1_200_000

local function getDescription(level: integer) :: string:
    return "gain a large amount of money and xp"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_xp} to "xp" of "jackpot" at {_level}
    set {_money} to {-jackpot money}

    add {_xp} to {_player}'s experience
    add {_money} to {money::%{_player}%}

    playEnchantmentSound("mining", "minecraft:ui.toast.challenge_complete", 1, 1, location of {_player}, all players, {_player})
    send "&6&lJACKPOT!" to {_player}
    send "&a+%formatNumber({_money})% money" to {_player}
    send "&b+%formatNumber({_xp})% xp" to {_player}

on load:
    getJackpotAmount()

async every 10 minutes:
    getJackpotAmount()

function getJackpotAmount():
    set {-jackpot money} to 50_000
    #async run 0 seconds later:
     #   set {-jackpot money} to 50_000 + (mean({money::*}) / 10) 
