pickaxe enchantment:
    id: "jackpot"
    display: "&f<sprite:items:item/gold_ingot> &6Jackpot"
    max level: 3
    priority: 0
    item: gold ingot
    cost: "normal"

    > "chance":
        lvl. 1: 0.01%
        lvl. 2: 0.02%
        lvl. 3: 0.04%

    > "money":
        lvl. 1: 100_000
        lvl. 2: 300_000
        lvl. 3: 600_000

    > "dust":
        lvl. 1: 250
        lvl. 2: 300
        lvl. 3: 350

    > "scale per level":
        lvl. 1: 1%
        lvl. 2: 1.5%
        lvl. 3: 2%

local function getDescription(level: integer) :: string:
    set {_dust} to "dust" of "jackpot" at {_level}
    set {_money} to "money" of "jackpot" at {_level}
    set {_scale} to "scale per level" of "jackpot" at {_level}
    return "gain &f$%kNumber({_money})% &7and &f%{-dust sprite}%%{_dust}%&8, &7scales by &f%{_scale} * 100%%% &7per player level"

local function onBreak(player: player, level: integer, block: block):
    set {_dust} to "dust" of "jackpot" at {_level}
    set {_money} to "money" of "jackpot" at {_level}
    set {_scale} to "scale per level" of "jackpot" at {_level}

    set {_dust} to {_dust} * (1 + {_scale} * {level::%{_player}%})
    set {_money} to {_money} * (1 + {_scale} * {level::%{_player}%})

    add {_dust} to {dust::%{_player}%}
    add {_money} to {money::%{_player}%}

    playEnchantmentSound("mining", "minecraft:ui.toast.challenge_complete", 1, 1, location of {_player}, all players, {_player})
    send "&6&lJACKPOT!" to {_player}
    send "&a+$%formatNumber({_money})%" to {_player}
    send formatted "&f+%{-dust sprite}%%formatNumber({_dust})%" to {_player}