on load:
    create pickaxe enchantment named "lightning":
        set enchantment display to "&f<sprite:items:item/trident> &9Lightning"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to 1 of trident

        level values for "chance":
            set level 1 to 10
            set level 2 to 15
            set level 3 to 20
            set level 4 to 25
            set level 5 to 30

        level values for "blocks":
            set level 1 to 5
            set level 2 to 6
            set level 3 to 7
            set level 4 to 8
            set level 5 to 9

        level values for "xp cost":
            set level 2 to 80_000
            set level 3 to 200_000
            set level 4 to 600_000
            set level 5 to 1_250_000

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 800_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_blocks} to "blocks" of {_level} for "lightning"
    return "break %{_blocks}% blocks below"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_blocks} to "blocks" of {_level} for "lightning"
    set {_y} to (y coordinate of {_block}) - ({_blocks} + 4)
    strike lightning effect at location of {_block}
    loop all blocks below location of {_block} where [y coordinate of input >= {_y}]:
        if any:
            loop-block is obsidian
            loop-block is bedrock
        then:
            stop loop
            
        blockReward({_player}, {_player}'s tool, loop-block, "lightning enchantment")

        set loop-block to air
