pickaxe enchantment:
    id: "lucky"
    display: "&f<sprite:items:item/trial_key> &fLucky"
    max level: 5
    priority: 1000
    item: trial key
    cost: "normal"

    > "chance":
        lvl. 1: 1%
        lvl. 2: 1.25%
        lvl. 3: 1.75%
        lvl. 4: 2%
        lvl. 5: 3%

    > "boost":
        lvl. 1: 20%
        lvl. 2: 22.5%
        lvl. 3: 25%
        lvl. 4: 27%
        lvl. 5: 30%

    > "duration":
        lvl. 1: 5 seconds
        lvl. 2: 5.5 seconds
        lvl. 3: 6 seconds
        lvl. 4: 6.5 seconds
        lvl. 5: 7 seconds

local function getDescription(level: integer) :: string:
    set {_boost} to "boost" of "lucky" at {_level}
    set {_duration} to "duration" of "lucky" at {_level}
    return "gain &f%{_boost} * 100%%% &7luck for &f%timeFormat({_duration})%"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    {-mining luck boost::%{_player}%} isn't set
    set {_boost} to "boost" of "lucky" at {_level}
    set {_duration} to "duration" of "lucky" at {_level}
    set {-mining luck boost::%{_player}%} to true
    add {_boost} to {-mining luck::%{_player}%}
    playEnchantmentSound("mining", "minecraft:block.amethyst_block.resonate", 1, 1, location of {_player}, all players, {_player})
    wait {_duration}
    delete {-mining luck boost::%{_player}%}
    remove {_boost} from {-mining luck::%{_player}%}