pickaxe enchantment:
    id: "money_boost"
    display: "&f<sprite:items:item/emerald> &2Money Boost"
    max level: 10
    priority: 0
    item: emerald
    cost: "expensive"

    > "chance":
        lvl. 1: 10
        lvl. 2: 15
        lvl. 3: 20
        lvl. 4: 25
        lvl. 5: 30
        lvl. 6: 35
        lvl. 7: 40
        lvl. 8: 45
        lvl. 9: 50
        lvl. 10: 70

    > "reward":
        lvl. 1: 20
        lvl. 2: 25
        lvl. 3: 30
        lvl. 4: 35
        lvl. 5: 40
        lvl. 6: 45
        lvl. 7: 50
        lvl. 8: 55
        lvl. 9: 60
        lvl. 10: 70

local function getDescription(level: integer) :: string:
    set {_reward} to "reward" of "money_boost" at {_level}
    return "gain &f$%{_reward}%"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_reward} to "reward" of "money_boost" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.villager.celebrate", 0.1, 1, location of {_player}, all players, {_player})
    add {_reward} to {money::%{_player}%}