on load:
    create pickaxe enchantment named "money_boost":
        set enchantment display to "&f<sprite:items:item/emerald> &2Money Boost"
        set enchantment max level to 10
        set enchantment priority to 0
        set enchantment item to emerald

        level values for "chance":
            set level 1 to 10
            set level 2 to 15
            set level 3 to 20
            set level 4 to 25
            set level 5 to 30
            set level 6 to 35
            set level 7 to 40
            set level 8 to 45
            set level 9 to 50
            set level 10 to 70

        level values for "reward":
            set level 1 to 20
            set level 2 to 25
            set level 3 to 30
            set level 4 to 35
            set level 5 to 40
            set level 6 to 45
            set level 7 to 50
            set level 8 to 55
            set level 9 to 60
            set level 10 to 70

        level values for "dust cost":
            set level 2 to 5
            set level 3 to 20
            set level 4 to 70
            set level 5 to 275
            set level 6 to 550
            set level 7 to 850
            set level 8 to 1_100
            set level 9 to 8_300
            set level 10 to 12_000

        level values for "money cost":
            set level 2 to 6_000
            set level 3 to 24_000
            set level 4 to 96_000
            set level 5 to 384_000
            set level 6 to 768_000
            set level 7 to 1_000_000
            set level 8 to 1_500_000
            set level 9 to 4_000_000
            set level 10 to 6_300_000

local function getDescription(level: integer) :: string:
    set {_reward} to "reward" of "money_boost" at {_level}
    return "gain &f$%{_reward}%"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_reward} to "reward" of "money_boost" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.villager.celebrate", 0.1, 1, location of {_player}, all players, {_player})
    add {_reward} to {money::%{_player}%}