on load:
    create pickaxe enchantment named "nuke":
        set enchantment display to "&f<sprite:items:item/end_crystal> &4Nuke"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to dragon head

        level values for "chance":
            set level 1 to 0.05
            set level 2 to 0.075
            set level 3 to 0.1
            set level 4 to 0.125
            set level 5 to 0.175

        level values for "radius":
            set level 1 to 8
            set level 2 to 9
            set level 3 to 10
            set level 4 to 11
            set level 5 to 13

        level values for "xp cost":
            set level 2 to 50_000
            set level 3 to 200_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 60_000
            set level 3 to 275_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "nuke" at {_level}
    return "nuke blocks within &f%{_radius}%m"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_radius} to "radius" of "nuke" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.creeper.primed", 1, 1, location of {_player}, all players, {_player})
    wait 1 second
    playEnchantmentSound("mining", "minecraft:entity.generic.explode", 0.25, 1, location of {_block}, all players, {_player})
    fastRadiusClear({_player}, location of {_block}, {_radius})
