pickaxe enchantment:
    id: "nuke"
    display: "&f<sprite:items:item/end_crystal> &4Nuke"
    max level: 5
    priority: 0
    item: dragon head
    cost: "normal"

    > "chance":
        lvl. 1: 0.05
        lvl. 2: 0.075
        lvl. 3: 0.1
        lvl. 4: 0.125
        lvl. 5: 0.175

    > "radius":
        lvl. 1: 8
        lvl. 2: 9
        lvl. 3: 10
        lvl. 4: 11
        lvl. 5: 13

local function getDescription(level: integer) :: string:
    set {_radius} to "radius" of "nuke" at {_level}
    return "nuke blocks within &f%{_radius}%m"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_radius} to "radius" of "nuke" at {_level}
    playEnchantmentSound("mining", "minecraft:entity.creeper.primed", 1, 1, location of {_player}, all players, {_player})
    wait 1 second
    playEnchantmentSound("mining", "minecraft:entity.generic.explode", 0.25, 1, location of {_block}, all players, {_player})
    fastRadiusClear({_player}, location of {_block}, {_radius})