pickaxe enchantment:
    id: "reroll"
    display: "&f<sprite:items:item/axolotl_spawn_egg> &1Reroll"
    max level: 5
    priority: 0
    item: axolotl spawn egg
    cost: "expensive"

    > "chance":
        lvl. 1: 3%
        lvl. 2: 6%
        lvl. 3: 9%
        lvl. 4: 12%
        lvl. 5: 18%

local function getDescription(level: integer) :: string:
    return "retry enchantments"

local function onBreak(player: player, level: integer, block: block):
    {-rerolling::%{_player}%} isn't set
    playEnchantmentSound("mining", "minecraft:block.wooden_button.click_on", 0.5, 1, location of {_player}, all players, {_player})
    set {-rerolling::%{_player}%} to true
    miningEnchants({_player}, {_block})
    wait 1 tick
    delete {-rerolling::%{_player}%}