on load:
    create pickaxe enchantment named "reroll":
        set enchantment display to "&f<sprite:items:item/axolotl_spawn_egg> &1Reroll"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to axolotl spawn egg

        level values for "chance":
            set level 1 to 3
            set level 2 to 6
            set level 3 to 9
            set level 4 to 12
            set level 5 to 18

        level values for "dust cost":
            set level 2 to 100
            set level 3 to 325
            set level 4 to 4_500
            set level 5 to 11_000

        level values for "money cost":
            set level 2 to 150_000
            set level 3 to 400_000
            set level 4 to 2_000_000
            set level 5 to 5_000_000

local function getDescription(level: integer) :: string:
    return "retry enchantments"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    {-rerolling::%{_player}%} isn't set
    playEnchantmentSound("mining", "minecraft:block.wooden_button.click_on", 0.5, 1, location of {_player}, all players, {_player})
    set {-rerolling::%{_player}%} to true
    miningEnchants({_player}, {_block})
    wait 1 tick
    delete {-rerolling::%{_player}%}