on load:
    setting("super_fortune", "display", value: "&f<sprite:items:item/torchflower_seeds> &3Super Fortune")
    setting("super_fortune", "max", value: 5)
    setting("super_fortune", "priority", value: 1000)
    setting("super_fortune", "type", value: "pickaxe")
    setting("super_fortune", "item", value: torchflower seeds)

    setting("super_fortune", "chance", l1: 1, l2: 2, l3: 3, l4: 4, l5: 5)
    
    setting("super_fortune", "multiplier", l1: 20, l2: 40, l3: 60, l4: 80, l5: 100)

    setting("super_fortune", "xp cost", l2: 80_000, l3: 200_000, l4: 600_000, l5: 1_250_000)
    setting("super_fortune", "money cost", l2: 100_000, l3: 300_000, l4: 800_000, l5: 1_500_000)

local function getDescription(level: integer) :: string:
    return "give %get_setting("super_fortune", "multiplier", {_level})%x more drops"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_drops::*} to drops of {_block type} using {_player}'s tool
    if type of {_block} is packed ice:
        add ((level of fortune on {_tool} + 1) of packed ice) to {_drops::*}
    loop {_drops::*}:
        set item amount of loop-value to item amount of loop-value * get_setting("super_fortune", "multiplier", {_level})
        add {-sell::%type of loop-value%} * item amount of loop-value to {_value}
    
    if {_value} isn't set:
        set {_value} to a random integer between 100 and 1000

    add {_value} to {money::%{_player}%}