pickaxe enchantment:
    id: "super_fortune"
    display: "&f<sprite:items:item/torchflower_seeds> &3Super Fortune"
    max level: 5
    priority: 1000
    item: torchflower seeds
    cost: "normal"

    > "chance":
        lvl. 1: 1%
        lvl. 2: 2%
        lvl. 3: 3%
        lvl. 4: 4%
        lvl. 5: 5%

    > "multiplier":
        lvl. 1: 20
        lvl. 2: 40
        lvl. 3: 60
        lvl. 4: 80
        lvl. 5: 100

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "super_fortune" at {_level}
    return "give &f%{_multiplier}%x &7more drops"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_multiplier} to "multiplier" of "super_fortune" at {_level}
    set {_drops::*} to drops of {_block type} using {_player}'s tool
    if type of {_block} is packed ice:
        add (({-cached enchantments::%{_player}%::pickaxe::vanilla::fortune} + 1) of packed ice) to {_drops::*}
    loop {_drops::*}:
        set item amount of loop-value to item amount of loop-value * {_multiplier}
        add {-sell::%type of loop-value%} * item amount of loop-value to {_value}
    
    if {_value} isn't set:
        set {_value} to a random integer between 100 and 1000

    add {_value} to {money::%{_player}%}