on load:
    create pickaxe enchantment named "super_fortune":
        set enchantment display to "&f<sprite:items:item/torchflower_seeds> &3Super Fortune"
        set enchantment max level to 5
        set enchantment priority to 1000
        set enchantment item to torchflower seeds

        level values for "chance":
            set level 1 to 1
            set level 2 to 2
            set level 3 to 3
            set level 4 to 4
            set level 5 to 5

        level values for "multiplier":
            set level 1 to 20
            set level 2 to 40
            set level 3 to 60
            set level 4 to 80
            set level 5 to 100

        level values for "dust cost":
            set level 2 to 90
            set level 3 to 225
            set level 4 to 650
            set level 5 to 1_400

        level values for "money cost":
            set level 2 to 100_000
            set level 3 to 300_000
            set level 4 to 800_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "super_fortune" at {_level}
    return "give &f%{_multiplier}%x &7more drops"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_multiplier} to "multiplier" of "super_fortune" at {_level}
    set {_drops::*} to drops of {_block type} using {_player}'s tool
    if type of {_block} is packed ice:
        add ((level of fortune on {_tool} + 1) of packed ice) to {_drops::*}
    loop {_drops::*}:
        set item amount of loop-value to item amount of loop-value * {_multiplier}
        add {-sell::%type of loop-value%} * item amount of loop-value to {_value}
    
    if {_value} isn't set:
        set {_value} to a random integer between 100 and 1000

    add {_value} to {money::%{_player}%}