on load:
    setting("xp_boost", "display", value: "&f<sprite:blocks:block/enchanting_table_top> &bXP Boost")
    setting("xp_boost", "max level", value: 10)
    setting("xp_boost", "priority", value: 9999)
    setting("xp_boost", "type", value: "pickaxe")
    setting("xp_boost", "item", value: enchanting table)

    setting("xp_boost", "chance", l1: 20, l2: 25, l3: 30, l4: 35, l5: 40, l6: 45, l7: 50, l8: 55, l9: 60, l10: 75)

    setting("xp_boost", "multiplier", l1: 5, l2: 5.5, l3: 6, l4: 6.5, l5: 7, l6: 7.5, l7: 8, l8: 8.5, l9: 9, l10: 10)

    setting("xp_boost", "xp cost", l2: 1_000, l3: 4_000, l4: 16_000, l5: 64_000, l6: 256_000, l7: 1_000_000, l8: 2_000_000, l9: 3_000_000, l10: 4_000_000)
    setting("xp_boost", "money cost", l2: 1_500, l3: 6_000, l4: 24_000, l5: 96_000, l6: 384_000, l7: 1_250_000, l8: 2_500_000, l9: 3_500_000, l10: 4_500_000)

local function getDescription(level: integer) :: string:
    return "boost xp gain by %get_setting("xp_boost", "multiplier", {_level})%x"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    play sound "minecraft:entity.experience_orb.pickup" with volume 0.5 and pitch 1 at location of {_player}
    set {_xp} to get_setting("xp_boost", "multiplier", {_level}) * xpYield({_block})
    add {_xp} to {_player}'s experience
    wait 1 tick