on load:
    create pickaxe enchantment named "xp_boost":
        set enchantment display to "&f<sprite:blocks:block/enchanting_table_top> &bXP Boost"
        set enchantment max level to 10
        set enchantment priority to 9999
        set enchantment item to enchanting table

        level values for "chance":
            set level 1 to 20
            set level 2 to 25
            set level 3 to 30
            set level 4 to 35
            set level 5 to 40
            set level 6 to 45
            set level 7 to 50
            set level 8 to 55
            set level 9 to 60
            set level 10 to 75

        level values for "multiplier":
            set level 1 to 5
            set level 2 to 5.5
            set level 3 to 6
            set level 4 to 6.5
            set level 5 to 7
            set level 6 to 7.5
            set level 7 to 8
            set level 8 to 8.5
            set level 9 to 9
            set level 10 to 10

        level values for "xp cost":
            set level 2 to 1_000
            set level 3 to 4_000
            set level 4 to 16_000
            set level 5 to 64_000
            set level 6 to 256_000
            set level 7 to 1_000_000
            set level 8 to 2_000_000
            set level 9 to 3_000_000
            set level 10 to 4_000_000

        level values for "money cost":
            set level 2 to 1_500
            set level 3 to 6_000
            set level 4 to 24_000
            set level 5 to 96_000
            set level 6 to 384_000
            set level 7 to 1_250_000
            set level 8 to 2_500_000
            set level 9 to 3_500_000
            set level 10 to 4_500_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "xp_boost" at {_level}
    return "boost xp gain by &f%{_multiplier}%x"

local function onBreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_multiplier} to "multiplier" of "xp_boost" at {_level}
    set {_xp} to {_multiplier} * xpYield({_block})
    add {_xp} to {_player}'s experience
    playEnchantmentSound("mining", "minecraft:entity.experience_orb.pickup", 0.5, 1, location of {_player}, all players, {_player})
