on load:
    setting("acrobat", "display", value: "&f<sprite:items:item/feather> &eAcrobat")
    setting("acrobat", "max", value: 5)
    setting("acrobat", "priority", value: 1)
    setting("acrobat", "type", value: "armor")
    setting("acrobat", "item", value: leather boots)

    setting("acrobat", "damage reduction", l1: 0.20, l2: 0.35, l3: 0.50, l4: 0.60, l5: 0.80)
    
    setting("acrobat", "xp cost", l2: 40_000, l3: 150_000, l4: 400_000, l5: 1_000_000)
    setting("acrobat", "money cost", l2: 60_000, l3: 200_000, l4: 500_000, l5: 1_200_000)

local function getDescription(level: integer) :: string:
    set {_reduction} to get_setting("acrobat", "damage reduction", {_level})
    return "reduces gravity damage by &f%{_reduction} * 100%%%"
    
local function onattacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    if {_damage cause} is fall (damage cause) or flying into a wall:
        set {_reduction} to get_setting("acrobat", "damage reduction", {_level})
        return ({_damage} * {_reduction}) * -1