on load:
    create armor enchantment named "acrobat":
        set enchantment display to "&f<sprite:items:item/feather> &eAcrobat"
        set enchantment max level to 5
        set enchantment priority to 1
        set enchantment item to leather boots

        level values for "damage reduction":
            set level 1 to 0.20
            set level 2 to 0.35
            set level 3 to 0.50
            set level 4 to 0.60
            set level 5 to 0.80

        level values for "xp cost":
            set level 2 to 40_000
            set level 3 to 150_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 60_000
            set level 3 to 200_000
            set level 4 to 500_000
            set level 5 to 1_200_000

local function getDescription(level: integer) :: string:
    set {_reduction} to "damage reduction" of "acrobat" at {_level}
    return "reduces gravity damage by &f%{_reduction} * 100%%%"

local function onattacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    if {_damage cause} is fall (damage cause) or flying into a wall:
        set {_reduction} to "damage reduction" of "acrobat" at {_level}
        return ({_damage} * {_reduction}) * -1
