armor enchantment:
    id: "acrobat"
    display: "&f<sprite:items:item/feather> &eAcrobat"
    max level: 5
    priority: 1
    item: leather boots
    cost: "normal"

    > "damage reduction":
        lvl. 1: 20%
        lvl. 2: 35%
        lvl. 3: 50%
        lvl. 4: 60%
        lvl. 5: 80%

local function getDescription(level: integer) :: string:
    set {_reduction} to "damage reduction" of "acrobat" at {_level}
    return "reduces gravity damage by &f%{_reduction} * 100%%%"

local function onAttacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    if {_damage cause} is fall (damage cause) or flying into a wall:
        set {_reduction} to "damage reduction" of "acrobat" at {_level}
        return ({_damage} * {_reduction}) * -1
