on load:
    create armor enchantment named "armor":
        set enchantment display to "&f<sprite:gui:hud/armor_full> &dArmor"
        set enchantment max level to 5
        set enchantment priority to 1
        set enchantment item to netherite chestplate

        level values for "armor":
            set level 1 to 2
            set level 2 to 5
            set level 3 to 7
            set level 4 to 9
            set level 5 to 12

        level values for "xp cost":
            set level 1 to 5_000
            set level 2 to 16_000
            set level 3 to 100_000
            set level 4 to 500_000
            set level 5 to 1_250_000

        level values for "money cost":
            set level 1 to 6_000
            set level 2 to 18_000
            set level 3 to 150_000
            set level 4 to 750_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_armor} to "armor" of "armor" at {_level}
    return "increases armor by &f%{_armor}%"

local function onapply(armor: item, level: integer, player: player = {_}):
    set {_amount} to "armor" of "armor" at {_level}
    apply attribute modifier to (item within {_armor}):
        attribute: armor
        id: "skript:armor_enchantment"
        slot: head_slot_group
        amount: {_amount}
        operation: add number

local function onunapply(armor: item, level: integer, player: player = {_}):
    remove attribute modifier with key "skript:armor_enchantment" from item within {_armor}
    
