on load:
    setting("armor", "display", value: "&f<sprite:gui:hud/armor_full> &dArmor")
    setting("armor", "max", value: 5)
    setting("armor", "priority", value: 1)
    setting("armor", "type", value: "armor")
    setting("armor", "item", value: netherite chestplate)

    setting("armor", "armor", l1: 2, l2: 5, l3: 7, l4: 9, l5: 12)

    setting("armor", "xp cost", l1: 5_000, l2: 16_000, l3: 100_000, l4: 500_000, l5: 1_250_000)
    setting("armor", "money cost", l1: 6_000, l2: 18_000, l3: 150_000, l4: 750_000, l5: 1_500_000)

local function getDescription(level: integer) :: string:
    set {_armor} to get_setting("armor", "armor", {_level})
    return "increases armor by &f%{_armor}%"
    
local function onapply(armor: item, level: integer, player: player = {_}):
    set {_amount} to get_setting("armor", "armor", {_level})
    apply attribute modifier to (item within {_armor}):
        attribute: armor
        id: "skript:armor_enchantment"
        slot: head_slot_group
        amount: {_amount}
        operation: add number

local function onunapply(armor: item, level: integer, player: player = {_}):
    remove attribute modifier with key "skript:armor_enchantment" from item within {_armor}
    