armor enchantment:
    id: "armor"
    display: "&f<sprite:gui:hud/armor_full> &dArmor"
    max level: 5
    priority: 1
    item: netherite chestplate
    cost: "normal"

    > "armor":
        lvl. 1: 2
        lvl. 2: 5
        lvl. 3: 7
        lvl. 4: 9
        lvl. 5: 12

local function getDescription(level: integer) :: string:
    set {_armor} to "armor" of "armor" at {_level}
    return "increases armor by &f%{_armor}%"

local function onApply(armor: item, level: integer, player: player = {_}):
    set {_amount} to "armor" of "armor" at {_level}
    apply attribute modifier to (item within {_armor}):
        attribute: armor
        id: "skript:armor_enchantment"
        slot: head_slot_group
        amount: {_amount}
        operation: add number

local function onUnapply(armor: item, level: integer, player: player = {_}):
    remove attribute modifier with key "skript:armor_enchantment" from item within {_armor}
    