armor enchantment:
    id: "cleanse"
    display: "&f<sprite:items:item/milk_bucket> &fCleanse"
    max level: 5
    priority: 1
    item: milk bucket
    cost: "normal"

    > "effect reduction":
        lvl. 1: 10%
        lvl. 2: 15%
        lvl. 3: 20%
        lvl. 4: 25%
        lvl. 5: 35%

    set {-negative effects::*} to poison, blindness, wither, nausea, slowness, weakness, levitation, hunger, bad omen, darkness, mining fatigue

local function getDescription(level: integer) :: string:
    set {_reduction} to "effect reduction" of "cleanse" at {_level}
    return "passively and on kill&8, &7reduce most negative effect durations by &f%{_reduction} * 100%%%" 

local function onKill(attacker: entity, armor: item, level: integer, victim: entity):
    set {_reduction} to "effect reduction" of "cleanse" at {_level}

    for {_effect} in active potion effects of {_attacker}:
        set {_type} to type of {_effect}
        {-negative effects::*} contains {_type}
        set {-%{_attacker}%::reducing::%{_type}%} to true
        set {_removed} to duration of {_effect} * {_reduction}
        remove {_removed} from duration of {_attacker}'s {_type} effect
        wait 1 tick
        delete {-%{_attacker}%::reducing::%{_type}%}

on combust:
    set {_level} to {-cached enchantments::%entity%::helmet::cleanse}
    {_level} is set

    set {_reduction} to "effect reduction" of "cleanse" at {_level}
    set {_remove} to entity's burning time * {_reduction}
    wait 1 tick
    remove {_remove} from entity's burning time
    
on entity potion effect added or changed:
    {-negative effects::*} contains event-potioneffecttype
    {-%entity%::reducing::%event-potioneffecttype%} is not set

    set {_level} to {-cached enchantments::%entity%::helmet::cleanse}
    {_level} is set

    cancel event

    set {_entity} to entity
    set {_type} to event-potioneffecttype
    set {_tier} to amplifier of event-potioneffect
    set {_duration} to duration of event-potioneffect

    set {_reduction} to "effect reduction" of "cleanse" at {_level}
    set {_removed} to {_duration} * {_reduction}

    remove {_removed} from {_duration}
    set {_newEffect} to potion effect of {_type} of tier {_tier} for {_duration}

    set {-%{_entity}%::reducing::%{_type}%} to true
    apply {_newEffect} to {_entity}

    wait 1 tick
    delete {-%{_entity}%::reducing::%{_type}%}
    