on load:
    create armor enchantment named "dodge":
        set enchantment display to "&f<sprite:items:item/rabbit_foot> Dodge"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to rabbit foot

        level values for "chance":
            set level 1 to 0.5
            set level 2 to 0.75
            set level 3 to 1.0
            set level 4 to 1.25
            set level 5 to 1.75

        level values for "speed":
            set level 1 to potion effect of speed 1 for 3 seconds
            set level 2 to potion effect of speed 1 for 4 seconds
            set level 3 to potion effect of speed 2 for 4 seconds
            set level 4 to potion effect of speed 2 for 4 seconds
            set level 5 to potion effect of speed 2 for 5 seconds

        level values for "xp cost":
            set level 2 to 25_000
            set level 3 to 200_000
            set level 4 to 500_000
            set level 5 to 1_250_000

        level values for "money cost":
            set level 2 to 35_000
            set level 3 to 250_000
            set level 4 to 600_000
            set level 5 to 1_500_000

local function getDescription(level: integer) :: string:
    set {_effect} to "speed" of {_level} for "dodge"
    return "take no damage&8, &7gain &f%effectDisplay({_effect})%"

local function onattacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    set {_effect} to "speed" of {_level} for "dodge"
    apply {_effect} to {_victim}
    play sound "minecraft:item.totem.use" with volume 0.2 and pitch 1 at {_victim}
    play (100 totem of undying item particles) with particle speed of 0.2 at {_victim}'s head
    return -1000
