armor enchantment:
    id: "dodge"
    display: "&f<sprite:items:item/rabbit_foot> Dodge"
    max level: 5
    priority: 0
    item: rabbit foot
    cost: "normal"

    > "chance":
        lvl. 1: 0.5%
        lvl. 2: 0.75%
        lvl. 3: 1.0%
        lvl. 4: 1.25%
        lvl. 5: 1.75%

    > "speed":
        lvl. 1: potion effect of speed 1 for 3 seconds
        lvl. 2: potion effect of speed 1 for 4 seconds
        lvl. 3: potion effect of speed 2 for 4 seconds
        lvl. 4: potion effect of speed 2 for 4 seconds
        lvl. 5: potion effect of speed 2 for 5 seconds

local function getDescription(level: integer) :: string:
    set {_effect} to "speed" of "dodge" at {_level}
    return "take no damage&8, &7gain &f%effectDisplay({_effect})%"

local function onAttacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    set {_effect} to "speed" of "dodge" at {_level}
    apply {_effect} to {_victim}
    playEnchantmentSound("combat", "minecraft:item.totem.use", 0.2, 1, location of {_victim}, all players)
    play (100 totem of undying item particles) with particle speed of 0.2 at ({_victim}'s head)
    return -1000
    