on load:
    create armor enchantment named "last_stand":
        set enchantment display to "&f<sprite:items:item/iron_chestplate> &eLast Stand"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to iron chestplate

        level values for "speed":
            set level 1 to potion effect of speed 1 for 1 second
            set level 2 to potion effect of speed 1 for 1 second
            set level 3 to potion effect of speed 2 for 1 second
            set level 4 to potion effect of speed 2 for 1 second
            set level 5 to potion effect of speed 3 for 1 second

        level values for "strength":
            set level 1 to potion effect of strength 1 for 1 second
            set level 2 to potion effect of strength 1 for 1 second
            set level 3 to potion effect of strength 1 for 1 second
            set level 4 to potion effect of strength 1 for 1 second
            set level 5 to potion effect of strength 2 for 1 second

        level values for "resistance":
            set level 1 to potion effect of resistance 1 for 1 second
            set level 2 to potion effect of resistance 1 for 1 second
            set level 3 to potion effect of resistance 1 for 1 second
            set level 4 to potion effect of resistance 1 for 1 second
            set level 5 to potion effect of resistance 1 for 1 second

        level values for "health threshold":
            set level 1 to 2
            set level 2 to 2.4
            set level 3 to 2.9
            set level 4 to 3.2
            set level 5 to 3.6

        level values for "dust cost":
            set level 2 to 45
            set level 3 to 175
            set level 4 to 450
            set level 5 to 1_100

        level values for "money cost":
            set level 2 to 60_000
            set level 3 to 200_000
            set level 4 to 500_000
            set level 5 to 1_200_000

local function getDescription(level: integer) :: string:
    set {_speed} to "speed" of "last_stand" at {_level}
    set {_strength} to "strength" of "last_stand" at {_level}
    set {_resistance} to "resistance" of "last_stand" at {_level}
    set {_health threshold} to "health threshold" of "last_stand" at {_level}

    return "when below &f%{_health threshold}%<sprite:gui:hud/heart/full>&8, &7gain &f%effectDisplay({_speed})%&8, &f%effectDisplay({_strength})%&8, &f%effectDisplay({_resistance})%"

local function onAttacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    wait 1 tick
    set {_health threshold} to "health threshold" of "last_stand" at {_level}
    if {_victim}'s health < {_health threshold}:
        set {_speed} to "speed" of "last_stand" at {_level}
        set {_strength} to "strength" of "last_stand" at {_level}
        set {_resistance} to "resistance" of "last_stand" at {_level}
        while {_victim}'s health < {_health threshold}:
            add {_speed} to {_victim}'s potion effects
            add {_strength} to {_victim}'s potion effects
            add {_resistance} to {_victim}'s potion effects
            wait 1 tick