armor enchantment:
    id: "last_stand"
    display: "&f<sprite:items:item/iron_chestplate> &eLast Stand"
    max level: 5
    priority: 0
    item: iron chestplate
    cost: "normal"

    > "speed":
        lvl. 1: potion effect of speed 1 for 1 second
        lvl. 2: potion effect of speed 1 for 1 second
        lvl. 3: potion effect of speed 2 for 1 second
        lvl. 4: potion effect of speed 2 for 1 second
        lvl. 5: potion effect of speed 3 for 1 second

    > "strength":
        lvl. 1: potion effect of strength 1 for 1 second
        lvl. 2: potion effect of strength 1 for 1 second
        lvl. 3: potion effect of strength 1 for 1 second
        lvl. 4: potion effect of strength 1 for 1 second
        lvl. 5: potion effect of strength 2 for 1 second

    > "resistance":
        lvl. 1: potion effect of resistance 1 for 1 second
        lvl. 2: potion effect of resistance 1 for 1 second
        lvl. 3: potion effect of resistance 1 for 1 second
        lvl. 4: potion effect of resistance 1 for 1 second
        lvl. 5: potion effect of resistance 1 for 1 second

    > "health threshold":
        lvl. 1: 2
        lvl. 2: 2.4
        lvl. 3: 2.9
        lvl. 4: 3.2
        lvl. 5: 3.6

local function getDescription(level: integer) :: string:
    set {_speed} to "speed" of "last_stand" at {_level}
    set {_strength} to "strength" of "last_stand" at {_level}
    set {_resistance} to "resistance" of "last_stand" at {_level}
    set {_health threshold} to "health threshold" of "last_stand" at {_level}

    return "when below &f%{_health threshold}%<sprite:gui:hud/heart/full>&8, &7gain &f%effectDisplay({_speed})%&8, &f%effectDisplay({_strength})%&8, &f%effectDisplay({_resistance})%"

local function onAttacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    wait 1 tick
    set {_health threshold} to "health threshold" of "last_stand" at {_level}
    if {_victim}'s health < {_health threshold}:
        set {_speed} to "speed" of "last_stand" at {_level}
        set {_strength} to "strength" of "last_stand" at {_level}
        set {_resistance} to "resistance" of "last_stand" at {_level}
        while {_victim}'s health < {_health threshold}:
            add {_speed} to {_victim}'s potion effects
            add {_strength} to {_victim}'s potion effects
            add {_resistance} to {_victim}'s potion effects
            wait 1 tick