disabled armor enchantment:
    id: "test"
    display: "&fTest"
    max level: 1
    priority: 0
    item: barrier
    ability:
        id: "test"
        bind: "offhand"

local function getDescription(level: integer) :: string:
    return "Test"

local function onAttacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    send "(%{_armor}%) You were attacked by %{_attacker}% at level %{_level}% for %{_damage}%." to {_victim}

local function onAttack(attacker: entity = {_}, armor: item, level: integer, victim: entity, damage: number, damage cause: damage cause) :: number:
    send "(%{_armor}%) You attacked %{_victim}% at level %{_level}% for %{_damage}%." to {_attacker}

local function test(player: player, level: integer) :: boolean:
    send "(%{_player}'s tool%) You put armor in your offhand at level %{_level}%." to {_player}
    chance of 50%:
        send "50%% chance, canceled event." to {_player}
        return true
    else:
        send "50%% chance, didn't cancel event." to {_player}
        return false

local function onApply(armor: item, level: integer, player: player = {_}):
    send "Applied enchantment at level %{_level}%." to {_player}

local function onUnapply(armor: item, old level: integer, player: player = {_}):
    send "Unapplied enchantment at level %{_old level}%." to {_player}

local function onKill(attacker: entity, armor: item, level: integer, victim: entity):
    send "(%{_armor}%) You killed %{_victim}% at level %{_level}%." to {_attacker}

local function onDeath(victim: entity, armor: item, level: integer, killer: entity = {_}):
    send "(%{_armor}%) You died at level %{_level}%." to {_victim}
