on load:
    create disabled armor enchantment named "test":
        set enchantment display to "&fTest"
        set enchantment max level to 1
        set enchantment priority to 0
        set enchantment item to barrier

local function getDescription(level: integer) :: string:
    return "Test"

local function onAttacked(victim: entity, armor: item, level: integer, attacker: entity = {_}, damage: number, damage cause: damage cause) :: number:
    send "(%{_armor}%) You were attacked by %{_attacker}% at level %{_level}% for %{_damage}%." to {_victim}

local function onAttack(attacker: entity = {_}, armor: item, level: integer, victim: entity, damage: number, damage cause: damage cause) :: number:
    send "(%{_armor}%) You attacked %{_victim}% at level %{_level}% for %{_damage}%." to {_attacker}

local function onOffHand(player: player, armor: item, level: integer) :: boolean:
    send "(%{_armor}%) You put armor in your offhand at level %{_level}%." to {_player}
    chance of 50%:
        send "50%% chance, canceled event." to {_player}
        return true
    else:
        send "50%% chance, didn't cancel event." to {_player}
        return false

local function onApply(armor: item, level: integer, player: player = {_}):
    send "Applied enchantment at level %{_level}%." to {_player}

local function onUnapply(armor: item, old level: integer, player: player = {_}):
    send "Unapplied enchantment at level %{_old level}%." to {_player}

local function onKill(attacker: entity, armor: item, level: integer, victim: entity):
    send "(%{_armor}%) You killed %{_victim}% at level %{_level}%." to {_attacker}

local function onDeath(victim: entity, armor: item, level: integer, killer: entity = {_}):
    send "(%{_armor}%) You died at level %{_level}%." to {_victim}