command /group [<offline player>] [<text>] [<text>]:
    permission: beans.admin
    trigger:
        if arg 3 isn't set:
            send "&c/group <player> <set|add|remove> <group>"
        else:
            if arg 2 is "set":
                set group of arg 1 to arg 3
                send "&7Set group of '%arg 1%' to '%arg 3%'."
            else if arg 2 is "add":
                add arg 3 to groups of arg 1
                send "&7Added group '%arg 3%' to '%arg 1%'."
            else if arg 2 is "remove":
                remove arg 3 from groups of arg 1
                send "&7Removed group '%arg 3%' from '%arg 1%'."
            else:
                player command "/group"
        
on tab complete of "/group":
    player has permission "beans.admin"
    set tab completions for position 1 to all players
    set tab completions for position 2 to "set", "add", "remove"
    if tab arg 2 is "set":
        set tab completions for position 3 to indexes of {-groups::*}
    else:
        set {_player} to offlineplayer(tab arg 1, false)
        if tab arg 2 is "add":
            set tab completions for position 3 to (indexes of {-groups::*}) where [{groups::%{_player}%::*} doesn't contain input]
        else if tab arg 2 is "remove":
            set tab completions for position 3 to {groups::%{_player}%::*} where [input isn't "default"]