on load:
    delete all groups

    create group named "default":
        set group prefix to "&7"
        set group weight to 0
        set group chat color to light gray
        set group permissions to ("bukkit.command.tps" and "-minecraft.command.me")

    create group named "vip":
        set group prefix to "&a&lVIP &a"
        set group weight to 100
        set group chat color to white
        set group parent to "default"

    create group named "premium":
        set group prefix to "&b&lPremium &b"
        set group weight to 200
        set group chat color to white
        set group parent to "vip"

    create group named "legend":
        set group prefix to "&5&lLegend &5"
        set group weight to 300
        set group chat color to white
        set group parent to "premium"
    
    create group named "gamer":
        set group prefix to "&3&lGamer &3"
        set group weight to 400
        set group chat color to white
        set group parent to "legend"

    create group named "patron":
        set group prefix to "&9&lPatron &9"
        set group weight to 500
        set group chat color to white
        set group parent to "gamer"

    create group named "mod":
        set group prefix to "&e&lMod &f"
        set group weight to 600
        set group chat color to white
        set group parent to "default"

    create group named "sr-mod":
        set group prefix to "&6&lSr. Mod &f"
        set group weight to 700
        set group chat color to white
        set group parent to "mod"

    create group named "admin":
        set group prefix to "&4&lAdmin &f"
        set group weight to 800
        set group chat color to white
        set group parent to "sr-mod"

on load:
    for {_player} in all players:
        sync {_player}

on join:
    sync player
    