import:
    org.bukkit.permissions.PermissionAttachment

effect sync permissions of %players%:
    trigger:
        for {_player} in exprs-1:
            set {_group} to group of {_player}

            if {-permission attachment::%{_player}%} is set:
                set {_oldAttachment} to {-permission attachment::%{_player}%}

                try:
                    {_oldAttachment}.remove()

                delete {-permission attachment::%{_player}%}

            set {_attachment} to {_player}.addAttachment(instance of plugin "Skript")

            for {_permission} in (group permissions of {_group}) and (custom permissions of {_player}):
                if {_permission} starts with "-":
                    replace first "-" with "" in {_permission}
                    {_attachment}.setPermission({_permission}, false)
                else:
                    {_attachment}.setPermission({_permission}, true)

            set {-permission attachment::%{_player}%} to {_attachment}

            {_player}.recalculatePermissions()
            {_player}.updateCommands()

on quit:
    if {-permission attachment::%player%} is set:
        set {_attachment} to {-permission attachment::%player%}

        try:
            {_attachment}.remove()

        delete {-permission attachment::%player%}

expression:
    patterns:
        custom permissions of %offlineplayer%
        %offlineplayer%'s custom permissions
    get:
        return {permissions::%expr-1%::*}
    add:
        add change value to {permissions::%expr-1%::*}
        sync permissions of expr-1
    remove:
        remove change value from {permissions::%expr-1%::*}
        sync permissions of expr-1
    delete:
        delete {permissions::%expr-1%::*}
        sync permissions of expr-1