on load:
    setting("grinder", "display", value: "&f<sprite:blocks:block/grindstone_side> &cGrinder")
    setting("grinder", "max", value: 5)
    setting("grinder", "priority", value: 10)
    setting("grinder", "type", value: "pickaxe")
    setting("grinder", "item", value: grindstone)
    
    setting("grinder", "requirement", l1: 100, l2: 90, l3: 85, l4: 80, l5: 75)
    setting("grinder", "boost", l1: 0.001, l2: 0.0015, l3: 0.002, l4: 0.0025, l5: 0.003)

    setting("grinder", "xp cost", l2: 60_000, l3: 160_000, l4: 500_000, l5: 1_250_000)
    setting("grinder", "money cost", l2: 100_000, l3: 225_000, l4: 750_000, l5: 1_500_000)

local function getDescription(level: integer) :: string:
    return "boost luck by %formatNumber(get_setting("grinder", "boost", {_level}), "#.#####")%x every %get_setting("grinder", "requirement", {_level})% blocks"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    {_player} is within bound with id "mine flight"

    startGrinderWatcher({_player})
    

    add 1 to {-grinder blocks::%{_player}%}

    if {-grinder blocks::%{_player}%} >= get_setting("grinder", "requirement", {_level}):
        remove get_setting("grinder", "requirement", {_level}) from {-grinder blocks::%{_player}%}
        if {-grinder mining luck::%{_player}%} isn't greater than or equal to 0.5:
            add get_setting("grinder", "boost", {_level}) to {-grinder mining luck::%{_player}%}
            add get_setting("grinder", "boost", {_level}) to {-mining luck::%{_player}%}
        send action bar "Grinder boost: +%formatNumber({-grinder mining luck::%{_player}%}, "#.#####")%x | Total proc rate: %formatNumber(1 + {-mining luck::%{_player}%}, "#.#####")%x" to {_player}

local function startGrinderWatcher(player: player):
    {-grinder watcher::%{_player}%} isn't set

    set {-grinder watcher::%{_player}%} to true

    wait 1 tick
    while {_player} is within bound with id "mine flight":
        wait 1 tick

    remove {-grinder mining luck::%{_player}%} from {-mining luck::%{_player}%}
    delete {-grinder mining luck::%{_player}%}
    delete {-grinder blocks::%{_player}%}
    delete {-grinder watcher::%{_player}%}