on load:
    setting("jackpot", "display", value: "&f<sprite:items:item/gold_ingot> &6Jackpot")
    setting("jackpot", "max", value: 3)
    setting("jackpot", "priority", value: 0)
    setting("jackpot", "type", value: "pickaxe")
    setting("jackpot", "item", value: gold ingot)

    setting("jackpot", "chance", l1: 0.01, l2: 0.02, l3: 0.04)
    
    setting("jackpot", "xp", l1: 50_000, l2: 50_000, l3: 50_000)

    setting("jackpot", "xp cost", l2: 250_000, l3: 1_000_000)
    setting("jackpot", "money cost", l2: 400_000, l3: 1_200_000)

local function getDescription(level: integer) :: string:
    return "gain a large amount of money and xp"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    set {_xp} to get_setting("jackpot", "xp", {_level})
    set {_money} to {-jackpot money}

    add {_xp} to {_player}'s experience
    add {_xp} to {xp source::%{_player}%::jackpot enchantment}
    add {_money} to {money::%{_player}%}
    add {_money} to {money source::%{_player}%::jackpot enchantment}

    play sound "minecraft:ui.toast.challenge_complete" with volume 1 and pitch 1 at location of {_player}
    send "&6&lJACKPOT!" to {_player}
    send "&a+%formatNumber({_money})% money" to {_player}
    send "&b+%formatNumber({_xp})% xp" to {_player}

on load:
    getJackpotAmount()

async every 10 minutes:
    getJackpotAmount()

function getJackpotAmount():
    set {-jackpot money} to 50_000
    #async run 0 seconds later:
     #   set {-jackpot money} to 50_000 + (mean({money::*}) / 10) 