using reflection

on load:
    setting("jackhammer", "display", value: "&f<sprite:items:item/netherite_pickaxe> &eJackhammer")
    setting("jackhammer", "max", value: 5)
    setting("jackhammer", "priority", value: 10)
    setting("jackhammer", "type", value: "pickaxe")
    setting("jackhammer", "item", value: netherite pickaxe)

    setting("jackhammer", "chance", l1: 10, l2: 13, l3: 15, l4: 15, l5: 15)

    setting("jackhammer", "width", l1: 4, l2: 5, l3: 6, l4: 7, l5: 8)
    setting("jackhammer", "height", l1: 1, l2: 1, l3: 2, l4: 2, l5: 3)

    setting("jackhammer", "xp cost", l2: 40_000, l3: 200_000, l4: 600_000, l5: 1_000_000)
    setting("jackhammer", "money cost", l2: 50_000, l3: 300_000, l4: 750_000, l5: 1_300_000)

local function getDescription(level: integer) :: string:
    return "mine %get_setting("jackhammer", "width", {_level})%x%get_setting("jackhammer", "width", {_level})%x%get_setting("jackhammer", "height", {_level})% area"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    play sound "minecraft:block.anvil.land" with volume 0.5 and pitch 1 at location of {_block}

    {_block} is within bound with id "mine"

    set {_centerX} to x-coordinate of {_block}
    set {_centerY} to y-coordinate of {_block}
    set {_centerZ} to z-coordinate of {_block}
    set {_world} to world of {_block}

    set {_width} to get_setting("jackhammer", "width", {_level})
    set {_height} to get_setting("jackhammer", "height", {_level})

    set {_left} to floor(({_width} - 1) / 2)
    set {_right} to ceil(({_width} - 1) / 2)

    set {_minX} to {_centerX} - {_left}
    set {_maxX} to {_centerX} + {_right}
    set {_minZ} to {_centerZ} - {_left}
    set {_maxZ} to {_centerZ} + {_right}
    set {_maxY} to {_centerY} + ({_height} - 1)

    loop all numbers between {_centerY} and {_maxY}:
        set {_y} to loop-value
        wait 3 ticks
        loop all numbers between {_minX} and {_maxX}:
            set {_x} to loop-value-2
            loop all numbers between {_minZ} and {_maxZ}:
                set {_z} to loop-value-3
                set {_b} to block at location({_x}, {_y}, {_z}, {_world})

                {_b} is within bound with id "mine"
                {_b} isn't air, bedrock, beacon, obsidian, or packed ice

                blockReward({_player}, {_tool}, {_b}, "jackhammer enchantment")
                
                set block within {_b} to air