on load:
    setting("lucky", "display", value: "&f<sprite:items:item/trial_key> &fLucky")
    setting("lucky", "max", value: 5)
    setting("lucky", "priority", value: 1000)
    setting("lucky", "type", value: "pickaxe")
    setting("lucky", "item", value: trial key)

    setting("lucky", "chance", l1: 1, l2: 1.25, l3: 1.75, l4: 2, l5: 3)

    setting("lucky", "boost", l1: 0.2, l2: 0.225, l3: 0.25, l4: 0.27, l5: 0.3)
    setting("lucky", "duration", l1: 5 seconds, l2: 5.5 seconds, l3: 6 seconds, l4: 6.5 seconds, l5: 7 seconds)

    setting("lucky", "xp cost", l2: 40_000, l3: 200_000, l4: 550_000, l5: 1_200_000)
    setting("lucky", "money cost", l2: 50_000, l3: 250_000, l4: 750_000, l5: 1_500_000)

local function getDescription(level: integer) :: string:
    set {_boost} to get_setting("lucky", "boost", {_level})
    set {_duration} to get_setting("lucky", "duration", {_level})
    return "gain %{_boost} * 100%%% luck for %time_format({_duration})%"

local function onbreak(player: player, tool: item, level: integer, block: block, block type: item type):
    {-mining luck boost::%{_player}%} isn't set
    set {-mining luck boost::%{_player}%} to true
    add get_setting("lucky", "boost", {_level}) to {-mining luck::%{_player}%}
    play sound "minecraft:block.amethyst_block.resonate" with volume 1 and pitch 1 at location of {_player}
    wait get_setting("lucky", "duration", {_level})
    delete {-mining luck boost::%{_player}%}
    remove get_setting("lucky", "boost", {_level}) from {-mining luck::%{_player}%}