import:
    ch.njol.skript.lang.Effect
    ch.njol.skript.lang.TriggerItem
    ch.njol.skript.lang.parser.ParserInstance
    ch.njol.skript.log.SkriptLogger
    ch.njol.skript.command.EffectCommandEvent
    ch.njol.skript.variables.Variables
    org.bukkit.Bukkit

command /effectcommand:
    trigger:
        canEditScripts(player) is true
        set {_initial} to {effectcommand::editor::%uuid of player%}
        openEffectCommandDialog(player, {_initial}, "")

function openEffectCommandDialog(player: player, code: text, output: text):
    open new confirmation dialog to {_player}:
        title: ""
        can_close_with_escape: true
        after_action: "close"

        body:
            if {_output} is not "":
                add text body:
                    contents: {_output}
                    width: 350

        inputs:
            add text input:
                key: "code"
                label: "%instance of plugin "Skript"%"
                initial: {_code}
                width: 350
                max_length: 100000
                multiline_height: 150
                multiline_max_lines: 9999

        actions:
            add callback action button:
                label: "Clear"
                width: 100
                trigger:
                    delete {effectcommand::editor::%uuid of event-player%}
                    openEffectCommandDialog(event-player, "", "")

            add callback action button:
                label: "Run"
                width: 100
                trigger:
                    set {_p} to event-player
                    set {_code} to string tag "code" of event-nbt
                    set {effectcommand::editor::%uuid of {_p}%} to {_code}

                    set {_error} to runMultilineEffectCommand({_p}, {_code})
                    {_error} is set 
                    openEffectCommandDialog({_p}, {_code}, {_error})

function runMultilineEffectCommand(sender: command sender, code: text) :: text:
    length of {_code} > 1
    set {_lines::*} to unformatted {_code} split at nl
    set {_mapped::*} to ({_lines::*} mapped using ["%nl%'%input%'"])
    send "&7Executing:%join {_mapped::*}%" to {_sender}

    set {_event} to new EffectCommandEvent({_sender}, {_code})

    Bukkit.getPluginManager().callEvent({_event})
    set {_code} to {_event}.getCommand()

    set {_parser} to ParserInstance.get()
    {_parser}.setCurrentEvent("effect command", EffectCommandEvent.class)

    set {_log} to SkriptLogger.startRetainingLog()

    delete {_effects::*}

    loop {_code} split at nl:
        set {_line} to loop-value

        if {_line} is "":
            continue
        if {_line} starts with "#":
            continue

        set {_effect} to Effect.parse({_line}, null)

        if {_effect} is not set:
            {_parser}.deleteCurrentEvent()

            {_log}.stop()

            send "&cError in: &7%{_line}%" to {_sender}

            return "&c&lLine %loop-iteration%:%nl%&6Line: &7%{_line}%"

        add {_effect} to {_effects::*}

    {_parser}.deleteCurrentEvent()

    if {_event}.isCancelled():
        {_log}.stop()
        return "&cYour effect command was cancelled."

    {_log}.clear()

    loop {_effects::*}:
        TriggerItem.walk(loop-value, {_event})

    Variables.removeLocals({_event})
    {_log}.stop()

function canEditScripts(player: player) :: boolean:
    return true if {_player} is op

    return whether {_player}'s name is "MrScopes"

command /editor <text>:
    trigger:
        canEditScripts(player) is true

        set {_name} to arg-1

        replace all "\" in {_name} with "/"
        replace all "../" in {_name} with ""
        replace all ".." in {_name} with ""
        replace all ":" in {_name} with ""
        replace all "|" in {_name} with ""

        if {_name} does not end with ".sk":
            set {_name} to "%{_name}%.sk"

        set {_path} to "./plugins/Skript/scripts/%{_name}%"

        if file {_path} does not exist:
            create file {_path}:
                set the text contents of file to ""

        delete {_lines::*}
        read file {_path}:
            loop the lines of file:
                add loop-value to {_lines::*}

        set {_content} to join {_lines::*} with nl

        openEditor(player, {_name}, {_path}, {_content})

function openEditor(p: player, name: text, path: text, content: text):
    open new notice dialog to {_p}:
        title: ""
        can_close_with_escape: true
        after_action: "close"

        inputs:
            add text input:
                key: "code"
                label: "%{_name}%"
                initial: {_content}
                width: 900
                max_length: 100000
                multiline_height: 150
                multiline_max_lines: 9999

        action:
            add callback action button:
                label: "Run"
                width: 100
                trigger:
                    set {_code} to string tag "code" of event-nbt

                    # backup current disk version before overwriting
                    set {_backup folder} to "./plugins/Skript/scripts/-backups/%event-player%/"
                    if file {_backup folder} does not exist:
                        create a new folder {_backup folder}

                    set {_backup} to "%{_backup folder}%%{_name}%-%now formatted as "yyyy-MM-dd-mm-ss"%.sk"

                    read file {_path}:
                        set {_old} to the text contents of file

                    create file {_backup}:
                        set the text contents of file to {_old}

                    edit file {_path}:
                        set the text contents of file to {_code}

                    execute event-player command "sk reload %{_name}%"

on tab complete of "/editor":
    set tab completions for position 1 to all scripts