
on load:
    set {-effect::speed::display} to "<sprite:gui:mob_effect/speed>"
    set {-effect::slowness::display} to "<sprite:gui:mob_effect/slowness>"
    set {-effect::strength::display} to "<sprite:gui:mob_effect/strength>"
    set {-effect::weakness::display} to "<sprite:gui:mob_effect/weakness>"
    set {-effect::haste::display} to "<sprite:gui:mob_effect/haste>"
    set {-effect::mining fatigue::display} to "<sprite:gui:mob_effect/mining_fatigue>"
    set {-effect::regeneration::display} to "<sprite:gui:mob_effect/regeneration>"
    set {-effect::poison::display} to "<sprite:gui:mob_effect/poison>"
    set {-effect::wither::display} to "<sprite:gui:mob_effect/wither>"
    set {-effect::fire resistance::display} to "<sprite:gui:mob_effect/fire_resistance>"
    set {-effect::invisibility::display} to "<sprite:gui:mob_effect/invisibility>"
    set {-effect::night vision::display} to "<sprite:gui:mob_effect/night_vision>"
    set {-effect::absorption::display} to "<sprite:gui:mob_effect/absorption>"
    set {-effect::luck::display} to "<sprite:gui:mob_effect/luck>"
    set {-effect::unluck::display} to "<sprite:gui:mob_effect/unluck>"
    set {-effect::water breathing::display} to "<sprite:gui:mob_effect/water_breathing>"
    set {-effect::jump boost::display} to "<sprite:gui:mob_effect/jump_boost>"
    set {-effect::resistance::display} to "<sprite:gui:mob_effect/resistance>"
    set {-effect::blindness::display} to "<sprite:gui:mob_effect/blindness>"
    set {-effect::glowing::display} to "<sprite:gui:mob_effect/glowing>"
    set {-effect::hunger::display} to "<sprite:gui:mob_effect/hunger>"
    set {-effect::armor::display} to "<sprite:gui:hud/armor_full>"

function smallNumber(number: number) :: text:
    set {_text} to "%{_number}%"
    replace all "1" with "¹" in {_text}
    replace all "2" with "²" in {_text}
    replace all "3" with "³" in {_text}
    replace all "4" with "⁴" in {_text}
    replace all "5" with "⁵" in {_text}
    replace all "6" with "⁶" in {_text}
    replace all "7" with "⁷" in {_text}
    replace all "8" with "⁸" in {_text}
    replace all "9" with "⁹" in {_text}
    replace all "0" with "⁰" in {_text}
    return {_text}

function effectDisplay(effect: potion effect, force: boolean = false) :: text:
    if {_force} is true:
        return "%{-effect::%type of {_effect}%::display}%%smallNumber(amplifier of {_effect})% &f%time_format(duration of {_effect})%&"
    if amplifier of {_effect} > 1:
        return "%{-effect::%type of {_effect}%::display}%%smallNumber(amplifier of {_effect})% &f%time_format(duration of {_effect})%"
    else:
        return "%{-effect::%type of {_effect}%::display}% &f%time_format(duration of {_effect})%"