on load:
    set {-romannumerals::roman::*} to "M", "XM", "CM", "D", "XD", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"
    set {-romannumerals::arabic::*} to 1000, 990, 900, 500, 490, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1

function romanNumeral(arabic:number) :: string:
    loop {-romannumerals::arabic::*}:
        set {_roman} to {-romannumerals::roman::%loop-index%}
        while {_arabic} >= loop-value:
            set {_romanNumeral} to "%{_romanNumeral} ? ""%%{_roman}%"
            remove loop-value from {_arabic}
    return {_romanNumeral}

import:
    java.lang.System 
    java.lang.Float

expression current (:m|:n)s:
    get:
        if parse tags is "m":
            return System.currentTimeMillis()
        else if parse tags is "n":
            return System.nanoTime()

function capitalizeFirst(input: string) :: string:
    set {_split::*} to split {_input} at ""
    set {_split::1} to capitalized {_split::1}
    return join {_split::*} with ""

# utilities
 # some of these scripts aren't mine

function kNumber(number: number) :: string:
    set {_n} to {_number}
    set {_data} to "QT,18|Q,15|T,12|B,9|M,6|k,3"
    loop split {_data} at "|":
        set {_s::*} to split loop-value at ","
        {_n} >= 10 ^ {_s::2} parsed as number
        return "%{_n} / 10 ^ {_s::2} parsed as number%%{_s::1}%"
    return "%{_n} ? 0%"

# creator: forgot 
# unformatted number 10k -> 10000
expression unformatted number %string%:
	get:
		set {_t} to expr-1
		replace all "," with "" in {_t}
		set {_v} to ""
		set {_data} to "Q,15|T,12|B,9|M,6|k,3"
		loop split {_data} at "|":
			set {_s::*} to split loop-value at ","
			set {_d::%{_s::1}%} to {_s::2} parsed as number
		loop split {_t} at "":
			if {_d::%loop-value%} is set:
				add {_d::%loop-value%} to {_n}
			else:
				set {_v} to "%{_v}%%loop-value%"
		return ({_v} parsed as number) * 10^{_n}
		
command /up <number>:
	permission: beans.admin
	trigger:
		set block at block arg - 1 above player to glass if block at block arg - 1 above player is air
		teleport player to block arg above player
			
import:
	java.util.ArrayList
	ch.njol.skript.lang.LiteralList
	ch.njol.skript.lang.Condition
	ch.njol.skript.lang.Expression

expression player %string%:
    get:
        return offlineplayer(expr-1)

on load:
    set {-time::s} to "second"
    set {-time::m} to "minute"
    set {-time::h} to "hour"
    set {-time::d} to "day"
    set {-time::w} to "week"
    set {-time::mo} to "month"
    set {-time::y} to "year"

function stringToTimespan(input: string) :: timespan:
    replace all " " in {_input} with ""
    loop regex {_input} split at "(?<=\d[a-z])(?=\d)":
        set {_t::*} to regex loop-value split at "(?<=\d)(?=[a-z])"
        set {_t::2} to " %{-time::%{_t::2}%} ? {_t::2}% "
        add (join {_t::*} with "") to {_result::*}
    set {_result} to (join {_result::*} with "")
    return {_result} parsed as timespan

function time_format(time: timespan) :: string:
  set {_time} to "%{_time}%"
  set {_timespan::*} to {_time} parsed as "%number% %string%[s][ and %number% %string%[s]]"
  set {_first} to "%{_timespan::1}%%first character of {_timespan::2}%"
  set {_second} to "%{_timespan::3}%%first character of {_timespan::4}%"

  return ("%{_first}% %{_second}%" if {_timespan::3} is set, else "%{_first}%")

###
###

function scramble(text: text) :: text:
    return join (shuffled ({_text} split at ""))

##

function timedTP(player: player, location: location):
    if all:
        {_player}'s gamemode isn't creative or spectator
        {-vanish::%{_player}%} isn't set
    then:
        set {_seconds} to 3
        set {_starting location} to {_player}'s location
        while {_seconds} > 0:
            send "&7Teleporting in &b%{_seconds}%s&7... Don't move." to {_player}
            wait 1 second
            subtract 1 from {_seconds}

            if distance between {_player}'s location and {_starting location} > 2:
                send "&cCanceled teleportation due to movement." to {_player}
                delete {_seconds}
                stop loop

            if {_seconds} is 0:
                teleport {_player} to {_location}
    else:
        teleport {_player} to {_location}