on load:
    create bow enchantment named "adrenaline":
        set enchantment display to "&f<sprite:items:item/sugar> &aAdrenaline"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to sugar (item)

        level values for "chance":
            set level 1 to 40
            set level 2 to 40
            set level 3 to 40
            set level 4 to 40
            set level 5 to 40

        level values for "cooldown":
            set level 1 to 15 seconds
            set level 2 to 14 seconds
            set level 3 to 13 seconds
            set level 4 to 12 seconds
            set level 5 to 10 seconds

        level values for "speed":
            set level 1 to potion effect of speed 1 for 3 seconds
            set level 2 to potion effect of speed 1 for 4 seconds
            set level 3 to potion effect of speed 2 for 4 seconds
            set level 4 to potion effect of speed 2 for 5 seconds
            set level 5 to potion effect of speed 3 for 6 seconds

        level values for "resistance":
            set level 1 to potion effect of resistance 1 for 2 seconds
            set level 2 to potion effect of resistance 1 for 3 seconds
            set level 3 to potion effect of resistance 2 for 3 seconds
            set level 4 to potion effect of resistance 2 for 4 seconds
            set level 5 to potion effect of resistance 3 for 4 seconds

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_speed} to "speed" of {_level} for "adrenaline"
    set {_resistance} to "resistance" of {_level} for "adrenaline"
    return "on hit&8, &7apply &f%effectDisplay({_speed})% &7and &f%effectDisplay({_resistance})%"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_speed} to "speed" of {_level} for "adrenaline"
        set {_resistance} to "resistance" of {_level} for "adrenaline"
        set duration of {_speed} to duration of {_speed} * {_force}
        set duration of {_resistance} to duration of {_resistance} * {_force}
        apply {_speed} to {_shooter}
        apply {_resistance} to {_shooter}
        playEnchantmentSound("combat", "entity.player.attack.sweep", 1, 0.1, location of {_shooter}, all players)
