bow enchantment:
    id: "adrenaline"
    display: "&f<sprite:items:item/sugar> &aAdrenaline"
    max level: 5
    priority: 10
    item: sugar (item)
    cost: "normal"

    > "chance":
        lvl. 1: 40%
        lvl. 2: 40%
        lvl. 3: 40%
        lvl. 4: 40%
        lvl. 5: 40%

    > "cooldown":
        lvl. 1: 15 seconds
        lvl. 2: 14 seconds
        lvl. 3: 13 seconds
        lvl. 4: 12 seconds
        lvl. 5: 10 seconds

    > "speed":
        lvl. 1: potion effect of speed 1 for 3 seconds
        lvl. 2: potion effect of speed 1 for 4 seconds
        lvl. 3: potion effect of speed 2 for 4 seconds
        lvl. 4: potion effect of speed 2 for 5 seconds
        lvl. 5: potion effect of speed 3 for 6 seconds

    > "resistance":
        lvl. 1: potion effect of resistance 1 for 2 seconds
        lvl. 2: potion effect of resistance 1 for 3 seconds
        lvl. 3: potion effect of resistance 2 for 3 seconds
        lvl. 4: potion effect of resistance 2 for 4 seconds
        lvl. 5: potion effect of resistance 3 for 4 seconds

local function getDescription(level: integer) :: string:
    set {_speed} to "speed" of "adrenaline" at {_level}
    set {_resistance} to "resistance" of "adrenaline" at {_level}
    return "on hit&8, &7apply &f%effectDisplay({_speed})% &7and &f%effectDisplay({_resistance})%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_speed} to "speed" of "adrenaline" at {_level}
        set {_resistance} to "resistance" of "adrenaline" at {_level}
        set duration of {_speed} to duration of {_speed} * {_force}
        set duration of {_resistance} to duration of {_resistance} * {_force}
        apply {_speed} to {_shooter}
        apply {_resistance} to {_shooter}
        playEnchantmentSound("combat", "entity.player.attack.sweep", 1, 0.1, location of {_shooter}, all players)
