on load:
    setting("ambush", "display", value: "&f<sprite:items:item/black_dye> &eAmbush")
    setting("ambush", "max level", value: 5)
    setting("ambush", "priority", value: 0)
    setting("ambush", "type", value: "bow")
    setting("ambush", "item", value: black dye)

    setting("ambush", "multiplier", l1: 0.1, l2: 0.15, l3: 0.2, l4: 0.25, l5: 0.3)

    setting("ambush", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("ambush", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "when the victim hasn't taken damage within &f20s&8, &7increase dmg by &f%get_setting("ambush", "multiplier", {_level}) * 100%%%"

local function onattack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    if (difference between now and {-last damaged::%{_victim}%}) > 20 seconds:
        play sound "entity.player.attack.crit" with volume 1 and pitch 0.1 at {_victim}
        return {_damage} * get_setting("ambush", "multiplier", {_level})

on damage of player with priority monitor:
    event isn't canceled
    damage > 0
    set {-last damaged::%victim%} to now