on load:
    create bow enchantment named "ambush":
        set enchantment display to "&f<sprite:items:item/black_dye> &eAmbush"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to black dye

        level values for "multiplier":
            set level 1 to 0.1
            set level 2 to 0.15
            set level 3 to 0.2
            set level 4 to 0.25
            set level 5 to 0.3

        level values for "time threshold":
            set level 1 to 20 seconds
            set level 2 to 20 seconds
            set level 3 to 20 seconds
            set level 4 to 20 seconds
            set level 5 to 20 seconds

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "ambush" at {_level}
    set {_time} to "time threshold" of "ambush" at {_level}
    return "when the victim hasn't taken damage within &f%time_format({_time})%&8, &7increase dmg by &f%{_multiplier} * 100%%%" 

local function onattack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    set {_time} to "time threshold" of "ambush" at {_level}
    if (difference between now and {-last damaged::%{_victim}%}) > {_time}:
        set {_multiplier} to "multiplier" of "ambush" at {_level}
        playEnchantmentSound("combat", "entity.player.attack.crit", 1, 0.1, location of {_victim}, all players)
        return {_damage} * {_multiplier}

on damage of player with priority monitor:
    event isn't canceled
    damage > 0
    set {-last damaged::%victim%} to now
