on load:
    create bow enchantment named "ambush":
        set enchantment display to "&f<sprite:items:item/black_dye> &eAmbush"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to black dye

        level values for "multiplier":
            set level 1 to 0.1
            set level 2 to 0.15
            set level 3 to 0.2
            set level 4 to 0.25
            set level 5 to 0.3

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    return "when the victim hasn't taken damage within &f20s&8, &7increase dmg by &f%"multiplier" of {_level} for "ambush" * 100%%%"

local function onattack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    if (difference between now and {-last damaged::%{_victim}%}) > 20 seconds:
        play sound "entity.player.attack.crit" with volume 1 and pitch 0.1 at {_victim}
        return {_damage} * "multiplier" of {_level} for "ambush"

on damage of player with priority monitor:
    event isn't canceled
    damage > 0
    set {-last damaged::%victim%} to now
