bow enchantment:
    id: "arrow_rain"
    display: "&f<sprite:items:item/spectral_arrow> &6Arrow Rain"
    max level: 5
    priority: 0
    item: spectral arrow
    cost: "normal"

    > "cooldown":
        lvl. 1: 15 seconds
        lvl. 2: 14 seconds
        lvl. 3: 13 seconds
        lvl. 4: 12 seconds
        lvl. 5: 10 seconds

    > "threshold":
        lvl. 1: 1
        lvl. 2: 1
        lvl. 3: 1
        lvl. 4: 1
        lvl. 5: 1

    > "amount":
        lvl. 1: 10
        lvl. 2: 14
        lvl. 3: 18
        lvl. 4: 20
        lvl. 5: 25

    > "damage":
        lvl. 1: 0.35
        lvl. 2: 0.5
        lvl. 3: 0.65
        lvl. 4: 0.8
        lvl. 5: 1.0

    > "duration":
        lvl. 1: 3 seconds
        lvl. 2: 4 seconds
        lvl. 3: 5 seconds
        lvl. 4: 6 seconds
        lvl. 5: 7 seconds

local function getDescription(level: integer) :: string:
    set {_amount} to "amount" of "arrow_rain" at {_level}
    set {_damage} to "damage" of "arrow_rain" at {_level}
    set {_duration} to "duration" of "arrow_rain" at {_level}
    return "on land&8, &7rain &f%{_amount}% &7arrows for &f%timeFormat({_duration})% &7dealing &c%{_damage}%&4<sprite:gui:hud/heart/full>&7 each"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    set {_amount} to "amount" of "arrow_rain" at {_level}
    set {_damage} to "damage" of "arrow_rain" at {_level}
    set {_duration} to "duration" of "arrow_rain" at {_level}

    set {_location} to location of {_projectile} ~ vector(0, 10, 0)
    set yaw of {_location} to 90
    set pitch of {_location} to 90

    loop seconds of {_duration} times:
        loop {_amount} times:
            set {_loc} to {_location} ~ vector(random number between -3 and 3, 0, random number between -3 and 3)
            shoot arrow from {_loc} at speed 0
            set velocity of last shot arrow to vector(0, -0.5, 0)
            set {-%last shot arrow%::damage} to {_damage}
            set {-%last shot arrow%::shooter} to {_shooter}
        wait 1 second

on damage with priority monitor:
    projectile is set
    set {_projectile} to projectile
    set {_damage} to {-%{_projectile}%::damage}
    set {_shooter} to {-%{_projectile}%::shooter}
    cancel event
    set {_source} to a custom damage source:
        set the damage type to arrow
        set the causing entity to {_shooter}
        set the direct entity to {_shooter}
        set the damage location to location of {_projectile}
    damage victim by {_damage} using {_source}
    reset victim's no damage time