on load:
    create bow enchantment named "black_hole":
        set enchantment display to "&f<sprite:blocks:block/obsidian> &5Black Hole"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to obsidian

        level values for "cooldown":
            set level 1 to 20 seconds
            set level 2 to 20 seconds
            set level 3 to 20 seconds
            set level 4 to 20 seconds
            set level 5 to 20 seconds

        level values for "threshold":
            set level 1 to 1
            set level 2 to 1
            set level 3 to 1
            set level 4 to 1
            set level 5 to 1

        level values for "duration":
            set level 1 to 3 seconds
            set level 2 to 4 seconds
            set level 3 to 5 seconds
            set level 4 to 6 seconds
            set level 5 to 7 seconds

        level values for "radius":
            set level 1 to 2
            set level 2 to 2.5
            set level 3 to 3
            set level 4 to 3.5
            set level 5 to 4

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of "black_hole" at {_level}
    set {_radius} to "radius" of "black_hole" at {_level}
    return "on land&8, &7pull in entities within &f%{_radius}%m &7for &f%timeFormat({_duration})%&8, &7and &f%effectDisplay("elytra disable", showAmplifier: false, showDuration: false,)%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    set {_duration} to "duration" of "black_hole" at {_level}
    set {_radius} to "radius" of "black_hole" at {_level}
    set {_location} to location of {_projectile}
    loop ticks of {_duration} times:
        wait 1 ticks
        show 100 portal particle at {_location}
        loop all living entities in radius {_radius} around {_location}:
            push loop-entity towards {_location} at speed 0.1
            add 2 ticks to cooldown of elytra for loop-entity
