bow enchantment:
    id: "black_hole"
    display: "&f<sprite:blocks:block/obsidian> &5Black Hole"
    max level: 5
    priority: 0
    item: obsidian
    cost: "normal"

    > "cooldown":
        lvl. 1: 20 seconds
        lvl. 2: 20 seconds
        lvl. 3: 20 seconds
        lvl. 4: 20 seconds
        lvl. 5: 20 seconds

    > "threshold":
        lvl. 1: 1
        lvl. 2: 1
        lvl. 3: 1
        lvl. 4: 1
        lvl. 5: 1

    > "duration":
        lvl. 1: 3 seconds
        lvl. 2: 4 seconds
        lvl. 3: 5 seconds
        lvl. 4: 6 seconds
        lvl. 5: 7 seconds

    > "radius":
        lvl. 1: 2
        lvl. 2: 2.5
        lvl. 3: 3
        lvl. 4: 3.5
        lvl. 5: 4

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of "black_hole" at {_level}
    set {_radius} to "radius" of "black_hole" at {_level}
    return "on land&8, &7pull in entities within &f%{_radius}%m &7for &f%timeFormat({_duration})%&8, &7and &f%effectDisplay("elytra disable", showAmplifier: false, showDuration: false,)%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    set {_duration} to "duration" of "black_hole" at {_level}
    set {_radius} to "radius" of "black_hole" at {_level}
    set {_location} to location of {_projectile}
    loop ticks of {_duration} times:
        wait 1 ticks
        show 100 portal particle at {_location}
        loop all living entities in radius {_radius} around {_location}:
            push loop-entity towards {_location} at speed 0.1
            add 2 ticks to cooldown of elytra for loop-entity
            