bow enchantment:
    id: "bullseye"
    display: "&f<head:entity/player/wide/steve> &eBullseye"
    max level: 5
    priority: 10
    item: player head
    cost: "normal"

    > "threshold":
        lvl. 1: 0.75
        lvl. 2: 0.75
        lvl. 3: 0.75
        lvl. 4: 0.75
        lvl. 5: 0.75

    > "damage":
        lvl. 1: 0.5
        lvl. 2: 0.75
        lvl. 3: 1
        lvl. 4: 1.25
        lvl. 5: 1.75

local function getDescription(level: integer) :: string:
    set {_damage} to "damage" of "bullseye" at {_level}
    return "deals &f%{_damage}%<sprite:gui:hud/heart/full> &7with headshots"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        if distance between location of {_projectile} and eye of {_victim} < 0.5:
            set {_damage} to "damage" of "bullseye" at {_level}
            playEnchantmentSound("combat", "entity.arrow.hit_player", 1, 0.1, location of {_shooter}, all players)
            damage({_victim}, {_attacker}, {_damage})
            