on load:
    create bow enchantment named "bullseye":
        set enchantment display to "&f<head:entity/player/wide/steve> &eBullseye"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to player head

        level values for "threshold":
            set level 1 to 0.75
            set level 2 to 0.75
            set level 3 to 0.75
            set level 4 to 0.75
            set level 5 to 0.75

        level values for "damage":
            set level 1 to 0.5
            set level 2 to 0.75
            set level 3 to 1
            set level 4 to 1.25
            set level 5 to 1.75

        level values for "dust cost":
            set level 2 to 20
            set level 3 to 100
            set level 4 to 450
            set level 5 to 1_100

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_damage} to "damage" of "bullseye" at {_level}
    return "deals &f%{_damage}%<sprite:gui:hud/heart/full> &7with headshots"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        if distance between location of {_projectile} and eye of {_victim} < 0.5:
            set {_damage} to "damage" of "bullseye" at {_level}
            playEnchantmentSound("combat", "entity.arrow.hit_player", 1, 0.1, location of {_shooter}, all players)
            damage({_victim}, {_attacker}, {_damage})