on load:
    setting("bullseye", "display", value: "&f<head:entity/player/wide/steve> &eBullseye")
    setting("bullseye", "max level", value: 5)
    setting("bullseye", "priority", value: 10)
    setting("bullseye", "type", value: "bow")
    setting("bullseye", "item", value: player head)

    setting("bullseye", "threshold", l1: 0.75, l2: 0.75, l3: 0.75, l4: 0.75, l5: 0.75)

    setting("bullseye", "damage", l1: 0.5, l2: 0.75, l3: 1, l4: 1.25, l5: 1.75)

    setting("bullseye", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("bullseye", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "deals %get_setting("bullseye", "damage", {_level})%&f<sprite:gui:hud/heart/full> &7with headshots"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        if distance between location of {_projectile} and eye of {_victim} < 0.5:
            play sound "entity.arrow.hit_player" at volume 1 and pitch 0.1 at {_shooter}
            damage({_victim}, {_attacker}, get_setting("bullseye", "damage", {_level}))