on load:
    create bow enchantment named "concuss":
        set enchantment display to "&f<sprite:blocks:block/cobweb> &fConcuss"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to cobweb

        level values for "chance":
            set level 1 to 20
            set level 2 to 25
            set level 3 to 30
            set level 4 to 35
            set level 5 to 40

        level values for "effect":
            set level 1 to potion effect of slowness 1 for 4 seconds
            set level 2 to potion effect of slowness 1 for 5 seconds
            set level 3 to potion effect of slowness 2 for 6 seconds
            set level 4 to potion effect of slowness 2 for 7 seconds
            set level 5 to potion effect of slowness 3 for 7 seconds

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_effect} to "effect" of "concuss" at {_level}
    set {_amplifier} to amplifier of {_effect}
    set {_duration} to time_format(duration of {_effect})
    return "applies &f%effectDisplay({_effect})% &7and &f%effectDisplay("firework disable", customDuration: duration of {_effect}, showAmplifier: false)%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_effect} to "effect" of "concuss" at {_level}
        add {_effect} to {_victim}'s potion effects
        set cooldown of firework for {_victim} to duration of {_effect}
        playEnchantmentSound("combat", "entity.spider.ambient", 1, 1, location of {_victim}, all players)
