bow enchantment:
    id: "concuss"
    display: "&f<sprite:blocks:block/cobweb> &fConcuss"
    max level: 5
    priority: 10
    item: cobweb
    cost: "normal"

    > "chance":
        lvl. 1: 20
        lvl. 2: 25
        lvl. 3: 30
        lvl. 4: 35
        lvl. 5: 40

    > "effect":
        lvl. 1: potion effect of slowness 1 for 4 seconds
        lvl. 2: potion effect of slowness 1 for 5 seconds
        lvl. 3: potion effect of slowness 2 for 6 seconds
        lvl. 4: potion effect of slowness 2 for 7 seconds
        lvl. 5: potion effect of slowness 3 for 7 seconds

local function getDescription(level: integer) :: string:
    set {_effect} to "effect" of "concuss" at {_level}
    set {_amplifier} to amplifier of {_effect}
    set {_duration} to timeFormat(duration of {_effect})
    return "applies &f%effectDisplay({_effect})% &7and &f%effectDisplay("firework disable", customDuration: duration of {_effect}, showAmplifier: false)%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_effect} to "effect" of "concuss" at {_level}
        add {_effect} to {_victim}'s potion effects
        set cooldown of firework for {_victim} to duration of {_effect}
        playEnchantmentSound("combat", "entity.spider.ambient", 1, 1, location of {_victim}, all players)