on load:
    create bow enchantment named "creeper":
        set enchantment display to "&f<head:creeper> &2Creeper"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to creeper spawn egg

        level values for "manual chance::onHit":
            set level 1 to true
            set level 2 to true
            set level 3 to true
            set level 4 to true
            set level 5 to true

        level values for "chance":
            set level 1 to 20
            set level 2 to 25
            set level 3 to 30
            set level 4 to 35
            set level 5 to 50

        level values for "threshold":
            set level 1 to 0.5
            set level 2 to 0.4
            set level 3 to 0.35
            set level 4 to 0.3
            set level 5 to 0.20

        level values for "manual cooldown::onHit":
            set level 1 to true
            set level 2 to true
            set level 3 to true
            set level 4 to true
            set level 5 to true

        level values for "cooldown":
            set level 1 to 18 seconds
            set level 2 to 17 seconds
            set level 3 to 16 seconds
            set level 4 to 15 seconds
            set level 5 to 12 seconds

        level values for "radius":
            set level 1 to 2.5
            set level 2 to 2.75
            set level 3 to 3
            set level 4 to 3.25
            set level 5 to 3.75

        level values for "damage":
            set level 1 to 0.5
            set level 2 to 0.75
            set level 3 to 1
            set level 4 to 1.25
            set level 5 to 1.75

        level values for "fuse":
            set level 1 to 20
            set level 2 to 17
            set level 3 to 15
            set level 4 to 13
            set level 5 to 10

        level values for "dust cost":
            set level 2 to 20
            set level 3 to 125
            set level 4 to 2_300
            set level 5 to 6_000

        level values for "money cost":
            set level 2 to 24_000
            set level 3 to 200_000
            set level 4 to 1_000_000
            set level 5 to 3_000_000

local function getDescription(level: integer) :: string:
    set {_fuse} to "fuse" of "creeper" at {_level}
    set {_damage} to "damage" of "creeper" at {_level}
    set {_radius} to "radius" of "creeper" at {_level}
    return "Spawn creeper on arrow. &f%{_fuse} / 20%s &7fuse&8, &7deals &f%{_damage}%<sprite:gui:hud/heart/full>&8, &7within &f%{_radius}%m"

local function onShoot(shooter: entity, tool: item, projectile: projectile, level: integer, force: number):
    set {-%{_projectile}%::spawn creeper} to true
    playEnchantmentSound("combat", "entity.creeper.hurt", 1, 1, location of {_shooter}, all players)
    while {_projectile} is alive:
        wait 1 tick
        draw 5 green dust particle at location of {_projectile}

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {-%{_projectile}%::spawn creeper} is set:
        delete {-%{_projectile}%::spawn creeper}
        set {_fuse} to "fuse" of "creeper" at {_level}
        set {_damage} to "damage" of "creeper" at {_level}
        set {_radius} to "radius" of "creeper" at {_level}
        spawn creeper at {_projectile}:
            set max health of creeper to 1
            set movement speed attribute of creeper to 0.3
            set scale attribute of creeper to 0.3
            creeper.setMaxFuseTicks({_fuse})
            set {-%creeper%::damage} to {_damage}
            set {-%creeper%::radius} to {_radius}
            set {-%creeper%::owner} to {_shooter}
            set {_creeper} to creeper
        while {_creeper} is alive:
            wait 12 ticks
            damage {_creeper} by 0.1
            reset no damage time of {_creeper}

on explode:
    {-%event-entity%::damage} is set
    cancel event
    playEnchantmentSound("combat", "entity.generic.explode", 1, 1, location of event-entity, all players)
    draw ({-%event-entity%::radius} * 20) explosion particle at (location of event-entity)

on damage:
    {-%attacker%::damage} is set
    cancel event
    loop living entities in radius {-%attacker%::radius} around location of victim:
        {-%attacker%::owner} isn't loop-entity
        damage(loop-entity, attacker, {-%attacker%::damage})

on target:
    {-%entity%::owner} is set
    target is {-%entity%::owner}
    cancel event