bow enchantment:
    id: "dash"
    display: "&f<sprite:items:item/ender_pearl> &5Dash"
    max level: 5
    priority: 0
    item: ender pearl (item type)
    cost: "normal"

    ability:
        id: "dash"
        bind: "offhand"

        > "cooldown":
            lvl. 1: 20 seconds
            lvl. 2: 18 seconds
            lvl. 3: 15 seconds
            lvl. 4: 12 seconds
            lvl. 5: 10 seconds

        > "distance":
            lvl. 1: 12
            lvl. 2: 14
            lvl. 3: 16
            lvl. 4: 18
            lvl. 5: 22

local function getDescription(level: integer) :: string:
    set {_distance} to "distance" of "dash" at {_level}
    return "&e[<dash>] &7dash forward &f%{_distance}%m"

local function dash(player: player, level: integer) :: boolean:
    set {_distance} to "distance" of "dash" at {_level}
    dashPlayer({_player}, {_distance})
    return true

local function dashPlayer(player: player, distance: number):
    set {_start} to location of {_player}
    set {_speed} to {_distance} / 2.184

    push {_player} horizontally forward at speed {_speed}

    loop 40 times:
        wait 1 tick

        set {_current} to location of {_player}

        set y-coordinate of {_current} to y-coordinate of {_start}
        set {_travelled} to distance between {_start} and {_current}

        if {_travelled} >= {_distance}:
            set {_velocity} to velocity of {_player}
            set x component of {_velocity} to 0
            set z component of {_velocity} to 0
            set velocity of {_player} to {_velocity}
            stop

        set {_horizontalVelocity} to velocity of {_player}
        set y component of {_horizontalVelocity} to 0

        if vector length of {_horizontalVelocity} < 0.02:
            stop
