on load:
    create bow enchantment named "fatality":
        set enchantment display to "&f<sprite:items:item/netherite_axe> &4Fatality"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to netherite axe

        level values for "multiplier":
            set level 1 to 0.2
            set level 2 to 0.25
            set level 3 to 0.3
            set level 4 to 0.4
            set level 5 to 0.5

        level values for "health threshold":
            set level 1 to 0.33
            set level 2 to 0.33
            set level 3 to 0.33
            set level 4 to 0.33
            set level 5 to 0.33

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_health threshold} to "health threshold" of "fatality" at {_level}
    set {_multiplier} to "multiplier" of "fatality" at {_level}
    return "when the victim is below &f%{_health threshold} * 100%%%<sprite:gui:hud/heart/full>&8, &7increases dmg by &f%{_multiplier} * 100%%%"

local function onAttack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number = {_}) :: number:
    set {_health threshold} to "health threshold" of "fatality" at {_level}
    if {_victim}'s health / {_victim}'s max health <= {_health threshold}:
        set {_multiplier} to "multiplier" of "fatality" at {_level}
        playEnchantmentSound("combat", "entity.player.attack.strong", 1, 0.1, location of {_victim}, all players)
        return {_damage} * {_multiplier}
