on load:
    setting("fatality", "display", value: "&f<sprite:items:item/netherite_axe> &4Fatality")
    setting("fatality", "max level", value: 5)
    setting("fatality", "priority", value: 0)
    setting("fatality", "type", value: "bow")
    setting("fatality", "item", value: netherite axe)

    setting("fatality", "multiplier", l1: 0.2, l2: 0.25, l3: 0.3, l4: 0.4, l5: 0.5)
    setting("fatality", "health threshold", l1: 0.33, l2: 0.33, l3: 0.33, l4: 0.33, l5: 0.33)

    setting("fatality", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("fatality", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "when the victim is below %get_setting("fatality", "health threshold", {_level}) * 100%%% health, increases dmg by %get_setting("fatality", "multiplier", {_level}) * 100%%%"

local function onattack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number = {_}) :: number:
    if {_victim}'s health / {_victim}'s max health <= get_setting("fatality", "health threshold", {_level}):
        play sound "entity.player.attack.strong" with volume 1 and pitch 0.1 at {_victim}
        return {_damage} * get_setting("fatality", "multiplier", {_level})