on load:
    setting("frostbite", "display", value: "&f<sprite:blocks:block/powder_snow> &fFrostbite")
    setting("frostbite", "max", value: 5)
    setting("frostbite", "priority", value: 10)
    setting("frostbite", "type", value: "bow")
    setting("frostbite", "item", value: snow block (item))

    setting("frostbite", "threshold", l1: 0.75, l2: 0.75, l3: 0.75, l4: 0.75, l5: 0.75)
    setting("frostbite", "chance", l1: 25, l2: 26, l3: 27, l4: 28, l5: 30)

    setting("frostbite", "duration", l1: 3 seconds, l2: 3 seconds, l3: 4 seconds, l4: 4 seconds, l5: 5 seconds)
    setting("frostbite", "damage", l1: 0.35, l2: 0.38, l3: 0.4, l4: 0.42, l5: 0.45)

    setting("frostbite", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("frostbite", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "freeze victim for %time_format(get_setting("frostbite", "duration", {_level}))% and do %get_setting("frostbite", "damage", {_level})%&f<sprite:gui:hud/heart/full>&7/s"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        play sound "block.powder_snow.break" at volume 1 and pitch 0.1 at {_shooter}
        add 1 minute to freeze time of {_victim}
        run 0 ticks later:
            loop seconds of get_setting("frostbite", "duration", {_level}) times:
                damage({_victim}, {_shooter}, get_setting("frostbite", "damage", {_level}))
                if {_victim} is dead:
                    stop loop
                wait 1 second
        wait get_setting("frostbite", "duration", {_level})
        remove 1 minute from freeze time of {_victim}