on load:
    create bow enchantment named "frostbite":
        set enchantment display to "&f<sprite:blocks:block/powder_snow> &fFrostbite"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to snow block (item)

        level values for "threshold":
            set level 1 to 0.75
            set level 2 to 0.75
            set level 3 to 0.75
            set level 4 to 0.75
            set level 5 to 0.75

        level values for "chance":
            set level 1 to 25
            set level 2 to 26
            set level 3 to 27
            set level 4 to 28
            set level 5 to 30

        level values for "duration":
            set level 1 to 3 seconds
            set level 2 to 3 seconds
            set level 3 to 4 seconds
            set level 4 to 4 seconds
            set level 5 to 5 seconds

        level values for "damage":
            set level 1 to 0.35
            set level 2 to 0.38
            set level 3 to 0.4
            set level 4 to 0.42
            set level 5 to 0.45

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of {_level} for "frostbite"
    set {_damage} to "damage" of {_level} for "frostbite"
    return "freeze victim for %time_format({_duration})% and do %{_damage}%&f<sprite:gui:hud/heart/full>&7/s"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_duration} to "duration" of {_level} for "frostbite"
        set {_damage} to "damage" of {_level} for "frostbite"
        play sound "block.powder_snow.break" at volume 1 and pitch 0.1 at {_shooter}
        add 1 minute to freeze time of {_victim}
        run 0 ticks later:
            loop seconds of {_duration} times:
                damage({_victim}, {_shooter}, {_damage})
                if {_victim} is dead:
                    stop loop
                wait 1 second
        wait {_duration}
        remove 1 minute from freeze time of {_victim}
