bow enchantment:
    id: "frostbite"
    display: "&f<sprite:blocks:block/powder_snow> &fFrostbite"
    max level: 5
    priority: 10
    item: snow block (item)
    cost: "normal"

    > "threshold":
        lvl. 1: 0.75
        lvl. 2: 0.75
        lvl. 3: 0.75
        lvl. 4: 0.75
        lvl. 5: 0.75

    > "chance":
        lvl. 1: 25
        lvl. 2: 26
        lvl. 3: 27
        lvl. 4: 28
        lvl. 5: 30

    > "duration":
        lvl. 1: 3 seconds
        lvl. 2: 3 seconds
        lvl. 3: 4 seconds
        lvl. 4: 4 seconds
        lvl. 5: 5 seconds

    > "damage":
        lvl. 1: 0.35
        lvl. 2: 0.38
        lvl. 3: 0.4
        lvl. 4: 0.42
        lvl. 5: 0.45

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of "frostbite" at {_level}
    set {_damage} to "damage" of "frostbite" at {_level}
    return "freeze victim for &f%timeFormat({_duration})% &7and do &f%{_damage}%&f<sprite:gui:hud/heart/full>&8/&fs"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_duration} to "duration" of "frostbite" at {_level}
        set {_damage} to "damage" of "frostbite" at {_level}
        playEnchantmentSound("combat", "block.powder_snow.break", 1, 0.1, location of {_shooter}, all players)
        add 1 minute to freeze time of {_victim}
        run 0 ticks later:
            loop seconds of {_duration} times:
                damage({_victim}, {_shooter}, {_damage})
                if {_victim} is dead:
                    stop loop
                wait 1 second
        wait {_duration}
        remove 1 minute from freeze time of {_victim}