bow enchantment:
    id: "grounding"
    display: "<sprite:gui:hud/locator_bar_arrow_down> &9Grounding"
    max level: 5
    priority: 0
    item: glow squid spawn egg
    cost: "normal"

    > "chance":
        lvl. 1: 30
        lvl. 2: 40
        lvl. 3: 50
        lvl. 4: 60

    > "threshold":
        lvl. 1: 0.5
        lvl. 2: 0.5
        lvl. 3: 0.5
        lvl. 4: 0.5
        lvl. 5: 0.5

    > "duration":
        lvl. 1: 10 seconds
        lvl. 2: 11 seconds
        lvl. 3: 12 seconds
        lvl. 4: 13 seconds
        lvl. 5: 15 seconds

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of "grounding" at {_level}
    return "Ground a player&8, &7applying &f%effectDisplay("elytra disable", customDuration: {_duration}, showAmplifier: false)%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a player:
        set {_duration} to "duration" of "grounding" at {_level}
        playEnchantmentSound("combat", "entity.shulker.hurt", 1, 1, location of {_victim}, all players)
        set gliding of {_victim} to false
        set cooldown of elytra for {_victim} to {_duration}

on gliding state change:
    if gliding state of player is false:
        cooldown of elytra for player > 0 seconds
        cancel event