on load:
    create bow enchantment named "grounding":
        set enchantment display to "<sprite:gui:hud/locator_bar_arrow_down> &9Grounding"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to glow squid spawn egg

        level values for "chance":
            set level 1 to 30
            set level 2 to 40
            set level 3 to 50
            set level 4 to 60

        level values for "threshold":
            set level 1 to 0.5
            set level 2 to 0.5
            set level 3 to 0.5
            set level 4 to 0.5
            set level 5 to 0.5

        level values for "duration":
            set level 1 to 10 seconds
            set level 2 to 11 seconds
            set level 3 to 12 seconds
            set level 4 to 13 seconds
            set level 5 to 15 seconds

        level values for "xp cost":
            set level 2 to 16_000
            set level 3 to 120_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 24_000
            set level 3 to 200_000
            set level 4 to 500_000
            set level 5 to 1_200_000

local function getDescription(level: integer) :: string:
    set {_duration} to "duration" of "grounding" at {_level}
    return "Ground a player&8, &7applying &f%effectDisplay("elytra disable", customDuration: {_duration}, showAmplifier: false)%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a player:
        set {_duration} to "duration" of "grounding" at {_level}
        playEnchantmentSound("combat", "entity.shulker.hurt", 1, 1, location of {_victim}, all players)
        set gliding of {_victim} to false
        set cooldown of elytra for {_victim} to {_duration}

on gliding state change:
    if gliding state of player is false:
        cooldown of elytra for player > 0 seconds
        cancel event
