on load:
    create bow enchantment named "leech":
        set enchantment display to "&f<sprite:gui:hud/heart/full> &2Leech"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to regeneration potion item

        level values for "cooldown":
            set level 1 to 9 seconds
            set level 2 to 8 seconds
            set level 3 to 7 seconds
            set level 4 to 6 seconds
            set level 5 to 5 seconds

        level values for "heal percentage":
            set level 1 to 0.15
            set level 2 to 0.2
            set level 3 to 0.25
            set level 4 to 0.3
            set level 5 to 0.35

        level values for "dust cost":
            set level 2 to 20
            set level 3 to 100
            set level 4 to 2_300
            set level 5 to 6_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 1_000_000
            set level 5 to 3_100_000

local function getDescription(level: integer) :: string:
    set {_heal percentage} to "heal percentage" of "leech" at {_level}
    return "heals for &f%{_heal percentage} * 100%%% &7of damage over &f3s"

local function onAttack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    set {_heal percentage} to "heal percentage" of "leech" at {_level}
    loop 3 times:
        wait 1 second
        heal({_shooter}, ({_heal percentage} * {_damage}) / 3)
        playEnchantmentSound("combat", "entity.witch.drink", 1, 1, location of {_shooter}, all players)
        show 5 heart particles at {_shooter}'s head