on load:
    setting("leech", "display", value: "&f<sprite:gui:hud/heart/full> &2Leech")
    setting("leech", "max", value: 5)
    setting("leech", "priority", value: 10)
    setting("leech", "type", value: "bow")
    setting("leech", "item", value: regeneration potion item)

    setting("leech", "cooldown", l1: 9 seconds, l2: 8 seconds, l3: 7 seconds, l4: 6 seconds, l5: 5 seconds)

    setting("leech", "heal percentage", l1: 0.15, l2: 0.2, l3: 0.25, l4: 0.3, l5: 0.35)

    setting("leech", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("leech", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "heals for %get_setting("leech", "heal percentage", {_level}) * 100%%% dmg over 3 seconds"

local function onattack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    loop 3 times:
        wait 1 second
        heal({_shooter}, (get_setting("leech", "heal percentage", {_level}) * {_damage}) / 3)
        play sound "entity.witch.drink" at volume 1 and pitch 1 at {_shooter}
        show 5 heart particles at {_shooter}'s head