bow enchantment:
    id: "leech"
    display: "&f<sprite:gui:hud/heart/full> &2Leech"
    max level: 5
    priority: 10
    item: regeneration potion item
    cost: "normal"

    > "cooldown":
        lvl. 1: 9 seconds
        lvl. 2: 8 seconds
        lvl. 3: 7 seconds
        lvl. 4: 6 seconds
        lvl. 5: 5 seconds

    > "heal percentage":
        lvl. 1: 0.15
        lvl. 2: 0.2
        lvl. 3: 0.25
        lvl. 4: 0.3
        lvl. 5: 0.35

local function getDescription(level: integer) :: string:
    set {_heal percentage} to "heal percentage" of "leech" at {_level}
    return "heals for &f%{_heal percentage} * 100%%% &7of damage over &f3s"

local function onAttack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    set {_heal percentage} to "heal percentage" of "leech" at {_level}
    loop 3 times:
        wait 1 second
        heal({_shooter}, ({_heal percentage} * {_damage}) / 3)
        playEnchantmentSound("combat", "entity.witch.drink", 1, 1, location of {_shooter}, all players)
        show 5 heart particles at {_shooter}'s head