on load:
    create bow enchantment named "mark":
        set enchantment display to "&f<sprite:items:item/bone> &dMark"
        set enchantment max level to 5
        set enchantment priority to -1
        set enchantment item to bone

        level values for "cooldown":
            set level 1 to 20 seconds
            set level 2 to 20 seconds
            set level 3 to 20 seconds
            set level 4 to 20 seconds
            set level 5 to 20 seconds

        level values for "multiplier":
            set level 1 to 0.1
            set level 2 to 0.12
            set level 3 to 0.15
            set level 4 to 0.17
            set level 5 to 0.2

        level values for "duration":
            set level 1 to 15 seconds
            set level 2 to 15 seconds
            set level 3 to 15 seconds
            set level 4 to 15 seconds
            set level 5 to 15 seconds

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "mark" at {_level}
    set {_duration} to "duration" of "mark" at {_level}
    return "mark the victim&8, &7increasing dmg taken by &f%{_multiplier} * 100%%% &7for &f%timeFormat({_duration})%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_multiplier} to "multiplier" of "mark" at {_level}
        set {_duration} to "duration" of "mark" at {_level}
        set {-marked::%{_victim}%} to now
        set {-marked level::%{_victim}%} to {_level}
        set {-marked multiplier::%{_victim}%} to {_multiplier}
        add potion effect of glowing for {_duration} to {_victim}'s potion effects
        playEnchantmentSound("combat", "entity.glow_squid.squirt", 1, 1, location of {_victim}, all players)

on damage with priority monitor:
    event isn't canceled
    damage > 0
    {-marked::%victim%} is set
    set {_dif} to difference between now and {-marked::%victim%}
    if {_dif} < "duration" of "mark" at {-marked level::%victim%}:
        set damage to damage * (1 + {-marked multiplier::%victim%})
