on load:
    setting("mark", "display", value: "&f<sprite:items:item/bone> &dMark")
    setting("mark", "max level", value: 5)
    setting("mark", "priority", value: -1)
    setting("mark", "type", value: "bow")
    setting("mark", "item", value: bone)


    setting("mark", "cooldown", l1: 20 seconds, l2: 20 seconds, l3: 20 seconds, l4: 20 seconds, l5: 20 seconds)

    setting("mark", "multiplier", l1: 0.1, l2: 0.12, l3: 0.15, l4: 0.17, l5: 0.2)
    setting("mark", "duration", value: 15 seconds)

    setting("mark", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("mark", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "mark the victim, increasing dmg taken by %get_setting("mark", "multiplier", {_level}) * 100%%% for %time_format(get_setting("mark", "duration"))%"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {-marked::%{_victim}%} to now
        set {-marked multiplier::%{_victim}%} to get_setting("mark", "multiplier", {_level})
        add potion effect of glowing for get_setting("mark", "duration") to {_victim}'s potion effects
        play sound "entity.glow_squid.squirt" with volume 1 and pitch 1 at {_victim}

on damage with priority monitor:
    event isn't canceled
    damage > 0
    {-marked::%victim%} is set
    set {_dif} to difference between now and {-marked::%victim%}
    if {_dif} < get_setting("mark", "duration"):
        set damage to damage * (1 + {-marked multiplier::%victim%})