bow enchantment:
    id: "mark"
    display: "&f<sprite:items:item/bone> &dMark"
    max level: 5
    priority: -1
    item: bone
    cost: "normal"

    > "cooldown":
        lvl. 1: 20 seconds
        lvl. 2: 20 seconds
        lvl. 3: 20 seconds
        lvl. 4: 20 seconds
        lvl. 5: 20 seconds

    > "multiplier":
        lvl. 1: 0.1
        lvl. 2: 0.12
        lvl. 3: 0.15
        lvl. 4: 0.17
        lvl. 5: 0.2

    > "duration":
        lvl. 1: 15 seconds
        lvl. 2: 15 seconds
        lvl. 3: 15 seconds
        lvl. 4: 15 seconds
        lvl. 5: 15 seconds

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "mark" at {_level}
    set {_duration} to "duration" of "mark" at {_level}
    return "mark the victim&8, &7increasing dmg taken by &f%{_multiplier} * 100%%% &7for &f%timeFormat({_duration})%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_multiplier} to "multiplier" of "mark" at {_level}
        set {_duration} to "duration" of "mark" at {_level}
        set {-marked::%{_victim}%} to now
        set {-marked level::%{_victim}%} to {_level}
        set {-marked multiplier::%{_victim}%} to {_multiplier}
        add potion effect of glowing for {_duration} to {_victim}'s potion effects
        playEnchantmentSound("combat", "entity.glow_squid.squirt", 1, 1, location of {_victim}, all players)

on damage with priority monitor:
    event isn't canceled
    damage > 0
    {-marked::%victim%} is set
    set {_dif} to difference between now and {-marked::%victim%}
    if {_dif} < "duration" of "mark" at {-marked level::%victim%}:
        set damage to damage * (1 + {-marked multiplier::%victim%})