on load:
    create bow enchantment named "meteor":
        set enchantment display to "&f<sprite:items:item/fire_charge> &cMeteor"
        set enchantment max level to 5
        set enchantment priority to 100
        set enchantment item to fire charge

        level values for "manual cooldown::onhit":
            set level 1 to true
            set level 2 to true
            set level 3 to true
            set level 4 to true
            set level 5 to true

        level values for "cooldown":
            set level 1 to 20 seconds
            set level 2 to 20 seconds
            set level 3 to 20 seconds
            set level 4 to 20 seconds
            set level 5 to 20 seconds

        level values for "threshold":
            set level 1 to 1
            set level 2 to 1
            set level 3 to 1
            set level 4 to 1
            set level 5 to 1

        level values for "damage per block":
            set level 1 to 0.2
            set level 2 to 0.22
            set level 3 to 0.25
            set level 4 to 0.27
            set level 5 to 0.3

        level values for "aoe per block":
            set level 1 to 0.1
            set level 2 to 0.12
            set level 3 to 0.15
            set level 4 to 0.17
            set level 5 to 0.2

        level values for "max damage":
            set level 1 to 5
            set level 2 to 5
            set level 3 to 5
            set level 4 to 5
            set level 5 to 5

        level values for "max aoe":
            set level 1 to 4
            set level 2 to 4
            set level 3 to 4
            set level 4 to 4
            set level 5 to 4

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_damage per block} to "damage per block" of {_level} for "meteor"
    set {_aoe per block} to "aoe per block" of {_level} for "meteor"
    return "create an explosion when shot from above&8, &f%{_damage per block}%<sprite:gui:hud/heart/full>&8/&7block&8, &7AOE &f%{_aoe per block}%m&8/&7block"

local function onshoot(shooter: entity, tool: item, projectile: entity, level: integer, force: number):
    wait 3 ticks
    if y coordinate of {_projectile} < y coordinate of {_shooter}:
        set {-%{_projectile}%::meteor} to location of {_projectile}

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    {-%{_projectile}%::meteor} is set
    set {_distance} to distance between {-%{_projectile}%::meteor} and location of {_victim}
    set {_damage} to clamp({_distance} * "damage per block" of {_level} for "meteor", 0, "max damage" of {_level} for "meteor")
    set {_aoe} to clamp({_distance} * "aoe per block" of {_level} for "meteor", 0, "max aoe" of {_level} for "meteor")
    {_damage} > 0
    play sound "entity.generic.explode" with volume 1 and pitch 1 at location of {_victim}
    loop all blocks in radius {_aoe} around {_victim}:
        show explosion particle at loop-block
        "%blocks at loop-block%" doesn't contain "spawn"
        y coordinate of loop-block > 0
        loop-block isn't bedrock or black concrete
        set loop-block to air
    loop all living entities in radius {_aoe} around {_victim}:
        damage(loop-value, {_shooter}, {_damage})
