bow enchantment:
    id: "meteor"
    display: "&f<sprite:items:item/fire_charge> &cMeteor"
    max level: 5
    priority: 100
    item: fire charge
    cost: "normal"

    > "manual cooldown::onHit":
        lvl. 1: true
        lvl. 2: true
        lvl. 3: true
        lvl. 4: true
        lvl. 5: true

    > "cooldown":
        lvl. 1: 20 seconds
        lvl. 2: 20 seconds
        lvl. 3: 20 seconds
        lvl. 4: 20 seconds
        lvl. 5: 20 seconds

    > "threshold":
        lvl. 1: 100%
        lvl. 2: 100%
        lvl. 3: 100%
        lvl. 4: 100%
        lvl. 5: 100%

    > "damage per block":
        lvl. 1: 0.2
        lvl. 2: 0.22
        lvl. 3: 0.25
        lvl. 4: 0.27
        lvl. 5: 0.3

    > "aoe per block":
        lvl. 1: 0.1
        lvl. 2: 0.12
        lvl. 3: 0.15
        lvl. 4: 0.17
        lvl. 5: 0.2

    > "max damage":
        lvl. 1: 5
        lvl. 2: 5
        lvl. 3: 5
        lvl. 4: 5
        lvl. 5: 5

    > "max aoe":
        lvl. 1: 4
        lvl. 2: 4
        lvl. 3: 4
        lvl. 4: 4
        lvl. 5: 4

local function getDescription(level: integer) :: string:
    set {_damage per block} to "damage per block" of "meteor" at {_level}
    set {_aoe per block} to "aoe per block" of "meteor" at {_level}
    return "create an explosion when shot from above&8, &f%{_damage per block}%<sprite:gui:hud/heart/full>&8/&7block&8, &7AOE &f%{_aoe per block}%m&8/&7block"

local function onShoot(shooter: entity, tool: item, projectile: entity, level: integer, force: number):
    wait 3 ticks
    if y coordinate of {_projectile} < y coordinate of {_shooter}:
        set {-%{_projectile}%::meteor} to location of {_projectile}

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    {-%{_projectile}%::meteor} is set
    set {_distance} to distance between {-%{_projectile}%::meteor} and location of {_victim}
    set {_damage} to clamp({_distance} * "damage per block" of "meteor" at {_level}, 0, "max damage" of "meteor" at {_level})
    set {_aoe} to clamp({_distance} * "aoe per block" of "meteor" at {_level}, 0, "max aoe" of "meteor" at {_level})
    {_damage} > 0
    playEnchantmentSound("combat", "entity.generic.explode", 1, 1, location of {_victim}, all players)
    loop all blocks in radius {_aoe} around {_victim}:
        show explosion particle at loop-block
        "%blocks at loop-block%" doesn't contain "spawn"
        y coordinate of loop-block > 0
        loop-block isn't bedrock or black concrete
        set loop-block to air
    loop all living entities in radius {_aoe} around {_victim}:
        damage(loop-value, {_shooter}, {_damage})