on load:
    setting("meteor", "display", value: "&f<sprite:items:item/fire_charge> &cMeteor")
    setting("meteor", "max", value: 5)
    setting("meteor", "priority", value: 100)
    setting("meteor", "type", value: "bow")
    setting("meteor", "item", value: fire charge)

    setting("meteor", "manual cooldown::onhit", l1: true, l2: true, l3: true, l4: true, l5: true)
    setting("meteor", "cooldown", l1: 20 seconds, l2: 20 seconds, l3: 20 seconds, l4: 20 seconds, l5: 20 seconds)
    setting("meteor", "threshold", l1: 1, l2: 1, l3: 1, l4: 1, l5: 1)

    setting("meteor", "damage per block", l1: 0.2, l2: 0.22, l3: 0.25, l4: 0.27, l5: 0.3)
    setting("meteor", "max damage", value: 5)
    setting("meteor", "aoe per block", l1: 0.1, l2: 0.12, l3: 0.15, l4: 0.17, l5: 0.2)
    setting("meteor", "max aoe", value: 4)

    setting("meteor", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("meteor", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "create an explosion when shot from above, %get_setting("meteor", "damage per block", {_level})%&f<sprite:gui:hud/heart/full>&7/block, %get_setting("meteor", "aoe per block", {_level})%m/block"

local function onshoot(shooter: entity, tool: item, projectile: entity, level: integer, force: number):
    wait 3 ticks
    if y coordinate of {_projectile} < y coordinate of {_shooter}:
        set {-%{_projectile}%::meteor} to location of {_projectile}

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    {-%{_projectile}%::meteor} is set
    set {_distance} to distance between {-%{_projectile}%::meteor} and location of {_victim}
    set {_damage} to clamp({_distance} * get_setting("meteor", "damage per block", {_level}), 0, get_setting("meteor", "max damage"))
    set {_aoe} to clamp({_distance} * get_setting("meteor", "aoe per block", {_level}), 0, get_setting("meteor", "max aoe"))
    {_damage} > 0
    play sound "entity.generic.explode" with volume 1 and pitch 1 at location of {_victim}
    loop all blocks in radius {_aoe} around {_victim}:
        show explosion particle at loop-block
        "%blocks at loop-block%" doesn't contain "spawn"
        y coordinate of loop-block > 0
        loop-block isn't bedrock
        set loop-block to air
    loop all living entities in radius {_aoe} around {_victim}:
        damage(loop-value, {_shooter}, {_damage})