bow enchantment:
    id: "precision"
    display: "&f<sprite:blocks:block/target_side> &ePrecision"
    max level: 5
    priority: 0
    item: target item
    cost: "normal"

    > "multiplier":
        lvl. 1: 0.1
        lvl. 2: 0.15
        lvl. 3: 0.2
        lvl. 4: 0.25
        lvl. 5: 0.3

    > "max multiplier":
        lvl. 1: 1
        lvl. 2: 1
        lvl. 3: 1
        lvl. 4: 1
        lvl. 5: 1

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "precision" at {_level}
    return "hitting a shot increases arrow damage by &f%{_multiplier} * 100%%%&8. &7missing a shot resets the multiplier"

local function onAttack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    {_shooter} isn't {_victim}
    if {-shots hit in a row::%{_shooter}%} > 1:
        set {_multiplier} to "multiplier" of "precision" at {_level}
        set {_max multiplier} to "max multiplier" of "precision" at {_level}
        playEnchantmentSound("combat", "entity.arrow.hit", 1, 1.5, location of {_victim}, all players)
        playEnchantmentSound("combat", "block.note_block.pling", 1, 0.5 + (clamp({-shots hit in a row::%{_shooter}%} * ({_multiplier} * 1.5), 0, 1.5)), location of {_shooter}, all players)
        return {_damage} * (clamp({-shots hit in a row::%{_shooter}%} * {_multiplier}, 0, {_max multiplier}))

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} isn't a living entity:
        delete {-shots hit in a row::%{_shooter}%}
    else:
        add 1 to {-shots hit in a row::%{_shooter}%}