on load:
    create bow enchantment named "precision":
        set enchantment display to "&f<sprite:blocks:block/target_side> &ePrecision"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to target item

        level values for "multiplier":
            set level 1 to 0.1
            set level 2 to 0.15
            set level 3 to 0.2
            set level 4 to 0.25
            set level 5 to 0.3

        level values for "max multiplier":
            set level 1 to 1
            set level 2 to 1
            set level 3 to 1
            set level 4 to 1
            set level 5 to 1

        level values for "dust cost":
            set level 2 to 20
            set level 3 to 100
            set level 4 to 450
            set level 5 to 1_100

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_multiplier} to "multiplier" of "precision" at {_level}
    return "hitting a shot increases arrow damage by &f%{_multiplier} * 100%%%&8. &7missing a shot resets the multiplier"

local function onAttack(shooter: entity, victim: entity, projectile: entity, level: integer, force: number, damage: number) :: number:
    {_shooter} isn't {_victim}
    if {-shots hit in a row::%{_shooter}%} > 1:
        set {_multiplier} to "multiplier" of "precision" at {_level}
        set {_max multiplier} to "max multiplier" of "precision" at {_level}
        playEnchantmentSound("combat", "entity.arrow.hit", 1, 1.5, location of {_victim}, all players)
        playEnchantmentSound("combat", "block.note_block.pling", 1, 0.5 + (clamp({-shots hit in a row::%{_shooter}%} * ({_multiplier} * 1.5), 0, 1.5)), location of {_shooter}, all players)
        return {_damage} * (clamp({-shots hit in a row::%{_shooter}%} * {_multiplier}, 0, {_max multiplier}))

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} isn't a living entity:
        delete {-shots hit in a row::%{_shooter}%}
    else:
        add 1 to {-shots hit in a row::%{_shooter}%}