bow enchantment:
    id: "quiver"
    display: "&f<sprite:items:item/arrow> &6Quiver"
    max level: 5
    priority: 0
    item: arrow item
    cost: "normal"

    > "chance":
        lvl. 1: 20
        lvl. 2: 30
        lvl. 3: 40
        lvl. 4: 50

local function getDescription(level: integer) :: string:
    return "return your shot arrow"

local function onShoot(shooter: entity, tool: item, projectile: projectile, level: integer, force: number):
    wait 1 tick
    give {_shooter} 1 arrow