on load:
    create bow enchantment named "quiver":
        set enchantment display to "&f<sprite:items:item/arrow> &6Quiver"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to arrow item

        level values for "chance":
            set level 1 to 20
            set level 2 to 30
            set level 3 to 40
            set level 4 to 50

        level values for "dust cost":
            set level 2 to 20
            set level 3 to 100
            set level 4 to 450
            set level 5 to 1_100

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    return "return your shot arrow"

local function onShoot(shooter: entity, tool: item, projectile: projectile, level: integer, force: number):
    wait 1 tick
    give {_shooter} 1 arrow