on load:
    setting("quiver", "display", value: "&f<sprite:items:item/arrow> &6Quiver")
    setting("quiver", "max level", value: 5)
    setting("quiver", "priority", value: 0)
    setting("quiver", "type", value: "bow")
    setting("quiver", "item", value: arrow item)

    setting("quiver", "chance", l1: 20, l2: 30, l3: 40, l4: 50)

    setting("quiver", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("quiver", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "return your shot arrow"

local function onshoot(shooter: entity, tool: item, projectile: projectile, level: integer, force: number):
    wait 1 tick
    give {_shooter} 1 arrow