bow enchantment:
    id: "sniper"
    display: "&f<sprite:items:item/spyglass> &9Sniper"
    max level: 5
    priority: 0
    item: spyglass
    cost: "normal"

    > "scale":
        lvl. 1: 0.05
        lvl. 2: 0.06
        lvl. 3: 0.07
        lvl. 4: 0.08
        lvl. 5: 0.1

local function getDescription(level: integer) :: string:
    set {_scale} to "scale" of "sniper" at {_level}
    return "deals &f%{_scale}%<sprite:gui:hud/heart/full> &7per block traveled by the arrow"

local function onShoot(shooter: entity, tool: item, projectile: projectile, level: integer, force: number):
    set {-%{_projectile}%::starting} to location of {_projectile}

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    {_victim} is a living entity
    set {_scale} to "scale" of "sniper" at {_level}
    set {_distance} to distance between location of {_projectile} and {-%{_projectile}%::starting}
    set {_damage} to {_distance} * {_scale}
    send action bar "&lSNIPER: &f%{_damage}%&f<sprite:gui:hud/heart/full> &7, &lDISTANCE: &f%{_distance}%" to {_shooter}
    damage({_victim}, {_shooter}, {_damage})
    delete {-%{_projectile}%::starting}