on load:
    create bow enchantment named "sniper":
        set enchantment display to "&f<sprite:items:item/spyglass> &9Sniper"
        set enchantment max level to 5
        set enchantment priority to 0
        set enchantment item to spyglass

        level values for "scale":
            set level 1 to 0.05
            set level 2 to 0.06
            set level 3 to 0.07
            set level 4 to 0.08
            set level 5 to 0.1

        level values for "dust cost":
            set level 2 to 30
            set level 3 to 150
            set level 4 to 2_800
            set level 5 to 7_600

        level values for "money cost":
            set level 2 to 30_000
            set level 3 to 175_000
            set level 4 to 1_200_000
            set level 5 to 3_800_000

local function getDescription(level: integer) :: string:
    set {_scale} to "scale" of "sniper" at {_level}
    return "deals &f%{_scale}%<sprite:gui:hud/heart/full> &7per block traveled by the arrow"

local function onShoot(shooter: entity, tool: item, projectile: projectile, level: integer, force: number):
    set {-%{_projectile}%::starting} to location of {_projectile}

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    {_victim} is a living entity
    set {_scale} to "scale" of "sniper" at {_level}
    set {_distance} to distance between location of {_projectile} and {-%{_projectile}%::starting}
    set {_damage} to {_distance} * {_scale}
    send action bar "&lSNIPER: &f%{_damage}%&f<sprite:gui:hud/heart/full> &7, &lDISTANCE: &f%{_distance}%" to {_shooter}
    damage({_victim}, {_shooter}, {_damage})
    delete {-%{_projectile}%::starting}