on load:
    setting("starve", "display", value: "&f<sprite:gui:hud/food_full> &6Starve")
    setting("starve", "max level", value: 5)
    setting("starve", "priority", value: 10)
    setting("starve", "type", value: "bow")
    setting("starve", "item", value: rotten flesh)

    setting("starve", "threshold", l1: 0.75, l2: 0.75, l3: 0.75, l4: 0.75, l5: 0.75)

    setting("starve", "hunger", l1: 0.5, l2: 0.6, l3: 0.7, l4: 0.8, l5: 1)

    setting("starve", "xp cost", l2: 20_000, l3: 100_000, l4: 400_000, l5: 1_000_000)
    setting("starve", "money cost", l2: 25_000, l3: 150_000, l4: 500_000, l5: 1_250_000)

local function getDescription(level: integer) :: string:
    return "removes %get_setting("starve", "hunger", {_level})% hunger from the victim"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_victim}'s food level to clamp({_victim}'s food level - get_setting("starve", "hunger", {_level}), 0, 10)
        play sound "entity.zoglin.ambient" with volume 1 and pitch 1 at {_victim}