bow enchantment:
    id: "starve"
    display: "&f<sprite:gui:hud/food_full> &6Starve"
    max level: 5
    priority: 10
    item: rotten flesh
    cost: "normal"

    > "threshold":
        lvl. 1: 75%
        lvl. 2: 75%
        lvl. 3: 75%
        lvl. 4: 75%
        lvl. 5: 75%

    > "hunger":
        lvl. 1: 0.5
        lvl. 2: 0.6
        lvl. 3: 0.7
        lvl. 4: 0.8
        lvl. 5: 1

local function getDescription(level: integer) :: string:
    set {_hunger} to "hunger" of "starve" at {_level}
    return "removes &f%{-effect::saturation::display}%%{_hunger}% &7from the victim"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_hunger} to "hunger" of "starve" at {_level}
        set {_victim}'s food level to clamp({_victim}'s food level - {_hunger}, 0, 10)
        playEnchantmentSound("combat", "entity.zoglin.ambient", 1, 1, location of {_victim}, all players)