on load:
    create bow enchantment named "starve":
        set enchantment display to "&f<sprite:gui:hud/food_full> &6Starve"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to rotten flesh

        level values for "threshold":
            set level 1 to 0.75
            set level 2 to 0.75
            set level 3 to 0.75
            set level 4 to 0.75
            set level 5 to 0.75

        level values for "hunger":
            set level 1 to 0.5
            set level 2 to 0.6
            set level 3 to 0.7
            set level 4 to 0.8
            set level 5 to 1

        level values for "xp cost":
            set level 2 to 20_000
            set level 3 to 100_000
            set level 4 to 400_000
            set level 5 to 1_000_000

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_hunger} to "hunger" of "starve" at {_level}
    return "removes &f%{-effect::saturation::display}%%{_hunger}% &7from the victim"

local function onhit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_hunger} to "hunger" of "starve" at {_level}
        set {_victim}'s food level to clamp({_victim}'s food level - {_hunger}, 0, 10)
        playEnchantmentSound("combat", "entity.zoglin.ambient", 1, 1, location of {_victim}, all players)
