on load:
    create bow enchantment named "wither":
        set enchantment display to "&f<sprite:items:item/wither_spawn_egg> &7Wither"
        set enchantment max level to 5
        set enchantment priority to 10
        set enchantment item to wither skeleton skull

        level values for "threshold":
            set level 1 to 0.5
            set level 2 to 0.5
            set level 3 to 0.5
            set level 4 to 0.5
            set level 5 to 0.5

        level values for "cooldown":
            set level 1 to 10 seconds
            set level 2 to 10 seconds
            set level 3 to 10 seconds
            set level 4 to 10 seconds
            set level 5 to 10 seconds

        level values for "effect":
            set level 1 to potion effect of wither 1 for 4 seconds
            set level 2 to potion effect of wither 1 for 5 seconds
            set level 3 to potion effect of wither 2 for 6 seconds
            set level 4 to potion effect of wither 2 for 7 seconds
            set level 5 to potion effect of wither 3 for 7 seconds

        level values for "dust cost":
            set level 2 to 20
            set level 3 to 100
            set level 4 to 450
            set level 5 to 1_100

        level values for "money cost":
            set level 2 to 25_000
            set level 3 to 150_000
            set level 4 to 500_000
            set level 5 to 1_250_000

local function getDescription(level: integer) :: string:
    set {_wither} to "effect" of "wither" at {_level}
    set {_blindness} to potion effect of blindness 1 for (duration of {_wither} / 2)
    set {_duration} to duration of {_wither}
    set {_amplifier} to amplifier of {_wither}
    return "applies &f%effectDisplay({_wither})% &7and &f%effectDisplay({_blindness})%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_effect} to "effect" of "wither" at {_level}
        set {_blindness} to potion effect of blindness 1 for (duration of {_effect} / 2)
        add {_effect} to {_victim}'s potion effects
        add {_blindness} to {_victim}'s potion effects
        playEnchantmentSound("combat", "entity.wither.shoot", 1, 1, location of {_victim}, all players)