bow enchantment:
    id: "wither"
    display: "&f<sprite:items:item/wither_spawn_egg> &7Wither"
    max level: 5
    priority: 10
    item: wither skeleton skull
    cost: "normal"

    > "threshold":
        lvl. 1: 50%
        lvl. 2: 50%
        lvl. 3: 50%
        lvl. 4: 50%
        lvl. 5: 50%

    > "cooldown":
        lvl. 1: 10 seconds
        lvl. 2: 10 seconds
        lvl. 3: 10 seconds
        lvl. 4: 10 seconds
        lvl. 5: 10 seconds

    > "effect":
        lvl. 1: potion effect of wither 1 for 4 seconds
        lvl. 2: potion effect of wither 1 for 5 seconds
        lvl. 3: potion effect of wither 2 for 6 seconds
        lvl. 4: potion effect of wither 2 for 7 seconds
        lvl. 5: potion effect of wither 3 for 7 seconds

local function getDescription(level: integer) :: string:
    set {_wither} to "effect" of "wither" at {_level}
    set {_blindness} to potion effect of blindness 1 for (duration of {_wither} / 2)
    set {_duration} to duration of {_wither}
    set {_amplifier} to amplifier of {_wither}
    return "applies &f%effectDisplay({_wither})% &7and &f%effectDisplay({_blindness})%"

local function onHit(shooter: entity, tool: item, projectile: entity, level: integer, force: number, victim: object):
    if {_victim} is a living entity:
        set {_effect} to "effect" of "wither" at {_level}
        set {_blindness} to potion effect of blindness 1 for (duration of {_effect} / 2)
        add {_effect} to {_victim}'s potion effects
        add {_blindness} to {_victim}'s potion effects
        playEnchantmentSound("combat", "entity.wither.shoot", 1, 1, location of {_victim}, all players)