using reflection

custom event "enchantment":
    pattern: [disabled:disabled] [ultimate:ultimate] (pickaxe:pickaxe|sword:sword|armor:armor|bow:bow) enchantment
    check:
        delete {-current ce::*}
        delete {-current ce ability::*}

        set {_type} to first element out of parse tags where [input isn't "ultimate" or "disabled"]
        set {-current ce::type} to {_type}

        if parse tags contains "ultimate":
            set {-current ce::ultimate} to true

        if parse tags contains "disabled":
            set {-current ce::disabled} to true

        continue

effect:
    patterns:
        id\: %string%
    usable in:
        custom event "enchantment"
    trigger:
        set {_id} to expr-1

        if {-current ce ability::active} is true:
            set {_enchantment} to {-current ce::name}

            set {-current ce ability::name} to {_id}

            set {-ce ability::%{_id}%::id} to {_id}
            set {-ce ability::%{_id}%::enchantment} to {_enchantment}

            if {-ce::%{_enchantment}%::abilities::*} doesn't contain {_id}:
                add {_id} to {-ce::%{_enchantment}%::abilities::*}

            stop

        set {-current ce::name} to {_id}

        set {-ce::%{_id}%::id} to {_id}
        set {-ce::%{_id}%::type} to {-current ce::type}

        if {-current ce::ultimate} is true:
            set {-ce::%{_id}%::ultimate} to true

        if {-current ce::disabled} is true:
            set {-ce::%{_id}%::disabled} to true

effect:
    patterns:
        (display:display|max level:max level|priority:priority|item:item|cost:cost)\: %object%
    usable in:
        custom event "enchantment"
    parse:
        set {_key} to first element out of parse tags
        continue
    trigger:
        set {_enchantment} to {-current ce::name}
        set {-ce::%{_enchantment}%::%{_key}%} to expr-1

condition > %string%:
    check:
        set {-current ce::level value key} to expr-1
        return true

effect:
    patterns:
        lvl[.] %integer%\: %object%
    usable in:
        custom event "enchantment"
    trigger:
        set {_enchantment} to {-current ce::name}
        set {_key} to {-current ce::level value key}
        set {-ce::%{_enchantment}%::%{_key}%::%expr-1%} to expr-2

expression %string% of %string% at %integer%:
    get:
        set {_key} to expr-1
        set {_enchantment} to expr-2
        set {_level} to expr-3

        set {_value} to {-ce::%{_enchantment}%::%{_key}%::%{_level}%}

        if {_value} isn't set:
            set {_max} to {-ce::%{_enchantment}%::max level}

            if {_max} is set:
                set {_maxValue} to {-ce::%{_enchantment}%::%{_key}%::%{_max}%}
                set {_previousValue} to {-ce::%{_enchantment}%::%{_key}%::%{_max} - 1%}

                if {_maxValue} is an instance of SkriptPotionEffect:
                    set {_maxValue} to ({_maxValue}.clone())
                    set {_maxDur} to duration of {_maxValue}
                    set {_prevDur} to duration of {_previousValue}
                    set {_maxAmp} to amplifier of {_maxValue}
                    set {_prevAmp} to amplifier of {_previousValue}

                    set {_durDiff} to {_maxDur} - {_prevDur}
                    set {_newDur} to {_maxDur} + ({_level} - {_max}) * {_durDiff}

                    set {_ampDiff} to {_maxAmp} - {_prevAmp}
                    set {_newAmp} to {_maxAmp} + ({_level} - {_max}) * {_ampDiff}

                    set {_type} to type of {_maxValue}
                    set {_value} to potion effect of {_type} {_newAmp} for {_newDur}

                else:
                    if {_level} > {_max}:
                        if {_maxValue} and {_previousValue} are set:
                            if {_maxValue} > {_previousValue}:
                                set {_difference} to {_maxValue} - {_previousValue}
                                set {_value} to {_maxValue} + ({_level} - {_max}) * {_difference}
                            else:
                                set {_ratio} to {_previousValue} / {_maxValue}
                                set {_value} to {_maxValue} / ({_ratio} ^ ({_level} - {_max}))

        return {_value}

import:
    org.skriptlang.skript.bukkit.potion.util.SkriptPotionEffect
