using reflection

condition ability:
    check:
        delete {-current ce ability::*}
        set {-current ce ability::active} to true
        return true

effect:
    patterns:
        bind\: %string%
    usable in:
        custom event "enchantment"
    trigger:
        set {_ability} to {-current ce ability::name}
        set {-ce ability::%{_ability}%::bind} to expr-1

expression ability function [of %-string%]:
    get:
        set {_current ability} to expr-1 ? {-current ce ability::name}
        return {-ce ability::%{_current ability}%::function}
    set:
        set {_current ability} to expr-1 ? {-current ce ability::name}
        set {-ce ability::%{_current ability}%::function} to change value

expression ability bind [of %-string% [for %-player%]]:
    get:
        set {_ability} to expr-1 ? {-current ce ability::name}
        set {_bind} to {-ce ability::%{_ability}%::bind}

        if expr-2 is set:
            set {_bind} to {ability bind::%expr-2%::%{_ability}%} ? {_bind}

        return {_bind}
    set:
        set {_ability} to expr-1 ? {-current ce ability::name}
        if expr-2 is set:
            set {ability bind::%expr-2%::%{_ability}%} to change value
        else:
            set {-ce ability::%{_ability}%::bind} to change value
    reset:
        set {_ability} to expr-1 ? {-current ce ability::name}
        if expr-2 is set:
            delete {ability bind::%expr-2%::%{_ability}%}
