import:
    org.bukkit.NamespacedKey
    org.bukkit.persistence.PersistentDataType
    org.bukkit.persistence.PersistentDataContainer
    org.bukkit.inventory.ItemStack
    org.bukkit.Material

on load:
    set {-enchant namespace} to new NamespacedKey("skript", "custom_enchantments")

###
[00:25:45 INFO]: reflect
[00:25:45 INFO]: write 1: 0.15 ms
[00:25:45 INFO]: read 20: 0.17 ms
[00:25:45 INFO]: 
[00:25:45 INFO]: variables
[00:25:45 INFO]: write 1: 0.01 ms
[00:25:45 INFO]: read 20: 0.06 ms
###
command /perf:
    trigger:
        send "reflect"
        set {_item} to new ItemStack(Material.DIAMOND_SWORD)
        set {_now} to current ns

        set {_item} to enchantItemNEW({_item}, "custom_enchant_1", 1)

        set {_elapsed} to (current ns - {_now}) / 1000000
        send "write 1: %{_elapsed}% ms"

        loop 20 times:
            set {_item} to enchantItemNEW({_item}, "custom_enchant_%loop-value%", 1)

        set {_now} to current ns

        set {_enchantments::*} to keyed getEnchantmentsNEW({_item})
        for {_ce}, {_level} in {_enchantments::*}:
            set {_} to {_}

        set {_elapsed} to (current ns - {_now}) / 1000000
        send "read %size of {_enchantments::*}%: %{_elapsed}% ms"

        send ""

        send "variables"
        set {_item} to new ItemStack(Material.DIAMOND_SWORD)
        set data tag "uuid" of {_item} to random uuid
        set {_uuid} to data tag "uuid" of {_item}
        delete {custom enchantments::%{_uuid}%::*}
        set {_now} to current ns

        set {custom enchantments::%{_uuid}%::custom_enchant_1} to 1

        set {_elapsed} to (current ns - {_now}) / 1000000
        send "write 1: %{_elapsed}% ms"

        loop 20 times:
            set {custom enchantments::%{_uuid}%::custom_enchant_%loop-value%} to 1

        set {_now} to current ns

        set {_uuid} to data tag "uuid" of {_item}
        set {_enchantments::*} to keyed {custom enchantments::%{_uuid}%::*}
        for {_ce}, {_level} in {_enchantments::*}:
            set {_} to {_}

        set {_elapsed} to (current ns - {_now}) / 1000000
        send "read %size of {_enchantments::*}%: %{_elapsed}% ms"

local function enchantItemNEW(item: item stack, enchantment: string, level: integer) :: item stack:
    set {_meta} to {_item}.getItemMeta()
    set {_pdc} to {_meta}.getPersistentDataContainer()
    if {_pdc}.has({-enchant namespace}, PersistentDataType.TAG_CONTAINER) is false:
        {_pdc}.set({-enchant namespace}, PersistentDataType.TAG_CONTAINER, {_pdc}.getAdapterContext().newPersistentDataContainer())
    set {_enchant container} to {_pdc}.get({-enchant namespace}, PersistentDataType.TAG_CONTAINER)
    {_enchant container}.set(new NamespacedKey("skript", {_enchantment}), PersistentDataType.LONG, {_level})
    {_pdc}.set({-enchant namespace}, PersistentDataType.TAG_CONTAINER, {_enchant container})
    {_item}.setItemMeta({_meta})
    return {_item}

local function getEnchantmentsNEW(item: item stack) :: objects:
    set {_meta} to {_item}.getItemMeta()
    set {_pdc} to {_meta}.getPersistentDataContainer()
    set {_enchant container} to {_pdc}.get({-enchant namespace}, PersistentDataType.TAG_CONTAINER)
    if {_enchant container} isn't set:
        return {_}
    for {_key} in ...{_enchant container}.getKeys():
        set {_enchantments::%{_key}.getKey()%} to {_enchant container}.get({_key}, PersistentDataType.LONG)
    return {_enchantments::*}

import:
    me.mrscopes.enchantments.CustomEnchantments

command /pdc:
    trigger:
        set {_item} to new ItemStack(Material.DIAMOND_SWORD)
        CustomEnchantments.setEnchantmentLevel({_item}, "custom_enchant_1", 1)

        for {_level}, {_enchantment} in ...CustomEnchantments.getEnchantments({_item}).entrySet():
            send "Enchantment: %{_enchantment}.getKey()% Level: %{_level}%"